### ISSUE TITLE
contract.watchEvent.Transfer 没有任何动静

### ISSUE THREAD

**Issue by phpmac** [NomicFoundation/hardhat#5159] opened 2024-04-23 05:55 UTC
### Version of Hardhat

^2.22.3

### What happened?

```
import hre from "hardhat";

async function main() {
  const accounts = await hre.viem.getWalletClients();

  const contract = await hre.viem.getContractAt(
    "USDT",
    "0x55d398326f99059ff775485246999027b3197955"
  );

  contract.watchEvent.Transfer(
    {
      onLogs: (logs) => console.log(`logs`, logs),
      onError: (error) => console.log(`error`, error),
    }
  );
}

// We recommend this pattern to be able to use async/await everywhere
and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});


```
This is my running code based on hardhat+viem. Please don't close it directly. I'm very troubled. Why can't I still monitor the recording? Can you give me some advice?

### Minimal reproduction steps

```sh
npx hardhat run scripts/fcm.ts --network bsc
```

**Comment by schaable** [comment] 2024-05-06 14:10
Hi @phpmac, the syntax for your watch event is incorrect; the first parameter should be the arguments, followed by the options. It should look like this:

```
contract.watchEvent.Transfer(
  {},
  {
    onLogs: (logs: any) => console.log(`logs`, logs),
    onError: (error: any) => console.log(`error`, error),
  }
);
```

![image](https://github.com/NomicFoundation/hardhat/assets/1165424/af17bbbc-761a-469e-8f08-e14c5204da0b)

You can find more information [here](https://viem.sh/docs/contract/getContract#usage).

I'm closing this issue as it's not a bug, but please feel free to ask any further questions in the [discussions](https://github.com/NomicFoundation/hardhat/discussions) section.

**Closed by schaable** 2024-05-06 14:10 UTC
Labels: status:triaging
