### ISSUE TITLE
 event args array is not available in the transaction receipt #3800 

### ISSUE THREAD

**Issue by makinghappen** [NomicFoundation/hardhat#3801] opened 2023-03-29 11:44 UTC
### Version of Hardhat

2.13

### What happened?

event args array is not available in the transaction receipt

```
{
  transactionIndex: 4,
  blockNumber: 33710309,
  transactionHash: '0x5f9893f7a19d8c774a0ff91bd62756ddbd68c0bcc3c4b0b6082daa20a924d4ff',
  address: '0x0000000000000000000000000000000000001010',
  topics: [
    '0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63',
    '0x0000000000000000000000000000000000000000000000000000000000001010',
    '0x0000000000000000000000003089c7c8f5aa2be20531634df9c12b72eaa79b0a',
    '0x000000000000000000000000c26880a0af2ea0c7e8130e6ec47af756465452e8'
  ],
  data: '0x000000000000000000000000000000000000000000000000000143168667c60000000000000000000000000000000000000000000000000025f72f82d21626d5000000000000000000000000000000000000000000001d059ecbf0cf4a1014c000000000000000000000000000000000000000000000000025f5ec6c4bae60d5000000000000000000000000000000000000000000001d059ecd33e5d077dac0',
  logIndex: 11,
  blockHash: '0xcc7bb29c92f4e7cd4b4ef2dc48577a4b0d6792b5f0bb68a771d945c701b35611',
  removeListener: [Function (anonymous)],
  getBlock: [Function (anonymous)],
  getTransaction: [Function (anonymous)],
  getTransactionReceipt: [Function (anonymous)]
}
```

### Minimal reproduction steps

a dependency you will need:
`npm install witnet/witnet-solidity-bridge#feat/bytecodes`

hardhat task code:

```
const fs = require("fs/promises");
const path = require("node:path");

const ecosystem = "polygon";
const network = "polygon.goerli";

const witnetAddresses = require("witnet-solidity-bridge/migrations/witnet.addresses")[ecosystem][network];

console.log(witnetAddresses)

let contractAddresses;

(async () => {
  const contractAddressesJson = await fs.readFile(path.join(__dirname, `../abi/addresses.json`));
  if (typeof contractAddressesJson !== "undefined") {
    contractAddresses = JSON.parse(contractAddressesJson);
  } else {
    console.log(`contract addresses file not found at ../abi/addresses.json`);
  }
})();

task("witnetConfig", "configure Witnet facet")
  // .addParam("taskContract", "task contract")
  // .addParam("messageText", "message text")
  .setAction(async function (taskArguments, hre, runSuper) {
    await configureWitnet();
    console.log(`updated witnet config`);
  });

async function configureWitnet() {
  let requestHashes;
  try {
    const existingRequestHashes = await fs.readFile(path.join(__dirname, `../abi/witnet-requesthashes.json`));
    if (typeof existingRequestHashes !== "undefined") {
      requestHashes = JSON.parse(existingRequestHashes);
    }
  } catch (error) {
    requestHashes = {
      hashes: {},
    };
  }

  console.log("verifying");
  if(typeof requestHashes.hashes[this.__hardhatContext.environment.network.config.chainId] == "undefined"){
    requestHashes.hashes[this.__hardhatContext.environment.network.config.chainId] = {};
  }

  const witnetBytecodes = await ethers.getContractAt("IWitnetBytecodes", witnetAddresses.WitnetBytecodes);
  // const witnetV2 = await ethers.getContractAt('WitnetV2', diamondAddress)

  // WitnetV2.DataRequestMethods
  // /* 0 */ Unknown,
  // /* 1 */ HttpGet,
  // /* 2 */ Rng,
  // /* 3 */ HttpPost
console.log(requestHashes)

  if (
    typeof requestHashes.hashes[this.__hardhatContext.environment.network.config.chainId] == "undefined" ||
    typeof requestHashes.hashes[this.__hardhatContext.environment.network.config.chainId].NewDataSourceHash ==
      "undefined"
  ) {
    console.log(`verifying datasource`);

    await witnetBytecodes.on("NewDataSourceHash", (NewDataSourceHash, event) => {
      console.log("received event");
      console.log(NewDataSourceHash, type);
    });
    const dataSource = await witnetBytecodes.verifyDataSource(
      1, // requestMethod
      /* requestSchema */ "",
      /* requestAuthority */ "https://api.github.com", // => will be substituted w/ WittyPixelsLib.baseURI() on next mint
      /* requestPath */ "repos/\\0\\/pulls", // => will by substituted w/ tokenId on next mint
      /* requestQuery */ "state=all",
      /* requestBody */ "",
      [], // requestHeaders
      "0x8218771869" // requestRadonScript
      , { gasLimit: 8000000 }
    );

    const dataSourceReceipt = await dataSource.wait();
    console.log(dataSourceReceipt.events[0])
    }
}

```

### Search terms

hardhat transactionReceipt events args

**Comment by fvictorio** [comment] 2023-04-04 09:20
Hi @makinghappen, can you provide a more minimal example showing what the issue is? I only skimmed the code but it seems clear to me that it's not complete (and that it would have too much noise if it was).

I'm tentatively closing this, but will re-open if you can provide the 
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by fvictorio** 2023-04-04 09:20 UTC
Labels: status:triaging

**Comment by makinghappen** [comment] 2023-04-05 10:35
issue solved, was actually an issue with the smart contract
