### ISSUE TITLE
block.chainid  returning 0 in view functions in macos

### ISSUE THREAD

**Issue by xihucuyu888** [NomicFoundation/hardhat#3476] opened 2022-12-28 09:38 UTC
block.chainid  returning 0 in view functions in macos

**Comment by fvictorio** [comment] 2022-12-28 10:36
I can't reproduce this. I deployed this contract:

```solidity
contract Foo {
  function f() public view returns (uint) {
    return block.chainid;
  }
}
```

deployed it, called `await foo.f()` and got the right result.

I'm not in macos but it's very unlikely that the OS is relevant here.

I'm going to close this now, but I'll re-open it if you can provide minimal reproduction steps.

**Closed by fvictorio** 2022-12-28 10:36 UTC
Labels: status:triaging

**Comment by xihucuyu888** [comment] 2022-12-28 11:02
> I can't reproduce this. I deployed this contract:
> 
> ```solidity
> contract Foo {
>   function f() public view returns (uint) {
>     return block.chainid;
>   }
> }
> ```
> 
> deployed it, called `await foo.f()` and got the right result.
> 
> I'm not in macos but it's very unlikely that the OS is relevant here.
> 
> I'm going to close this now, but I'll re-open it if you can provide minimal reproduction steps.

same steps,not working in macos 
and pls check https://github.com/NomicFoundation/hardhat/actions/runs/2397733616/jobs/3624124733

**Comment by fvictorio** [comment] 2022-12-28 12:34
> and pls check https://github.com/NomicFoundation/hardhat/actions/runs/2397733616/jobs/3624124733
> job not passed in macos

That's not a failure, our CI is currently not running on macos because there are some problems with GitHub runners that cause a lot of false negatives through timeouts.

> same steps,not working in macos

I tested it in macos now and it also worked. Here's a repo that shows it: https://github.com/fvictorio/hardhat-3476 Clone, `npm i` and `npx hardhat run scripts/deploy.js` to check for yourself.

**Comment by xihucuyu888** [comment] 2022-12-29 03:10
> > and pls check https://github.com/NomicFoundation/hardhat/actions/runs/2397733616/jobs/3624124733
> > job not passed in macos
> 
> That's not a failure, our CI is currently not running on macos because there are some problems with GitHub runners that cause a lot of false negatives through timeouts.
> 
> > same steps,not working in macos
> 
> I tested it in macos now and it also worked. Here's a repo that shows it: https://github.com/fvictorio/hardhat-3476 Clone, `npm i` and `npx hardhat run scripts/deploy.js` to check for yourself.

upgrade "hardhat" to "^2.12.4" and it works, thank you !
