### ISSUE TITLE
Verifying a contract with 

### ISSUE THREAD

**Issue by keyboard-clacker** [NomicFoundation/hardhat#2448] opened 2022-03-03 03:28 UTC
I'm not sure if this is just something I'm doing wrong or a bug, but I have a contract that looks something like this:

```solidity
contract Staking {
  SomeERC721Contract public immutable nftContract;

  constructor(SomeERC721Contract nftContract_) {
    nftContract = nftContract_;
  } 

  function someFunction() public {
    nftContract.hello();
  }
}
```
I can deploy this fine, but when I go to verify the contract, I can't seem to figure out how to pass the instance of `SomeERC721Contract` to the verifier. In my hardhat deploy script I can just pass in the address for the contract and it seems to convert it to the contract instance itself, but on verify it goes into the fallback verification step and then fails with some generic error. Any ideas?

Cheers,
Kyle

**Comment by Remscar** [comment] 2022-03-03 03:38
May be related to https://github.com/NomicFoundation/hardhat/issues/2447

**Comment by alcuadrado** [comment] 2022-03-03 12:32
Duplicate of #2447, which was already fixed by Etherscan.

**Closed by alcuadrado** 2022-03-03 12:32 UTC
