### ISSUE TITLE
WebSocket Server doesn't support Batch requests, though HTTP server does.

### ISSUE THREAD

**Issue by tenbits** [NomicFoundation/hardhat#3571] opened 2023-01-12 17:58 UTC
### Version of Hardhat

2.12.6

### What happened?

WebSocket server does not accept the array of RPC messages. The message is not valid:

[`handleWs` handler.ts#L91](https://github.com/NomicFoundation/hardhat/blob/654e7cd44a0f1229a44538f73584c538961a117e/packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts#L91)

Though the HTTP server accepts arrays: [`handleHttp` handler.ts#L41](https://github.com/NomicFoundation/hardhat/blob/654e7cd44a0f1229a44538f73584c538961a117e/packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts#L41)

### Minimal reproduction steps

Send a message to `ws://127.0.0.1:8545`

```json
[
    {
        "jsonrpc": "2.0",
        "id": 17,
        "method": "eth_getTransactionReceipt",
        "params": [
            "0x188f8a6a69535e9e1e5fd8a9ad844325f4f01157e039035f0f16de14a97a3b69"
        ]
    },
    {
        "jsonrpc": "2.0",
        "id": 18,
        "method": "eth_getTransactionReceipt",
        "params": [
            "0x33b1a6378404ab21d213ff2d9cbe660417fdacb990de054651637537f663ceb6"
        ]
    }
]
```

> Same body requests to `POST https://127.0.0.1:8545` works.

### Search terms

BatchRequest

**Comment by fvictorio** [comment] 2023-01-13 09:08
I think this is a duplicate of https://github.com/NomicFoundation/hardhat/issues/1324. I edited that issue's description to include your search terms.

**Closed by fvictorio** 2023-01-13 09:08 UTC
Labels: status:triaging

**Comment by tenbits** [comment] 2023-01-13 09:48
Sorry, indeed, I missed that.
