### ISSUE TITLE
`console.log` uses `uint` rather than `uint256` in `abi.encodeWithSignature`

### ISSUE THREAD

**Issue by lukehutch** [NomicFoundation/hardhat#2890] opened 2022-07-04 13:08 UTC
`hardhat/console.sol` defines functions like the following:

```solidity
function log(string memory p0, uint p1) internal view {
    _sendLogPayload(abi.encodeWithSignature("log(string,uint)", p0, p1));
}
```

This should be `_sendLogPayload(abi.encodeWithSignature("log(string,uint256)", p0, p1));`, since the full names of aliases like `uint` must be used in ABI encoding.

I assume the "contract" at `CONSOLE_ADDRESS = address(0x000000000000000000636F6e736F6c652e6c6f67)` is not a contract but a piece of HardHat native code, which expects function selectors derived from params of the form `log(string,uint)` rather than `log(string,uint256)`. However this should be changed to make the ABI encoding for the console handler the same as the ABI for Solidity.

**Comment by fvictorio** [comment] 2022-07-04 14:35
Hi @lukehutch, thanks a lot for opening this, but I think it's a duplicate of https://github.com/NomicFoundation/hardhat/issues/2666.

**Closed by fvictorio** 2022-07-04 14:35 UTC

**Comment by lukehutch** [comment] 2022-07-04 15:02
Sorry, I missed that. Thanks for getting so responsive!
