### ISSUE TITLE
Hardhat in a docker container, compiller redownloading

### ISSUE THREAD

**Issue by bwintertkb** [NomicFoundation/hardhat#3587] opened 2023-01-16 15:22 UTC
Hi guys,

Thanks for looking at this! I'm trying to use hardhat in my local docker container but everytime I restart the container I need to redownload the compiler. Do you guys know where the compiler is stored so I can add a volume for it? I can't seem to find the location.

Thanks in advance!

**Comment by fvictorio** [comment] 2023-01-19 16:52
It depends on the system, but in your case it sould probably be under `~/.cache/hardhat-nodejs/`.

Depending on how you are building your image, you might just force a download when the image is built. Something like:

```dockerfile
RUN mkdir foo && cd foo && npm init -y && npm install hardhat && touch hardhat.config.js && mkdir contracts && touch contracts/Foo.sol && npx hardhat compile && cd .. && rm -r foo
```

...give or take. This will use the default compiler version though, so you might want to replace `touch hardhat.config.js` with something like `echo 'module.exports = { solidity: "0.8.17" }' > hardhat.config.js`

I'm going to close this for bookkeeping reasons, but if you have some specific question feel free to leave another comment.

**Closed by fvictorio** 2023-01-19 16:52 UTC
Labels: status:triaging

**Comment by sjkelleyjr** [comment] 2023-04-08 23:30
I tried doing something similar to [this](https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/ci-builder/Dockerfile#L60-L87), but for some reason when I run `await hre.run('compile')` it doesn't recognize that the compiler has already been installed and re-installs it.  Any idea what's going on here?

**Comment by fvictorio** [comment] 2023-04-10 10:44
Uhm, hard to know without more context. But the way I usually approach this issues when I'm creating a Docker image is to use `docker run --rm -it <your-image> sh` and then check the result.

So in this case, where you want an image with the compiler pre-downloaded, I would run that and then `ls` the directory where the compilers are supposed to be pre-downloaded (again, that's probably `~/.cache/hardhat-nodejs/.`) and try to figure it out from there.

**Comment by sjkelleyjr** [comment] 2023-04-10 14:33
I can see the compilers in the appropriate directory when the docker image is created, the problem is that hardhat doesn't detect that it's already in that directory and re-installs it.  

I primarily just wanted confirmation that I didn't need to do anything else.  Hardhat uses that directory to determine whether it needs to install the compiler or not and nothing else, correct?

**Comment by fvictorio** [comment] 2023-04-13 08:28
I don't remember all the details of the downloading algorithm (it's a bit more complex than it seems), but yeah, that's the essence of it.
