### ISSUE TITLE
npx compile/deploy --> "Downloading compiler 0.8.18"

### ISSUE THREAD

**Issue by GildedHonour** [NomicFoundation/hardhat#4013] opened 2023-06-10 17:29 UTC
### Version of Hardhat

2.14.1

### What happened?

```
$ npx hardhat compile
Downloading compiler 0.8.18

[................]

$ npx hardhat compile
Downloading compiler 0.8.18

$ npx hardhat run --network arbitrum_goerli scripts/deploy2.ts
Downloading compiler 0.8.18
```

All the time - `Downloading compiler 0.8.18`

### Minimal reproduction steps

see above

**Comment by fvictorio** [comment] 2023-06-11 07:02
This is probably a duplicate of https://github.com/NomicFoundation/hardhat/issues/3877 I'll re-open if you aren't using node v18.16.0.

**Closed** 2023-06-11 07:02 UTC
Labels: status:triaging
