### ISSUE TITLE
[hardhat-waffle] Transaction reverted without a reason when using mock contract

### ISSUE THREAD

**Issue by xuhcc** [NomicFoundation/hardhat#1046] opened 2020-11-23 17:49 UTC
One of the unit tests in my project started to fail for no obvious reason after migration from buidler to hardhat. The test is using Waffle's mock contract, but maybe it is not relevant. I'm not sure how to provide a minimal reproducible example because the bug apparently manifests itself only in very specific circumstances. So here's the test:

https://github.com/xuhcc/monorepo/blob/963d252f87f876a0e39bff46c95778dda93dcc8f/contracts/tests/round.ts#L210-L219

This is the part of the contract which is being tested:

https://github.com/xuhcc/monorepo/blob/963d252f87f876a0e39bff46c95778dda93dcc8f/contracts/contracts/FundingRound.sol#L144-L145

The result:

```
     AssertionError: Expected transaction to be reverted with FundingRound: User has not been verified, but other exception was thrown: Error: Transaction reverted without a reason and without a valid sourcemap provided by the compiler. Some line numbers may be off. We strongly recommend upgrading solc and always using revert reasons.
```

Interestingly, the test passes if I insert `console.log` statement in the right place:

https://github.com/xuhcc/monorepo/commit/177d7bae80e454af2661f1ba858dcbd376bd9d82#diff-b094db7ce2f99cbcbde7ec178a6754bac666e2192f076807acbd70d49ddd0559

- hardhat v2.0.3
- hardhat-waffle v2.0.0
- ethereum-waffle v3.0.2
- solidity v0.6.12

**Comment by bingen** [comment] 2020-11-25 14:42
It’s happening to us on buidler too, without migrating to hardhat.

**Comment by xuhcc** [comment] 2020-11-25 15:26
In my case pre-migration version of `@nomiclabs/buidler` were 1.3.8. So maybe the bug was introduced somewhere between 1.3.8 and 1.4.4 :thinking:

**Comment by bingen** [comment] 2020-11-25 18:47
Inspired by your `console.log` workaround, I realized that this change in our codebase seems to fix the problem:

![Screenshot from 2020-11-25 19-44-39](https://user-images.githubusercontent.com/701095/100269511-f213aa00-2f56-11eb-927e-5d1affc8ba0b.png)

Not sure if it has been just a coincidence, still investigating. But just in case it helps you.

**Comment by bingen** [comment] 2020-11-25 19:46
It was probably a coincidence, still having the issue.

**Comment by xuhcc** [comment] 2020-11-29 11:36
The bug was introduced in one of commits between buidler-core 1.4.5 and 1.4.6.

**Comment by xuhcc** [comment] 2020-11-29 11:52
@fvictorio Do you have any ideas on what might be causing this? If you need more info I can try to find the exact commit that breaks the test.

**Comment by bingen** [comment] 2020-11-30 12:53
Thanks a lot @xuhcc !! As we haven’t migrated to hardhat yet, pinning to 1.4.4 seems to fix the issue for us.

**Comment by fvictorio** [comment] 2020-11-30 15:40
Hi @xuhcc, I'll try to take a look at this as soon as I can.

**Comment by bingen** [comment] 2020-11-30 16:04
That was too fast. I tried with 1.4.4 and 1.4.3 but hit the error again. :'(

**Comment by fvictorio** [comment] 2020-12-01 16:23
I think you might be getting an error similar to this one https://github.com/ethereum/solidity/issues/9006 The tl;dr is that in some solc versions, revert strings *sometimes* might not be correctly detected. I think that was supposed to be fixed (in 0.6.9 I think?), but maybe some more edge case is being triggered here. Notice that if you disable the optimizer, this problem doesn't happen (you have to enable `allowUnlimitedContractSize` if you do that, btw).

It is entirely possible that there's a fix that could be done on our side, but to be honest I don't think we'll have time to look into this soon. Plus, it might be the case that the problem comes from solc and not from hardhat.

I'm not sure what's your best course of action here. One option is to just check that the transaction reverts, and not the error message. It's less than ideal, but at least your tests will work again.

Another, more involved option is to run your tests in two modes: with and without the optimizer. So you'll need something like an environment variable to switch between the modes. When the optimizer is disabled, you disable it in the config, enable the unlimited contract size, and check the revert error in that test. When it's enabled, you only check that the tx reverts. Probably not worth the effort, though.

You can also try upgrading everything to solidity 0.7, but I can't promise that that will fix the issue :sweat_smile:

**Comment by alcuadrado** [comment] 2020-12-01 16:44
> revert strings _sometimes_ might not be correctly detected.

#9006 happens when a revert reason is empty, so this may be a different error.

**Comment by xuhcc** [comment] 2020-12-01 20:04
@fvictorio If the problem comes from solc, why it manifested itself after the change in `buidler-core`? I found the exact commit after which the test started to fail: https://github.com/nomiclabs/hardhat/commit/abdebd416f0cf06f2b8494520d3bd225ba20fc1f

**Comment by fvictorio** [comment] 2020-12-01 20:22
> If the problem comes from solc, why it manifested itself after the change in `buidler-core`?

Sorry, my explanation wasn't very good. I meant that this error comes from how hardhat uses the information given by solc, so these kind of errors are at the interface between the two and it's hard to know beforehand where the problem lays. That being said, as @alcuadrado mentioned this is a different scenario to the linked issue, so it's probably a problem on our side.

> I found the exact commit after which the test started to fail: [abdebd4](https://github.com/nomiclabs/hardhat/commit/abdebd416f0cf06f2b8494520d3bd225ba20fc1f)

Thanks, that will help a lot when we look into this.

**Comment by xuhcc** [comment] 2020-12-02 00:17
This patch fixes the failing test for me:
```patch
diff --git a/packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts b/packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts
index af4aa4ab..fbcc19f0 100644
--- a/packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts
+++ b/packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts
@@ -435,7 +435,6 @@ function astFunctionDefinitionToSelector(functionDefinition: any): Buffer {
 
   // The function selector is available in solc versions >=0.6.0
   if (functionDefinition.functionSelector !== undefined) {
-    return Buffer.from(functionDefinition.functionSelector, "hex");
   }
 
   for (const param of functionDefinition.parameters.parameters) {
@@ -454,10 +453,11 @@ function astFunctionDefinitionToSelector(functionDefinition: any): Buffer {
 
     // The rest of the function parameters always have their typeName node defined
     const typename = param.typeName;
-    if (
-      typename.nodeType === "ArrayTypeName" ||
-      typename.nodeType === "FunctionTypeName"
-    ) {
+    if (typename.nodeType === "ArrayTypeName") {
+      paramTypes.push(`${toCanonicalAbiType(typename.baseType.name)}[]`);
+      continue;
+    }
+    if (typename.nodeType === "FunctionTypeName") {
       paramTypes.push(typename.typeDescriptions.typeString);
       continue;
     }

```

**Comment by alcuadrado** [comment] 2020-12-04 00:41
Thank you @xuhcc. I'm investigating this and other "transaction reverted" errors. I'll take a deeper look at this tomorrow.

**Comment by livingrock7** [comment] 2020-12-05 19:46
The error I am getting is 
```Error: Transaction reverted without a reason
      at new TransactionExecutionError (node_modules/hardhat/src/internal/hardhat-network/provider/errors.ts:97:16)
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:953:16)
      at HardhatNode.estimateGas (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:517:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
Do update what I need to do to get it fixed.
I am using below verisons 

"@typechain/ethers-v5": "^4.0.0",
"ethereum-waffle": "^3.2.0",
    "ethers": "^5.0.21",
    "hardhat": "^2.0.3",
    "hardhat-typechain": "^0.3.3",

**Comment by fvictorio** [comment] 2020-12-18 17:26
Hi everyone. Can you check if you still have these issues in the latest version of hardhat (`2.0.6`)?

**Comment by bingen** [comment] 2020-12-18 18:47
Yes, unfortunately it still happens to us. :cry:

**Comment by xuhcc** [comment] 2020-12-18 20:55
Can confirm, the problem is still present in 2.0.6.

**Comment by sshmaxime** [comment] 2021-03-22 15:23
The problem is present in 2.1.1 too. Exact same problem. Any news on that issue ?

**Comment by sshmaxime** [comment] 2021-03-22 16:30
How to you guys deals with it ? Do you leave empty `console.log("")` in your contract ? @bingen

**Comment by xuhcc** [comment] 2021-03-22 17:52
I made some unrelated changes to the contract and the problem disappeared :shrug:

**Comment by bingen** [comment] 2021-03-26 15:51
> How to you guys deals with it ?

Mostly we are commenting out the part where we check the error string :cry: 
We try to manually verify that it’s doing what we expect, and use the help of coverage to make sure we trigger all the errors, but so far we have already had situations where we thought we were testing different things due to this issue. In my opinion, it’s more important than it seems. Actually, when we started having the error strings I felt so relieved, as testing before was way more tedious.

**Comment by sshmaxime** [comment] 2021-03-26 16:14
That's annoying tbh. We are basically waiting for this fix to completely switch to Hardhat ... However, good news the fix should come up in the upcoming weeks as the their team seemed to figured out where the problem was coming from. Hoping for it to be fixed asap

**Comment by bingen** [comment] 2021-03-26 16:42
Good news!!! (Just curious, where did you get that info from?)

**Comment by sshmaxime** [comment] 2021-03-26 16:44
Hardhat's discord :) https://discord.gg/P4F3yRcsvE

And here is the link of the message: https://discord.com/channels/750408878008827925/750408878008827928/824003404623773776

**Comment by bingen** [comment] 2021-03-26 17:17
Nice, thanks!!

**Comment by sshmaxime** [comment] 2021-04-01 14:15
In addition, I spotted another case when this issue occurs, which is even odder from what it seems.

When running test on one file everything is fine. But when running our WHOLE tests all at once using `hardhat test` this one file that was tested successfully when solo testing, is now throwing: `Error: Transaction reverted without a reason`. 

Overall, out of our 37k+ tests, 160 are failing with either `Error: Transaction reverted without a reason` OR `AssertionError: Expected transaction to be reverted with XXX, but other exception was thrown: Error: Transaction reverted without a reason`.

It is sad, we really want to move to hardhat but cannot until this issue is fixed :(

**Comment by bingen** [comment] 2021-05-12 08:16
Hi :wave: 

any news on this?

Thanks!

**Comment by fvictorio** [comment] 2021-05-12 16:39
Hey @bingen, sorry but we haven't had time to look into this. I'll try to take another look as soon as I can (whenever that happens).

**Comment by sshmaxime** [comment] 2021-05-26 12:40
I hope you'll have the time to have a look on this ASAP 🙏

**Comment by fvictorio** [comment] 2022-12-30 10:40
Hi. I'm super sorry for never responding here again.

It's been a while since this was reported, and we've had (and fixed) similar reports. That, and the fact that reproduction steps from two years ago will probably not be very useful, means that there isn't a lot for me to do here.

So I'm going to (tentatively) close this issue. If someone is still running into something like this and has reproduction steps, please comment here or (preferably) open a new issue.

**Closed by fvictorio** 2022-12-30 10:40 UTC
Labels: type:bug, priority:high
