### ISSUE TITLE
`await contract.waitForDeployment()` call kills deployment process to Infura with `hardhat-toolbox@3.0.0`

### ISSUE THREAD

**Issue by markin-io** [NomicFoundation/hardhat#4006] opened 2023-06-08 12:31 UTC
### Version of Hardhat

2.15.0

### What happened?

`contract.waitForDeployment()` call seem to be killing `hadhat run` process when deploying on Goerli via Infura.

### Minimal reproduction steps

- Configure `harhat.config.js` to deploy on Goerli network via Infura
- Write `deploy` script as described in the Tutorial https://hardhat.org/hardhat-runner/docs/guides/deploying
- `$ npx hardhat run scripts/deploy.js --network goerli`

### Expected behavior
- Contract deployed to Goerli network
- `Lock with ${...}ETH and unlock timestamp ${...} deployed to ${...}` printed into console

### Actual behavior
- Contract deployed to Goerli network
- `await contract.waitForDeployment()` interrupts process and nothing is printed to the console

### Workaround
Reverting to `hardhat-toolbox@2.x.x` solves the problem.

### Sample project
- https://github.com/markin-io/whitelist-dapp/tree/master/hardhat-tutorial

### Search terms

deployment, interrupted, hardhat-toolbox, infura

**Comment by fvictorio** [comment] 2023-06-08 14:11
Thanks @markin-io, I can confirm this. I'll try to get it fixed asap.

**Comment by fvictorio** [comment] 2023-06-08 19:58
Hey @markin-io, I have a fix ready for this but npm publish is not working right now :disappointed: I'll try to publish it early tomorrow.

**Comment by fvictorio** [comment] 2023-06-08 21:14
We just published [hardhat-ethers@3.0.2](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-ethers%403.0.2) that should fix this problem. Please let me know if it doesn't!

**Comment by markin-io** [comment] 2023-06-10 08:49
@fvictorio it's fixed, thank you!

**Comment by mshahzadmalik1995** [comment] 2023-07-09 14:29
Its not working in sepolia.
await contract.waitForDeployment kill the deployment process.

**Comment by alcuadrado** [comment] 2023-07-09 17:04
Reopening as this was also reported on discord

**Comment by fvictorio** [comment] 2023-08-30 16:45
`.waitForDeployment` works for me in sepolia and BSC testnet, using the latest versions of the plugins.

If someone is running into this, please try upgrading `ethers` and `@nomicfoundation/hardhat-ethers` to the latest versions. For example, with npm:

```
npm i ethers@latest @nomicfoundation/hardhat-ethers@latest
```

If this doesn't fix the issue, then I'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to look into it.

Tentatively closing this again, happy to re-open if the problem happens with the latest versions _and_ someone can provide a reproduction example.

**Closed by fvictorio** 2023-08-30 16:45 UTC
Labels: type:bug, status:ready
