### ISSUE TITLE
allowUnlimitedContractSize flag not working

### ISSUE THREAD

**Issue by Benen66** [NomicFoundation/hardhat#3208] opened 2022-09-22 22:47 UTC
I've been trying to run a fork of Set Protocol on localhost using hardhat and I'm getting a ProviderError: Error: Transaction reverted: trying to deploy a contract whose code is too large even when the file in question (SetTokenCreator.sol) is only a 100 lines long and I've enabled allowUnlimitedContractSize: true.

My hardhat.config looks like this:
```
solidity: "0.8.11",
  defaultNetwork: "hardhat",
  hardhat: {
    allowUnlimitedContractSize: true,
    gas: 12000000,
    blockGasLimit: 0x1fffffffffffff,
    ignoreUnknownTxType: true,
  },
  localhost: {
    allowUnlimitedContractSize: true,
    timeout: 200000,
    gas: 12000000,
    blockGasLimit: 0x1fffffffffffff,
    ignoreUnknownTxType: true,
  },
```
the ignoreUnknownTxType is because I'm attempting to fork Arbitrum using the patch in #2995. The patch is working correctly and the unknown transactions are indeed being ignored correctly. My hardhat reset in the test file looks like this:
```
await hre.network.provider.request({
      method: 'hardhat_reset',
      params: [
          {
            allowUnlimitedContractSize: true,
              forking: {
                  jsonRpcUrl: 'https://rinkeby.arbitrum.io/rpc',
                  // enabled: true,
                  // blockNumber: 15216420,
                  ignoreUnknownTxType: true,
                  allowUnlimitedContractSize: true,
              },
          },
      ],
  })
const setTokenCreator = await hre.ethers.getContractFactory("SetTokenCreator");
 const setTokenCreatorInterface = await setTokenCreator.deploy(controllerInterface.address, {gasLimit: BigNumber.from("655592")});
 await setTokenCreatorInterface.deployed();
```
The full error message is 
```
Error: Transaction reverted: trying to deploy a contract whose code is too large
      at SetTokenCreator.constructor (contracts/protocol/SetTokenCreator.sol:50)
```
**why is allowUnlimitedContractSize not kicking in?** I'm confused because in a couple of old projects I didn't have this problem. And **a couple of bigger contracts in terms of code length are deploying correctly in this same file**

**Comment by fvictorio** [comment] 2022-10-31 18:05
This might be a wrong diagnostic, telling you that the problem is a "contract too large" when it's actually running out of gas. Can you try increasing the gas limit of the transaction?

**Comment by fvictorio** [comment] 2022-12-24 12:27
I'm pretty sure this is caused by https://github.com/NomicFoundation/hardhat/issues/3420, so I'm going to close this one.

**Closed by fvictorio** 2022-12-24 12:27 UTC

**Comment by JustCallMeDavid** [comment] 2022-12-24 17:45
Ciao @fvictorio, I just had the same issue and indeed increasing the gas limit of the transaction when deploying it seems to have fixed it. Adding `allowUnlimitedContractSize: true` to the `hardhat.config.js` file did not make a difference.

**Comment by fvictorio** [comment] 2022-12-24 21:13
> Maybe also worth methioning: I checked the size of my contract's bytecode and it should be ~16kb, well under the 24kb limit of EIP170.

This is a bit confusing. The EIP170 limit is about the size of the resulting bytecode. But if the deployment code spends a lot of gas (say, there's a loop in the constructor or whatever) then you might hit #3420. This is, of course, a bug in Hardhat.
