### ISSUE TITLE
hardhat's error stack is not usable

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat#3444] opened 2022-12-22 08:27 UTC
Using factory will make hardhat's error stack become such as following,  18695 lines of errors, hardhat just simply print the source code no matter what...

![image](https://user-images.githubusercontent.com/33961674/209090835-9070fbc4-0cc2-488d-865d-07fee634c72a.png)

this error seems was reported [long time ago](https://github.com/NomicFoundation/hardhat/issues/2848) and hardhat is still not wiling to take it serious. It's not really usable at the moment, people always need to set gasLimit to see the real errors

Anyway to just turn off the gas estimation? it's not really useful in test environment unless people really want.

**Comment by fvictorio** [comment] 2022-12-22 11:40
Repeating [my comment](https://github.com/NomicFoundation/hardhat/issues/2848#issuecomment-1362736678) in the related issue:

I just closed two other issues that were similar to this, because I couldn't reproduce them with the latest version of Hardhat, ethers.js and hardhat-ethers. @GopherJ if you are using the latest version of those packages and still running into this problem, please provide a 
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by fvictorio** [comment] 2022-12-22 12:56
Disregard that, I already understand under which conditions this happen. I will look into this.

**Comment by GopherJ** [comment] 2022-12-23 15:02
hi @fvictorio I think you can check this [action](https://github.com/para-space/paraspace-core/actions/runs/3763583532/jobs/6397218527), it's easily reproducible in our repo

**Comment by fvictorio** [comment] 2023-01-13 23:08
Closing this one in favor of #3582.

**Closed by fvictorio** 2023-01-13 23:08 UTC
Labels: status:needs-more-info
