### ISSUE TITLE
No overload matches this call - Lock's deploy script

### ISSUE THREAD

**Issue by 0xartcro** [NomicFoundation/hardhat#4118] opened 2023-07-05 23:36 UTC
### Version of Hardhat

2.16.1

### What happened?

Installed latest version of Hardhat including Toolbox 3 and after opening Lock's `deploy.ts` script it shows errors:

```
No overload matches this call.
  Overload 1 of 4, '(name: "Lock", args: any[], signerOrOptions?: Signer | FactoryOptions | undefined): Promise<Lock>', gave the following error.
    Argument of type '{ value: bigint; }' is not assignable to parameter of type 'Signer | FactoryOptions | undefined'.
      Object literal may only specify known properties, and 'value' does not exist in type 'Signer | FactoryOptions'.
  Overload 2 of 4, '(name: string, args: any[], signerOrOptions?: Signer | FactoryOptions | undefined): Promise<Contract>', gave the following error.
    Argument of type '{ value: bigint; }' is not assignable to parameter of type 'Signer | FactoryOptions | undefined'.
      Object literal may only specify known properties, and 'value' does not exist in type 'Signer | FactoryOptions'.ts(2769)
```

Running the script compiles and deploys everything properly though.

Using Visual Studio Code.

### Minimal reproduction steps

1. Install latest version of hardhat

My `package.json` file:
```json
{
  "name": "hardhat",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "hardhat": "^2.16.1",
    "typescript": "^5.1.6"
  },
  "dependencies": {
    "@openzeppelin/hardhat-upgrades": "^2.0.0"
  }
}
```

2. Setup project for Typescript
3. Open `deploy.ts` script

**Comment by 0xartcro** [comment] 2023-07-07 21:40
> Uhm, I cannot reproduce this. I generated the sample typescript project, opened the script with VSCode, and got no errors.
> 
> Can you share your `tsconfig.json` file?

```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  }
}
```

**Comment by clauBv23** [comment] 2023-07-09 18:17
The issue here is related to TypeChain, not Hardhat, the script runs without a problem, but the error is shown once the `hardhat.d.ts` file is autogenerated. 

This is due to the latest version of hardhat-ethers that TypeChain supports is v3.0.0 and in version [v3.0.1](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-ethers%403.0.1) transactions override where added updating the  `deployContract` function return type,
https://github.com/NomicFoundation/hardhat/commit/d8056fb8bc1116338f61974a8a44cd0defcb2555#diff-8d6cd3812336cbda37672c85460dd7086a6dd3fa1c6848ab12dce44fedd880e7
 

In the `hardhat.d.ts` file, changing the return type of the function will fix this issue. 
Only have to change `FactoryOptions` for `DeployContractOptions`.

This could work until TypeChain is updated.

**Comment by boldrack** [comment] 2023-07-09 18:28
@clauBv23 I'm using hardhat-ethers 3.0.0 and I'm facing the same issue now .

**Comment by clauBv23** [comment] 2023-07-09 19:58
@boldrack what version of hardhat and hardhat-toolbox are you using? 
And yes you are right when adding hardhat-ethers v3.0.0 to the project it works but you can check that the balance of the deployed contract is zero (it should be 0.001 ethers due to it being passed as value). 
So the problem remained the same, you are providing a param that the function is not expecting. 
That's why the sample project [was different before this change ](https://github.com/NomicFoundation/hardhat/commit/d8056fb8bc1116338f61974a8a44cd0defcb2555#diff-42eb8e46399a577a6f33ced97feb4a35f75da1b273cb2de86fbf2e8b19b32a46)

**Comment by boldrack** [comment] 2023-07-09 20:10
@clauBv23 I"m using hardhat 2.16.1 and hardhat-toolbox 3.0.0 

I think there's been a mixup in the usage of `DeployContractOptions`  and `FactoryOptions` 

`DeployContractOptions` is supposed to cater for that value param, correct me if i'm wrong.

**Comment by clauBv23** [comment] 2023-07-09 20:53
Yeap, it looks like `DeployContractOptions` was created to extend  `FactoryOptions` and support transaction overrides (in this case `value`) as mentioned in [v3.0.1](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-ethers%403.0.1) release 
https://github.com/NomicFoundation/hardhat/blob/f92e3233acc3180686e99b3c1b31a0e469f2ff1a/packages/hardhat-ethers/src/types/index.ts#L15

**Comment by DainisGorbunovs** [comment] 2023-07-16 05:46
I've added a fix to `@typechain/ethers-v6`, which should solve this issue.
It's in code review -  https://github.com/dethcrypto/TypeChain/pull/852

**Comment by fvictorio** [comment] 2023-07-17 10:37
Thanks a lot everyone for the info, I will look into this again

**Comment by clauBv23** [comment] 2023-07-18 11:29
I just tried with the latest version of [@typechain/hardhat@8.0.2](https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fhardhat%408.0.2) and the typechain error has gone

**Comment by DainisGorbunovs** [comment] 2023-07-20 15:41
I can confirm this issue is now solved due to flexible patch versioning in [hardhat-toolbox](https://github.com/NomicFoundation/hardhat/tree/main/packages/hardhat-toolbox) package and absence of a lock file. The actual [fix](https://github.com/dethcrypto/TypeChain/commit/c2b3f1b6e0a8f4535a3757dc7d877ef76ec2dd62) is in `typechain@8.3.0` and `@typechain/ethers-v6@0.4.1+`.

Users with already existing projects will need to run `npm update typechain @typechain/ethers-v6`, or if using pnpm `pnpm up typechain @typechain/ethers-v6`.

Here are the package versions currently used when creating a TypeScript project:

<details>
<summary>Versions</summary>

- `npm install --save-dev hardhat`
   - `"hardhat": "^2.17.0"` (`2.17.0` in `package-lock.json`)
- `npx hardhat`
   - `"@nomicfoundation/hardhat-toolbox": "^3.0.0"` (`3.0.0` in `package-lock.json`), with these peer dependencies:
      - `"typechain": "^8.2.0"`
      - `"@typechain/ethers-v6": "^0.4.0"`
      - `"@typechain/hardhat": "^8.0.0"`
   - `"@typechain/hardhat" is `8.0.2` with these peer dependencies:
      - `"@typechain/ethers-v6": "^0.4.2"` with this peer dependency:
         - `"typechain": "^8.3.0"`, which in my case is 8.3.0.
</details>

**Comment by 0xartcro** [comment] 2023-07-21 20:42
> Ah interesting. @0xartcro can you check if that fixes the issue for you?

It does, thanks

**Comment by fvictorio** [comment] 2023-08-01 13:12
Thanks. In that case I think I will close this issue. I didn't re-read the whole conversation so let me know if I'm missing something and I'll re-open.

**Closed by fvictorio** 2023-08-01 13:12 UTC
Labels: status:needs-more-info
