### ISSUE TITLE
Call by golang reverts unknown reason using hardhat-deploy in local env

### ISSUE THREAD

**Issue by Aliceonly** [NomicFoundation/hardhat#4682] opened 2023-12-14 13:28 UTC
### Version of Hardhat

2.19.1

### What happened?

I'm using "hardhat-deploy": "^0.11.44" and "@nomicfoundation/hardhat-toolbox-viem": "^2.0.0" libs
which are recommanded by hardhat official templates (with viem)
it automatically run deploy scripts when I run command "yarn hardhat node --hostname 0.0.0.0"
but calls to local hardhat network in golang seems reverted with no reason
It leads to hard to debug in local env
but it can call in online chains

hardhat-deploy": "^0.11.44
@nomicfoundation/hardhat-toolbox-viem
"viem": "^1.19.11"
"hardhat": "^2.19.1"
go-ethereum

Plz advise me some paths to debug with golang in local env using viem and hardhat-deploy
Check hardhat-deploy to fully support for Viem which recommands by hardhat official

### Minimal reproduction steps

1. running 'yarn hardhat node --hostname 0.0.0.0' , it deploy contracts before local accounts shows up and didn't cost (may be the problem)
2. generate go files with abis :
    solc --abi contracts/${name} --include-path node_modules --base-path . -o goBuild/${fileName} --overwrite
    abigen --abi=goBuild/${fileName}/${fileName}.abi --pkg=${fileName} --out goBuild/${fileName}/${fileName}.go 

3. using generated abi in go to call methods but reverted with no reason (func sig error)
but it can successfully call in online chain but failed in hardhat node

**Comment by fvictorio** [comment] 2023-12-27 10:57
@Aliceonly any chance this is a duplicate of https://github.com/NomicFoundation/hardhat/issues/4648?

**Comment by fvictorio** [comment] 2023-12-28 13:57
Thanks, yes, this is a duplicate of #4648.

**Closed by fvictorio** 2023-12-28 13:57 UTC
Labels: status:needs-more-info
