### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5364] opened 2024-06-10 13:46 UTC
Add telemetry to `v-next`:

* Add a permission flow on first run
* Document Sentry and Google analytics approach and implement a frame to allow us to execute on it

We expect both sentry and GA will send requests from a detached sub-process.

**Comment by alcuadrado** [comment] 2024-06-11 20:25
Duplicate of #5239

**Closed by alcuadrado** 2024-06-11 20:25 UTC
Labels: status:ready, v-next
