### ISSUE TITLE
error when using es modules [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by cruzdanilo** [NomicFoundation/hardhat#957] opened 2020-10-26 17:07 UTC
considering the function name `importCsjOrEsModule`, i suppose it should work with es modules

```log
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxx/hardhat.config.js
require() of ES modules is not supported.
require() of xxx/hardhat.config.js from xxx/node_modules/hardhat/internal/core/config/config-loading.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename hardhat.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from xxx/package.json.

    at new NodeError (node:internal/errors:258:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1100:13)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at importCsjOrEsModule (xxx/node_modules/hardhat/src/internal/core/config/config-loading.ts:18:20)
    at Object.loadConfigAndTasks (xxx/node_modules/hardhat/src/internal/core/config/config-loading.ts:61:18)
    at main (xxx/node_modules/hardhat/src/internal/cli/cli.ts:116:20) {
  code: 'ERR_REQUIRE_ESM'
}

hardhat@2.0.1
node@15.0.1
```

**Comment by cruzdanilo** [comment] 2020-10-26 17:39
i tried renaming the config file to `hardhat.config.cjs` and using `--config hardhat.config.cjs`, but i got a similar error from mocha ([which supports esm](https://mochajs.org/#nodejs-native-esm-support))
```log
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxx/test/contract.test.js
require() of ES modules is not supported.
require() of xxx/test/contract.test.js from xxx/node_modules/mocha/lib/mocha.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename contract.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from xxx/package.json.

    at new NodeError (node:internal/errors:258:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1100:13)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at xxx/node_modules/mocha/lib/mocha.js:349:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (xxx/node_modules/mocha/lib/mocha.js:346:14)
    at Mocha.run (xxx/node_modules/mocha/lib/mocha.js:1006:10) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by alcuadrado** [comment] 2020-10-26 17:49
@cruzdanilo can you provide instructions about how to reproduce this?

**Comment by cruzdanilo** [comment] 2020-10-26 17:55
just add `"type": "module"` to `package.json`. the error will pop even with an empty `hardhat.config.js`.

**Comment by numismatic4** [comment] 2021-05-10 00:39
I have the same problem. How did Uniswap solve this, they are using es6 modules

**Comment by David-Kneel** [comment] 2021-05-25 17:02
I am having this issue too. I have configured mocha to work with es6 imports and it is working mint. But I am having a hard time in converting [this project](https://github.com/TachyonicFinance/faster-than-light/tree/mocking) to hardhat. When I do so and issue command `hardhat test`, the result is:

```zsh
❯ npx hardhat test
Compiling 17 files with 0.8.0
Compilation finished successfully
An unexpected error occurred:

/home/david/Workspaces/Tachyonic/faster-than-light/test/YieldFarming.spec.js:1
import { MockProvider } from '@ethereum-waffle/provider'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/david/Workspaces/Tachyonic/faster-than-light/node_modules/mocha/lib/mocha.js:349:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/david/Workspaces/Tachyonic/faster-than-light/node_modules/mocha/lib/mocha.js:346:14)
```

It looks `hardhat`'s internal mocha is not picking up `.mocharc.js` switches as defined below:

```js
module.exports = {
    timeout: 20000,
    require: ["esm"],
    recursive: true,
    exit: true
}
```

**Comment by alcuadrado** [comment] 2021-05-25 17:16
`.mocharc.js` is not used when running the hardhat cli. You can try `node --require esm node_modules/.bin/hardhat`, or running mocha directly.

**Comment by David-Kneel** [comment] 2021-05-25 17:36
> `.mocharc.js` is not used when running the hardhat cli. You can try `node --require esm node_modules/.bin/hardhat`, or running mocha directly.

It is now working as it should. I followed your suggestion and added `"test": "node --require esm node_modules/.bin/hardhat test",` to package.json. Now `yarn test` runs successfully:

```zsh
yarn run v1.22.10
$ solhint 'contracts/**/*.sol'

Done in 2.73s.
yarn run v1.22.10
$ eslint .
Done in 0.86s.
yarn run v1.22.10
$ node --require esm node_modules/.bin/hardhat test


  YieldFarming
    ✓ Ownership (3050ms)


  1 passing (3s)
```

**Comment by nhasanli** [comment] 2021-09-09 15:25
I'm having a similar problem..

I'm using typescript and my package.json has "type": "module".

I try compiling with `npx hardhat compile` and get an error back when node tries to require(filePath) at `"/node_modules/hardhat/src/internal/core/config/config-loading.ts:23:20)"`

```
function importCsjOrEsModule(filePath: string): any {
  const imported = require(filePath);
  return imported.default !== undefined ? imported.default : imported;
}
```

Full error trace

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/nhh/Documents/GitHub/video-marketplace/hardhat.config.ts
require() of ES modules is not supported.
require() of /Users/nhh/Documents/GitHub/video-marketplace/hardhat.config.ts from /Users/nhh/Documents/GitHub/video-marketplace/node_modules/hardhat/internal/core/config/config-loading.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/nhh/Documents/GitHub/video-marketplace/package.json.

    at createErrRequireEsm (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:97:15)
    at assertScriptCanLoadAsCJSImpl (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:30:11)
    at Object.require.extensions.<computed> [as .ts] (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/ts-node/src/index.ts:1302:5)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at importCsjOrEsModule (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/hardhat/src/internal/core/config/config-loading.ts:23:20)
    at Object.loadConfigAndTasks (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/hardhat/src/internal/core/config/config-loading.ts:66:18)
    at main (/Users/nhh/Documents/GitHub/video-marketplace/node_modules/hardhat/src/internal/cli/cli.ts:126:20) {
  code: 'ERR_REQUIRE_ESM'
}

```

My hardhat.config.ts in same folder as package.json and tsconfig.json

```
import dotenv from "dotenv";
dotenv.config();
import "@nomiclabs/hardhat-etherscan";
import "@nomiclabs/hardhat-waffle";
import "hardhat-gas-reporter";
import "solidity-coverage";
import { task } from "hardhat/config";
import { HardhatUserConfig } from "hardhat/types";

task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(await account.address);
  }
});

const config: HardhatUserConfig = {
  solidity: "0.8.4",
  networks: {
    hardhat: {
      initialBaseFeePerGas: 0, 
    },
    ropsten: {
      url: `https://ropsten.infura.io/v3/${process.env.INFURA_PROJECT_ID}`,
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : undefined,
    },
    rinkeby: {
      url: `https://rinkeby.infura.io/v3/${process.env.INFURA_PROJECT_ID}`,
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : undefined,
    },
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: "USD",
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};

export default config;

```

**Comment by fvictorio** [comment] 2021-09-10 13:05
> I'm using typescript and my package.json has "type": "module".

AFAIK we don't support that yet. @alcuadrado can you confirm?

**Comment by Olyno** [comment] 2021-09-19 00:06
I tried to use hardhat for the first time, and got this issue when using it with ``"type": "module"``

**Comment by aspiers** [comment] 2021-11-07 19:11
I've run into this too.  It's pretty confusing, given that `import` works fine in `hardhat.config.ts`, and frustrating given how long ES modules have been around, but I'm certainly not complaining as we're all victims of the total mess which is the chaotic evolution of the JS ecosystem.

`yarn add esm` and `node --require esm node_modules/.bin/hardhat test` seem to do the trick for me too, although this seems pretty ugly.  Thanks to all for sharing your suggestions!

**Comment by aspiers** [comment] 2021-11-07 22:35
I seem to have found another workaround, but I have to say that I don't really understand why it works!

- `yarn add esm` as before
- add `require = require("esm")(module, { sourceMap: true });` to the top of `hardhat.config.ts` (I got the idea from [the `esm` README](https://github.com/standard-things/esm#getting-started)

The *really* weird thing is that if I remove the `sourceMap` option, it causes a ton of Typescript errors; but if I change the option to `false`, it still works?!

**Comment by aspiers** [comment] 2021-11-07 23:02
Sorry for the noise, false alarm - the above doesn't work.  Will delete.

**Comment by alcuadrado** [comment] 2021-11-07 23:38
Another alternative is just to use ts with a very permissive config. `"strict": false` should probably be enough.

**Comment by aspiers** [comment] 2021-11-08 03:32
`"strict": false` doesn't have any effect here :-(

**Comment by alcuadrado** [comment] 2021-11-08 18:27
Are you using .ts as an extension?

**Comment by aspiers** [comment] 2021-11-09 00:09
Yes.

**Comment by alcuadrado** [comment] 2021-11-10 10:12
There goes my theory :( I guess using `esm` is the less intrusive option then.

**Comment by Olyno** [comment] 2021-11-10 13:02
I still got the problem on my side using ``esm``, that's why i came here report the issue

**Comment by ddnexus** [comment] 2022-05-25 00:28
After so long, is it still not a priority? Typescript 4.7 is out and updating your typescript syntax to use `import` instead of `require` doesn't seem a lot of work. Am I missing something?

**Comment by aspiers** [comment] 2022-05-25 08:26
I'm also concerned that this is marked as `priority:low`.  From what I've seen, the majority of the EVM space moved to TypeScript and ESM a long time ago, so Hardhat is in danger of getting left behind in this respect.

**Comment by fvictorio** [comment] 2022-08-15 20:46
Hi everyone. We are working on having some initial support for ES Modules that doesn't require a new major version of Hardhat. The way this will work is that the config and anything required from it (plugins, files defining modules, etc.) will have to be in CJS, but you'll be able to use ESM for scripts and tests.

The main issue tracking this effort is #3043.

**Comment by Sceat** [comment] 2022-08-16 12:10
Heavily following this, `commonJs` is a fossil of the past and should never be used. Web3 is leading the future so i would suggest to mark this issue as **priority:high**

**Comment by fvictorio** [comment] 2022-09-23 11:27
Hi everyone. We just released a version of Hardaht under the `esm` npm tag which includes basic support for ESM.

The way this works is that your Hardhat config still needs to be CommonJS, and so it has to be named `hardhat.config.cjs` (or `.cts`, if your project is in typescript). But your scripts and tests can be ESM now, or you can mix CJS and ESM for both tests and scripts.

Please give it a try (`npm i hardhat@esm`, or equivalent yarn command) and let us know if you find any issues!

**Comment by brozorec** [comment] 2022-09-26 07:55
> Hi everyone. We just released a version of Hardaht under the `esm` npm tag which includes basic support for ESM.
> 
> The way this works is that your Hardhat config still needs to be CommonJS, and so it has to be named `hardhat.config.cjs` (or `.cts`, if your project is in typescript). But your scripts and tests can be ESM now, or you can mix CJS and ESM for both tests and scripts.
> 
> Please give it a try (`npm i hardhat@esm`, or equivalent yarn command) and let us know if you find any issues!

hey this is awesome :+1:  I'm about to try it out and changed `hardhat.config.ts` to `hardhat.config.cts` but it doesn't seem to detect the config. It promts this when I run `hardhat test`:
![image](https://user-images.githubusercontent.com/9572072/192223098-07614be9-6fc2-408b-9d28-a370acc0d190.png)

**Comment by Sceat** [comment] 2022-09-26 16:42
with `hardhat.config.cjs` i can confirm that it works nicely

**Comment by brozorec** [comment] 2022-09-26 16:52
Yes, it works with `.cjs` but not with `.cts`

**Comment by fvictorio** [comment] 2022-09-27 09:28
> I'm about to try it out and changed `hardhat.config.ts` to `hardhat.config.cts` but it doesn't seem to detect the config. It promts this when I run `hardhat test`:

@brozorec sorrry about that! I published a new version that should fix that issue. `npm i hardhat@esm` should upgrade it to that version.

**Comment by fvictorio** [comment] 2022-09-27 10:00
Well, to be honest, typescript+esm support is not quite there yet. I can't get scripts to run properly, and tests have to be `.cts` to work (which kind of defeats the purpose?) I'll let you know folks here when that's working reasonably well.

**Comment by Sceat** [comment] 2022-09-28 15:26
actually what is the point of using esm if you use typescript, you already have access to the syntax

**Comment by fvictorio** [comment] 2022-09-28 17:36
@Sceat it's necessary if you want to use a package that is published as ESM. And since Sindre did that for most of his bazillion npm packages, some people are migrating to be able to use them.

**Comment by Olyno** [comment] 2022-09-28 22:17
I agree with @Sceat. A typescript library has the opportunity to be compiled in both CJS and ESM. Many developers have already done this, and it's clearly not the most complicated thing.

The big problem is the Hardhat base code, which is not favorable to this conversion. Many syntaxes are exclusive to CJS, especially the ``require`` used in functions to import modules dynamically.

I have already started to solve several problems with Hardhat in one of my projects, [Solidhat](https://github.com/Olyno/solidhat), but it only concerns the CLI for the moment.

**Comment by mihaic195** [comment] 2022-10-04 15:01
I'm getting the same thing on a nextjs project. Hardhat config is written in typescript, tests as well.

I'm trying to import the hardhat runtime environment to perform programmatic verification of the smart contracts, but once imported into a nextjs api endpoint, it fails with the above error.

Changing the hardhat config to js fixes the error and everything works fine, but then my tests will not be picked up since they're written in ts and moving them to js is not an option.

`hardhat@esm` had exactly the same result for me.

**Comment by fvictorio** [comment] 2022-10-06 15:19
@mihaic195 yes, adding support for typescript + ESM will be hard, because there's not good support for that in `ts-node` yet :disappointed:

**Comment by DanielAtKrypton** [comment] 2022-10-12 09:54
> @mihaic195 yes, adding support for typescript + ESM will be hard, because there's not good support for that in `ts-node` yet 😞

It works, see: https://github.com/TachyonicFinance/faster-than-light

**Comment by mihaic195** [comment] 2022-10-12 10:08
@David-Kneel it works because you're not using typescript

**Comment by David-Kneel** [comment] 2022-10-12 10:49
@mihaic195, depending on your project requirements and timelines, it may make sense to transpile your typescript tests to js for the time being until hardhat provides full support to typescript + ESM, then switch back to typescript afterwards.

**Comment by cnohara** [comment] 2022-10-19 15:20
I've been using this hardhat esm branch for the past week and noticed the same behavior described here [https://github.com/NomicFoundation/hardhat/issues/957#issuecomment-1257640807](url) .

Basically, although hardhat is installed, at some point, it seems to reset and any command to it shows the initial project generator screen.  The only "fix" is to do the npm install of the esm branch again.  Anyone else encountering this?

**Comment by fvictorio** [comment] 2022-10-21 15:23
@cnohara does that happen after you install something?

**Comment by fvictorio** [comment] 2022-10-21 15:23
@cnohara does that happen after you install something?

**Comment by cnohara** [comment] 2022-10-22 02:16
@fvictorio I just tested and this definitely triggered hardhat to revert to its initial state.  Actually, this also occurred when just uninstalling a package as well.  I'm not sure if the install/uninstall are the only times this is triggered, but definitely true in my case.  Is this intended behavior or did I do something wrong on my side?

**Comment by fvictorio** [comment] 2022-10-28 12:31
@cnohara can you share the `hardhat` entry in your package.json's dependencies?

**Comment by slesolliec** [comment] 2022-10-31 10:37
1) installed hardhat@esm
2) changed my hardhad.config.js filename to hardhat.config.cjs
3) changed my ugly require() in my scripts to beautiful imports
4) fixed a few glitches which are not related to hardhat, but to small differences between commonJS and ESM

Tadam !!!! I works like a breeze.

And now I can use HH with the rest of my ESM codebase, which is a real pleasure because I work with SvelteKit.

Thank you A LOT to all those who contribute to hardhat@esm!!! Having to maintain two different kind of code base (my modern ESM one, and the old CJS) just because of HH, was a real pain, and was getting more and more painful by the day.

Thank you again for making my life easier and my work more productive.

PS: sorry for the TS people for whom it doesn't work as easily. IMHO TS is a waste of time and clutters your code too much. (no troll intended, just my personal opinion).

**Comment by fvictorio** [comment] 2022-11-16 11:33
@cnohara I t hink the problem is that npm 7+ has a new behavior when using peer dependencies that, while super useful most of the time, makes it a pain in the ass when using pre-releases. There isn't much we can do about that afaik.

**Comment by fvictorio** [comment] 2022-12-30 11:30
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3043 for bookkeeping reasons.

**Closed by fvictorio** 2022-12-30 11:30 UTC
