### ISSUE TITLE
verification on etherscan doesn't work for holesky

### ISSUE THREAD

**Issue by novaknole** [NomicFoundation/hardhat#5459] opened 2024-06-29 16:02 UTC
### Version of Hardhat

2.22.3

### What happened?

Hi.

I am trying to deploy on holesky testnet.

For the etherscan configuration via hardhat, I use the following:

```js
{
        network: 'holesky',
        chainId: 17000,
        urls: {
          apiURL: 'https://api-holesky.etherscan.io/api',
          browserURL: 'https://holesky.etherscan.io',
        },
}
```

It turns out contracts get verified successfully except one contract which is deployed inside another contract via `new` keyword. Etherscan verification results in:

> Reason: Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.

Does anyone know why ? Exact same thing successfuly gets verified on `sepolia`.  I even tried using etherscan manually, but same thing.

**Comment by kanej** [comment] 2024-07-08 10:58
Hey @novaknole, does the newed up contract take constructor arguments?

**Comment by kanej** [comment] 2024-07-22 14:36
I am closing as I suspect the issue is no longer relevant.

**Closed by kanej** 2024-07-22 14:36 UTC
Labels: status:needs-more-info
