### ISSUE TITLE
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by prathamesh2525** [NomicFoundation/hardhat#2405] opened 2022-02-20 15:31 UTC

**Comment by 3commascapital** [comment] 2022-03-01 17:23
```
     Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:135:10)
      at hash160 (node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
      at HDKey.set (node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
      at Function.HDKey.fromMasterSeed (node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
      at deriveKeyFromMnemonicAndPath (node_modules/hardhat/src/internal/util/keys-derivation.ts:21:27)
      at derivePrivateKeys (node_modules/hardhat/src/internal/core/providers/util.ts:29:52)
      at new HDWalletProvider (node_modules/hardhat/src/internal/core/providers/accounts.ts:312:42)
      at applyProviderWrappers (node_modules/hardhat/src/internal/core/providers/construction.ts:188:18)
      at createProvider (node_modules/hardhat/src/internal/core/providers/construction.ts:124:27)
      at /Users/michaelmclaughlin/Documents/pulsechain/ammbot/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:28
      at getRealTarget (node_modules/hardhat/src/internal/util/lazy.ts:96:22)
      at Object.get (node_modules/hardhat/src/internal/util/lazy.ts:169:26)
      at createProviderProxy (node_modules/@nomiclabs/hardhat-ethers/src/internal/provider-proxy.ts:25:19)
      at /Users/michaelmclaughlin/Documents/pulsechain/ammbot/node_modules/@nomiclabs/hardhat-ethers/src/internal/index.ts:33:27
      at getRealTarget (node_modules/hardhat/src/internal/util/lazy.ts:96:22)
```
i am also getting this error. here is my trace. only happens when i use node v17.5. works on lts (16.14)

**Comment by feuGeneA** [comment] 2022-03-09 16:06
Duplicate of #1988

**Closed by feuGeneA** 2022-03-09 16:06 UTC
