### ISSUE TITLE
Solidity stacktraces are wrong when using function modifiers

### ISSUE THREAD

**Issue by lukehutch** [NomicFoundation/hardhat#2755] opened 2022-05-24 21:40 UTC
Given this Solidity code, `MyContract.sol`:

```
contract MyContract {
    modifier ownerOnly() {
        require(msg.sender == _owner, "You are not the owner");
        _;            // Assume this is line 100
    }

    function myMethod external ownerOnly {
        require(false, "Can't call this method");
    }
}
```

Calling `MyContract.myMethod()` results in a stack trace that contains:

```
     Error: VM Exception while processing transaction: reverted with reason string 'Can't call this method'
      at MyContract.ownerOnly (contracts/main/MyContract.sol:100)
```

In other words the revert message `Can't call this method` is correct, but the location of the revert is wrong (both the method `ownerOnly` and the line number `100` is wrong).

**Comment by lukehutch** [comment] 2022-07-05 02:51
Hi, still an issue

**Comment by feuGeneA** [comment] 2022-07-11 16:49
Thank you for using Hardhat.

In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example

Can you provide us with a minimal reproducible example?

**Comment by vulntor** [comment] 2022-07-19 11:21
meet exact same issues with same code pattern

**Comment by fvictorio** [comment] 2022-10-03 13:19
Hmm, with this contract:

```solidity
contract Foo {
  address _owner;

  modifier ownerOnly() {
    require(msg.sender == _owner, "You are not the owner");
    _;            // Assume this is line 100
  }

  function f() external ownerOnly {
    require(false, "Can't call this method");
  }
}
```

I get a stack trace like this:

```
    at Foo.ownerOnly (contracts/Foo.sol:8)
    at Foo.f (contracts/Foo.sol:12)
```

Where line 8 corresponds to `require(msg.sender == _owner, "You are not the owner");` and line 12 to `function f() external ownerOnly {`, which seems correct?

I'm using solc 0.8.9 and the optimizer is disabled.

@lukehutch @vulntor maybe you have the optimizer enabled? In that case, the line numbers can be off.

**Comment by lukehutch** [comment] 2022-10-03 19:13
@fvictorio I should have specified, the test `msg.sender == _owner` should succeed (since in the original report, the error was "Can't call this method" not "You are not the owner"). To simplify the code:

```
contract Foo {
  address _owner;

  modifier ownerOnly() {
    // The following test is commented out
    // require(msg.sender == _owner, "You are not the owner");
    _;            // Assume this is line 100
  }

  function f() external ownerOnly {
    require(false, "Can't call this method");
  }
}
```

The error will be shown with the location `_;` ("line 100" as labeled).

Additionally, the calling context (one stack frame deeper) does not always show in the stack trace when there is a revert. Often only the top stack frame shows, or the caller stack frame does not show. Yes, that could be an optimizer issue.

**Comment by hiroshi-yamamoto-dublr** [comment] 2022-10-14 01:16
@fvictorio the problem is solved with the optimizer switched off.

Updated example:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

contract Test {
  bool private flag = true;
  
  modifier someModifier() {
    require(flag, "Failed in modifier");
    _;
  }

  function f() external someModifier {
    require(false, "Can't call this method");
  }
}
```

With optimizer switched on, stack trace has erroneous (superfluous) `someModifier` frame:

```
     Error: VM Exception while processing transaction: reverted with reason string 'Can't call this method'
      at Test.someModifier (contracts/Test.sol:8)
      at Test.f (contracts/Test.sol:12)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

With no code changes, but optimizer switched off:

```
     Error: VM Exception while processing transaction: reverted with reason string 'Can't call this method'
      at Test.f (contracts/Test.sol:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by fvictorio** [comment] 2022-10-18 10:02
Thanks. I'm going to close this one because, at the moment, it's super hard to give proper line numbers when the optimizer is disabled, given that solc gives way less information when the optimizer is enabled.

**Closed by fvictorio** 2022-10-18 10:02 UTC
