### ISSUE TITLE
ContractFactory deploy fails to estimate gas on solidity version: "0.8.20" with Shanghai as default

### ISSUE THREAD

**Issue by SvenMeyer** [NomicFoundation/hardhat#3977] opened 2023-06-02 13:56 UTC
### Version of Hardhat

2.12.2

### What happened?

ContractFactory deploy fails to estimate gas on solidity version: "0.8.20" with Shanghai as default

### Minimal reproduction steps

- create new project from @PaulRBerg template https://github.com/PaulRBerg/hardhat-template
- `pnpm install`
- `pnpm compile && pnpm clean && pnpm test` => OK
- in `hardhat.config.ts` change solidity compiler to   `solidity: {version: "0.8.20",`
- run again `pnpm compile && pnpm clean && pnpm test` => ERROR

```
  1) Unit tests
       Greeter
         "before each" hook for "should return the new greeting once it's changed":
     Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Transaction reverted and Hardhat couldn't infer the reason.", method="estimateGas", transaction={"from":"0xE12b5ca5Cf657184064dc2917933D008B6E6a168","data":"0x608060405234801562000010575f80fd5b506040516200097738038062000977833981016040819052620000339162000116565b620000586040518060600160405280602281526020016200095560229139826200006d565b5f62000065828262000255565b50506200037b565b620000ba82826040516024016200
```

### Search terms

deploy, ethers, Solidity, Shanghai, v0.8.20

**Comment by fvictorio** [comment] 2023-06-05 08:17
Thank you for the detailed instructions @SvenMeyer, I can confirm this.

**Comment by fvictorio** [comment] 2023-06-05 08:31
Ah, I see. The problem is that the template is using an older version of Hardhat, that doesn't have support for Shanghai (or at least doesn't have it enabled by default, I'm not sure).

You have two options here: either upgrade hardhat (`pnpm i --save-dev hardhat@latest`) or configure solidity to not emit bytecode for the shanghai hardfork. But I think the first option is what you want.

Closing this because I don't thinks there's much we can do on our side.

**Closed by fvictorio** 2023-06-05 08:31 UTC
Labels: type:bug, status:ready

**Comment by fvictorio** [comment] 2023-06-05 08:32
Btw, I feel like the proper solution here is to _not_ include the `pnpm-lock.yaml` in the template. @PaulRBerg would you be ok with doing that?

**Comment by SvenMeyer** [comment] 2023-06-05 10:13
@fvictorio Thanks, upgrading hardhat to @latest "^2.14.1" solved the problem ! :+1:

**Comment by PaulRBerg** [comment] 2023-06-08 10:22
> I feel like the proper solution here is to not include the pnpm-lock.yaml in the template. @PaulRBerg would you be ok with doing that?

No, I don't think so. I do want dependencies to be deterministic upon installing the template.

Why can't we simply bump `hardhat` to `latest` in the template? That would update `pnpm-lock.yaml`.

**Comment by fvictorio** [comment] 2023-06-08 10:43
That's fair! I just personally think that not including the lock file makes more sense for a template (we take that approach in hardhat sample projects, for example). It means less maintenance and that users always get the latest versions of the dependencies.

The only downside I see is that a dependency that doesn't follow semver can cause problems, but if that happens you can pin it in the package.json.

Of course, it's your template, you can do whatever you think is better 🙂

**Comment by PaulRBerg** [comment] 2023-06-08 11:03
> It means less maintenance and that users always get the latest versions of the dependencies.

Doesn't this go the other way, too? Users get the latest versions, which may contain (accidental) breaking changes.

Maintenance is inevitable, I guess.

> you can do whatever you think is better 

I'm thinking of simply bumping `hardhat`, and calling it a day.

**Comment by fvictorio** [comment] 2023-06-08 11:13
I was gonna suggest that you use dependabot in that case, but it seems like it's already enabled? I wonder why it doesn't open PRs for new versions of Hardhat.
