### ISSUE TITLE
[hardhat test]block.number become 0 after wrapped in a function

### ISSUE THREAD

**Issue by WarrenPanDDDD** [NomicFoundation/hardhat#3278] opened 2022-10-17 09:24 UTC
versions:
solidity 0.5.16;
hardhat 2.10.2

I have this sol code:
```
uint32 blockNumber = safe32(getBlockNumber(), "block number exceeds 32 bits");
console.log("blockNumber: ", blockNumber);
console.log("getBlockNumber(): ", getBlockNumber());
console.log("block.number: ", block.number);

function getBlockNumber() public view returns (uint) {
        return block.number;
}
```

When I run test, I get these logs:
`blockNumber:  0
  getBlockNumber():  0
  block.number:  23
`

As you can see, `block.number` is working in hardhat test. But after it is wrapped in `getBlockNumber() `, it become 0.

**Comment by fvictorio** [comment] 2022-10-18 10:20
I can't reproduce this:

```solidity
import "hardhat/console.sol";

contract Foo {
  function f() public {
    console.log("getBlockNumber(): ", getBlockNumber());
    console.log("block.number: ", block.number);
  }

  function getBlockNumber() public view returns (uint) {
    return block.number;
  }
}
```

**Comment by WarrenPanDDDD** [comment] 2022-10-18 11:44
alright, thanks for taking a look

**Comment by fvictorio** [comment] 2022-10-18 19:02
Tentatively closing this, but if you are still running into this problem and can give me precise reproduction steps, I will re-open it.

**Closed by fvictorio** 2022-10-18 19:02 UTC
