### ISSUE TITLE
npx hardhat run check: raise error, exit code stays 0 

### ISSUE THREAD

**Issue by codekoriko** [NomicFoundation/hardhat#5057] opened 2024-04-02 09:04 UTC
### Version of Hardhat

2.22.2

### What happened?

I'm using the [hardhat-solhint](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-solhint) plugin, when the litting process raise error, the exit code stays the 0, therefor command chaining with && don't break, which is a problem

### Minimal reproduction steps

Running the linter as mentioned in the doc: 
```shell
npx hardhat check && echo 'Error Code: '$? 
```

An error arise during the linting but _Exit Code_ stays 0
```shell
    8:1  error    Unexpected import of console file
             no-console
    8:1  warning  global import of path hardhat/console.sol is not allowed. Specify names to import individually or bind all exports of the module into a name (import "path" as Name)
             no-global-import
   31:5  warning  Explicitly mark visibility in function (Set ignoreConstructors to true if using solidity >=0.7.0)
             func-visibility
   56:9  warning  Use Custom Errors instead of require statements
             custom-errors
   74:9  warning  Use Custom Errors instead of require statements
             custom-errors
   76:9  warning  Use Custom Errors instead of require statements
             custom-errors
   94:9  warning  Use Custom Errors instead of require statements
             custom-errors
  114:9  warning  Use Custom Errors instead of require statements
             custom-errors

✖ 40 problems (1 error, 39 warnings)

Error Code: 0
```

**Comment by kanej** [comment] 2024-04-02 09:53
I was able to reproduce this locally, by taking a new typescript sample project, adding the solhint plugin, running `solhint --init` and updating the config to:

```json
{
  "extends": "solhint:recommended"
}
```

On running `npx hardhat check` we don't get a non-zero exit code:

![image](https://github.com/NomicFoundation/hardhat/assets/24030/4c51e713-a6b6-402b-86e3-b03a430eb057)

**Comment by madlabman** [comment] 2024-04-08 15:37
Because of this I think https://github.com/protofire/solhint/pull/554

**Comment by madlabman** [comment] 2024-04-09 13:10
Opened the issue https://github.com/protofire/solhint/issues/572

**Comment by kanej** [comment] 2024-04-10 14:44
Thanks @madlabman, we will keep this open to track the issue coming in on the `hardhat-solhint` plugin.

**Comment by AlissonRS** [comment] 2024-07-18 15:30
@kanej just a heads up this was fixed in Solhint 5.0.1 :rocket:

**Comment by kanej** [comment] 2024-07-26 14:28
Just note that upgrading to Solhint 5.0.1 would equate to a `major` version bump in the `hardhat-solhint` plugin.

**Closed** 2024-08-01 08:30 UTC
Labels: type:bug, status:blocked

**Comment by galargh** [comment] 2024-08-01 09:02
Thanks for the report! This issue has now been fixed in the release [@nomiclabs/hardhat-solhint@4.0.0](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-solhint%404.0.0)
