### ISSUE TITLE
"@nomicfoundation/hardhat-foundry" breaks coverage tests.

### ISSUE THREAD

**Issue by LucasGrasso** [NomicFoundation/hardhat#3961] opened 2023-05-29 21:50 UTC
### Version of Hardhat

2.14.0

### What happened?

I Don't know if this is a solidity-coverage or a hardhat-foundry issue, but after importing the latter, it just seems to break coverage tests.
With hardhat-foundry imported;
![image](https://github.com/NomicFoundation/hardhat/assets/66641667/8d014747-400f-49d1-9569-af51167dc482)
Without hardhat-foundry imported:
![image](https://github.com/NomicFoundation/hardhat/assets/66641667/303f3ee4-8652-45cf-93bb-7ca2a8a6baa1)

Tests in Foundry and in Hardhat were made for `DecentBatchDepositor.sol`. Sorry for the lack of a profound explanation, I just discovered it randomly and seems like a incompatibility bug. Thanks for your help.

### Minimal reproduction steps

* Install and import "@nomicfoundation/hardhat-foundry" in hardhat.config.ts
* Run coverage tests with `npx hardhat coverage`
* Unimport "@nomicfoundation/hardhat-foundry" in hardhat.config.ts
* Run coverage tests once again with `npx hardhat coverage`

### Search terms

foundry, coverage

**Comment by fvictorio** [comment] 2023-06-28 14:22
Hey @LucasGrasso, sorry for not responding sooner.

I can't reproduce this, at least in the simple Hardhat sample project.

Can you try again with the latest versions of the plugins and see if it's still happening?

And if it's still happening, could you create and share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by LucasGrasso** [comment] 2023-06-30 21:03
Hello @fvictorio , don't worry. As soon as I get some spare time I'll get to it.

**Comment by tariqkb** [comment] 2023-07-14 18:21
@fvictorio I am able to reproduce this issue with the following minimal steps

1. `hardhat init`
2. `npm install @nomicfoundation/hardhat-foundry`
3. Add `require("@nomicfoundation/hardhat-foundry")` to hardhat.config.js
4. `hardhat init-foundry` (coverage will work until after this step)
5. `hardhat coverage`

Produces this report:
<img width="674" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/664514/a90f0b59-fa73-49bf-83ae-484545c300ab">

**Comment by gatekeeper-app** [comment] 2024-02-20 04:23
Hi, I am getting the same issue, just wondering if there was any update. Thanks

**Comment by bingen** [comment] 2024-02-20 08:52
I’m getting the same error. It seems that the problem is `foundry.toml` file. If I remove it, it works again.

**Comment by miguelmtzinf** [comment] 2024-02-20 10:31
Same issue here

**Comment by partylikeits1983** [comment] 2024-02-21 11:18
Hello all, I had this same exact issue. Removing the foundry.toml file in the base of the repository fixed this issue. Code coverage is no longer 0%

**Comment by cgewecke** [comment] 2024-02-21 19:30
This should be fixed now in the latest solidity-coverage release: 
https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.8

Make sure you run the clean task after you update:
```
npm install --save-dev solidity-coverage@latest
npx hardhat clean
```

If there are further problems after installing the patch please report to [solidity-coverage issue 853][1]

[1]: https://github.com/sc-forks/solidity-coverage/issues/853

**Comment by miguelmtzinf** [comment] 2024-02-21 20:30
works on my end! @cgewecke goat :1st_place_medal:

**Comment by bingen** [comment] 2024-02-22 12:58
It works for me too, thanks!
I’m now having problems with skipping contracts. I think this was working before, so may it be related?

**Comment by kanej** [comment] 2024-04-03 11:23
I am going to close this, thanks @cgewecke

**Closed by kanej** 2024-04-03 11:23 UTC
Labels: type:bug, status:ready, area:hardhat-foundry
