### ISSUE TITLE
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by TOUSSAINT7** [NomicFoundation/hardhat#2765] opened 2022-05-26 23:56 UTC
C:\Users\TOUSSAINT\NFT-market>npx hardhat node
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces

C:\Users\TOUSSAINT\NFT-market>npx hardhat
Hardhat version 2.8.4

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config              A Hardhat config file.
  --emoji               Use emoji in messages.
  --help                Shows this message, or a task's help if its name is provided
  --max-memory          The maximum amount of memory that Hardhat can use.
  --network             The network to connect to.
  --show-stack-traces   Show stack traces.
  --tsconfig            A TypeScript config file.
  --verbose             Enables Hardhat verbose logging

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

C:\Users\TOUSSAINT\NFT-market>npx hardhat node
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces

**Comment by feuGeneA** [comment] 2022-05-27 16:20
Duplicate of #1988 . To be fixed in https://github.com/NomicFoundation/hardhat/pull/2705
For a short-term fix, consider downgrading Node.js to v16

**Closed by feuGeneA** 2022-05-27 16:20 UTC

**Comment by tonynoce** [comment] 2022-07-04 17:24
hi ! any updates on this ?
