### ISSUE TITLE
support for deno?

### ISSUE THREAD

**Issue by marsian83** [NomicFoundation/hardhat#5839] opened 2024-10-22 06:27 UTC
### Describe the feature

[Deno](https://deno.land/) is the next-gen version of nodejs, built specifically for TypeScript. Hardhat is a modern TypeScript project that could fit very well with deno.

Here are some tools that can help:

[Denoify](https://github.com/garronej/denoify) is a library that can aid in supporting deno with minimal changes to Hardhat's codebase
[dpx](https://github.com/denorg/dpx) is analogous to node's npx, could it be used to execute the cli?
Deno now support npm packages out of the box with "npm:hardhat" but somehow other nomicfoundation packages are being recognized but npm:hardhat fails to resolve.
Ethers.js is also a modern Typescript repo that's often paired with Hardhat -- for reference, here's the corresponding deno issue: https://github.com/ethers-io/ethers.js/issues/2009
Are there any plans to support this unresolved deno dep?

**Comment by kanej** [comment] 2024-11-22 11:32
Closing as a duplicate of #2888.

**Closed by kanej** 2024-11-22 11:32 UTC
Labels: status:triaging
