### ISSUE TITLE
Meet the `Failed to generate 1 stack trace`

### ISSUE THREAD

**Issue by Nipol** [NomicFoundation/hardhat#2151] opened 2021-12-13 04:30 UTC
I tested the case of reverted when I tried to using "create2" with the same salt. and in hardhat, stack trace generation failed.
That's why I'm reporting it.

```sh
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
    at isEvmStep (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/message-trace.ts:89:14)
    at ErrorInferrer._isConstructorInvalidArgumentsError (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:972:19)
    at ErrorInferrer.inferBeforeTracingCreateMessage (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:142:14)
    at SolidityTracer._getCreateMessageStackTrace (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:126:27)
    at SolidityTracer.getStackTrace (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:52:19)
    at SolidityTracer._rawTraceEvmExecution (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:201:38)
    at SolidityTracer._traceEvmExecution (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
    at SolidityTracer._rawTraceEvmExecution (/workspaces/library/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:201:38) +0ms
      ✓ should be revert deploy contract using create2 with delegatecall
```

The following code was called twice from one tx.

```solidity
pragma solidity ^0.8.0;

contract DeploySpell {
    function cast(
        uint256 value,
        bytes memory byteCode,
        bytes32 salt
    ) external returns (address deployed) {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            deployed := create2(value, add(byteCode, 0x20), mload(byteCode), salt)
            if iszero(extcodesize(deployed)) {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
        }
    }
}
```

If guys need more explanation of the situation, I will respond.

**Comment by 2dpetkov** [comment] 2022-06-08 22:03
Greetings, Team.

I am afraid the issue is still relevant.

The contract code is 

```
    function deploy(bytes memory initCode_, bytes32 salt_, bytes calldata initializer_)
        external onlyOwner payable
        returns (address payable deployedContractAddress)
    {
        uint256 msgValue = msg.value;
        assembly {
            deployedContractAddress := create2(msgValue, add(initCode_, 0x20), mload(initCode_), salt_)
        }
        require(deployedContractAddress != address(0), "target address occupied");
        if (initializer_.length != 0) {
            (bool success, ) = deployedContractAddress.call(initializer_);
            require(success, "initialization failed");
        }
    }
```


and the test that produces the warning:
```
    it("Should not deploy on the same address twice", async () => {
        const expectedRevertMessage = "target address occupied";

        await expect(factory.deploy(deployTx.data, SALT, [])).to.be.revertedWith(expectedRevertMessage);
    });
```

the warning:
```
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
    at isEvmStep (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/message-trace.ts:89:14)
    at ErrorInferrer._isConstructorInvalidArgumentsError (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:976:19)
    at ErrorInferrer.inferBeforeTracingCreateMessage (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:142:14)
    at SolidityTracer._getCreateMessageStackTrace (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:126:27)
    at SolidityTracer.getStackTrace (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:52:19)
    at SolidityTracer._rawTraceEvmExecution (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:201:38)
    at SolidityTracer._traceEvmExecution (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (<...>/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
    at HardhatNode._manageErrors (<...>/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1896:41) +0ms
    ✔ Should not deploy on the same address twice (45ms)
```

**Comment by fvictorio** [comment] 2022-12-28 16:37
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3482

**Closed by fvictorio** 2022-12-28 16:37 UTC
