### ISSUE TITLE
`ethers.getSigners()` returns an array containing only one signer

### ISSUE THREAD

**Issue by naftalimurgor** [NomicFoundation/hardhat#2735] opened 2022-05-19 04:24 UTC
## summary
`ethers` in hardhat provides same functionality with [ethers](https://docs.ethers.io/v5/single-page/#/v5/api/providers/provider/)  with added functionality such as:
```javascript
function getSigners() => Promise<ethers.Signer[]>;
```
## Desired effect
The desired effect is to have:
```javascript
// from hre
// some lines of  code ommitted for brevity
const accounts = await ethers.getSigners()
```
returning the 10 accounts as signers(wallets) with their addresses. Currently returns only one account as in the result:

## Result:
```javascript
[
  SignerWithAddress {
    _isSigner: true,
    address: '0xBCEeB54fa604FB357750E76229ADf98DfA90580f',
    _signer: JsonRpcSigner {
      _isSigner: true,
      provider: [EthersProviderWrapper],
      _address: '0xBCEeB54fa604FB357750E76229ADf98DfA90580f',
      _index: null
    },
    provider: EthersProviderWrapper {
      _isProvider: true,
      _events: [],
      _emitted: [Object],
      formatter: [Formatter],
      anyNetwork: false,
      _networkPromise: [Promise],
      _maxInternalBlockNumber: -1024,
      _lastBlockNumber: -2,
      _pollingInterval: 4000,
      _fastQueryDate: 0,
      connection: [Object],
      _nextId: 42,
      _hardhatProvider: BackwardsCompatibilityProviderAdapter {
        _wrapped: AutomaticGasPriceProvider {
          _wrapped: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _wrappedProvider: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          }
        },
        _provider: AutomaticGasPriceProvider {
          _wrapped: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _wrappedProvider: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          }
        },
        sendAsync: [Function: bound sendAsync],
        send: [Function: bound send],
        _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
      },
      _eventLoopCache: [Object]
    }
  }
]
```

**Comment by fvictorio** [comment] 2022-05-19 16:23
@naftalimurgor do you have reproduction steps? I tried `ethers.getSigners()` in a sample project and it worked as expected, returning all the available accounts.

**Comment by naftalimurgor** [comment] 2022-05-19 19:51
@fvictorio I'll get you a sample project with which this issue was first encountered

**Comment by mcintyre94** [comment] 2022-05-24 14:18
Not sure if this is the same cause, but I've just helped someone debug this issue. They had `defaultNetwork: "rinkeby",` in the hardhat config:

```
module.exports = {
  solidity: "0.8.4",
  defaultNetwork: "rinkeby",
  networks: {
    rinkeby: {
      url: `${process.env.NODE_API_URL}`,
      accounts: [`${process.env.RINKEBY_PRIVATE_KEY}`],
    },
  },
};
```

So I think hardhat was using the rinkeby network and then resolving `RINKEBY_PRIVATE_KEY` to a single signer, instead of running the local network that has multiple signers available

@naftalimurgor any chance you could have something similar going on?

**Comment by fvictorio** [comment] 2022-05-25 13:46
Thanks @mcintyre94, my guess is also that something like this is going on.

I'm going to tentatively close this issue, but I will re-open it if there are reproduction steps that confirm there's some bug.

**Closed by fvictorio** 2022-05-25 13:46 UTC

**Comment by Silver-IT** [comment] 2022-06-21 13:26
I met this error too.

**Comment by Silver-IT** [comment] 2022-06-21 13:26
```
import * as dotenv from "dotenv";

import { HardhatUserConfig, task } from "hardhat/config";
import "@nomiclabs/hardhat-ethers";
import "@nomiclabs/hardhat-etherscan";
import "@nomiclabs/hardhat-waffle";
import "@typechain/hardhat";
import "hardhat-gas-reporter";
import "solidity-coverage";

dotenv.config();

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 1000,
      },
    },
  },
  defaultNetwork: 'rinkeby',
  networks: {
    ropsten: {
      url: process.env.ROPSTEN_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
    rinkeby: {
      url: process.env.RINKEBY_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: "USD",
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
  mocha: {
    timeout: 150000
  }
};

export default config;

```

**Comment by naftalimurgor** [comment] 2022-06-21 14:50
@I did end up creating signers directly from their Private keys

**Comment by hanpanpan200** [comment] 2022-08-02 13:31
> 

Thanks!  @mcintyre94 It works for me! 

> Not sure if this is the same cause, but I've just helped someone debug this issue. They had `defaultNetwork: "rinkeby",` in the hardhat config:
> 
> ```
> module.exports = {
>   solidity: "0.8.4",
>   defaultNetwork: "rinkeby",
>   networks: {
>     rinkeby: {
>       url: `${process.env.NODE_API_URL}`,
>       accounts: [`${process.env.RINKEBY_PRIVATE_KEY}`],
>     },
>   },
> };
> ```
> 
> So I think hardhat was using the rinkeby network and then resolving `RINKEBY_PRIVATE_KEY` to a single signer, instead of running the local network that has multiple signers available
> 
> @naftalimurgor any chance you could have something similar going on?
