### ISSUE TITLE
Error creating an advanced sample project that uses TypeScript

### ISSUE THREAD

**Issue by SpencerMiller23** [NomicFoundation/hardhat#2314] opened 2022-01-29 19:55 UTC
I am trying to create a new Hardhat environment using the Advanced Typescript template. I am using Windows 11 64-bit with VS Code and Hardhat v2.8.3

Steps to reproduce:
1) `npm install --save-dev hardhat`
2) `npx hardhat`
3) Select "Create an advanced sample project that uses TypeScript
4) Select "y" for add .gitignore
5) Follow the prompt to run:
 `npm install --save-dev "hardhat@^2.8.3" "@nomiclabs/hardhat-waffle@^2.0.0" "ethereum-waffle@^3.0.0" "chai@^4.2.0" "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0" "@nomiclabs/hardhat-etherscan@^2.1.3" "dotenv@^10.0.0" "eslint@^7.29.0" "eslint-config-prettier@^8.3.0" "eslint-config-standard@^16.0.3" "eslint-plugin-import@^2.23.4" "eslint-plugin-node@^11.1.0" "eslint-plugin-prettier@^3.4.0" "eslint-plugin-promise@^5.1.0" "hardhat-gas-reporter@^1.0.4" "prettier@^2.3.2" "prettier-plugin-solidity@^1.0.0-beta.13" "solhint@^3.3.6" "solidity-coverage@^0.7.16" "@typechain/ethers-v5@^7.0.1" "@typechain/hardhat@^2.3.0" "@typescript-eslint/eslint-plugin@^4.29.1" "@typescript-eslint/parser@^4.29.1" "@types/chai@^4.2.21" "@types/node@^12.0.0" "@types/mocha@^9.0.0" "ts-node@^10.1.0" "typechain@^5.1.2" "typescript@^4.5.2"`

Error message:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: ethers@5.0.0
npm ERR! node_modules/ethers
npm ERR!   dev ethers@"5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer ethers@"^5.1.3" from @typechain/ethers-v5@7.0.1
npm ERR! node_modules/@typechain/ethers-v5
npm ERR!   dev @typechain/ethers-v5@"7.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\spenc\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\spenc\AppData\Local\npm-cache\_logs\2022-01-29T19_47_47_570Z-debug-0.log
```

**Comment by Palmatum** [comment] 2022-02-12 09:11
Hey @SpencerMiller23, try setting up everything in a new directory (like a clean install). If that still doesn't work, then try using the `--legacy-peer-deps` flag.

For example,

`npm install --save-dev --legacy-peer-deps "hardhat@^2.8.3" "@nomiclabs/hardhat-waffle@^2.0.0" "ethereum-waffle@^3.0.0" "chai@^4.2.0" "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0" "@nomiclabs/hardhat-etherscan@^2.1.3" "dotenv@^10.0.0" "eslint@^7.29.0" "eslint-config-prettier@^8.3.0" "eslint-config-standard@^16.0.3" "eslint-plugin-import@^2.23.4" "eslint-plugin-node@^11.1.0" "eslint-plugin-prettier@^3.4.0" "eslint-plugin-promise@^5.1.0" "hardhat-gas-reporter@^1.0.4" "prettier@^2.3.2" "prettier-plugin-solidity@^1.0.0-beta.13" "solhint@^3.3.6" "solidity-coverage@^0.7.16" "@typechain/ethers-v5@^7.0.1" "@typechain/hardhat@^2.3.0" "@typescript-eslint/eslint-plugin@^4.29.1" "@typescript-eslint/parser@^4.29.1" "@types/chai@^4.2.21" "@types/node@^12.0.0" "@types/mocha@^9.0.0" "ts-node@^10.1.0" "typechain@^5.1.2" "typescript@^4.5.2"`

**Comment by fvictorio** [comment] 2022-02-21 22:02
@SpencerMiller23 which version of `npm` are you using?

**Comment by YoKawaiiK** [comment] 2022-04-17 04:31
The same. Flags --force and --legacy-peer-deps flag also doesn't help to correct this situation.

Version npm: 8.6.0

**Comment by fvictorio** [comment] 2022-04-27 13:22
@YoKawaiiK are you on Windows?

**Comment by fvictorio** [comment] 2022-04-27 13:25
For the record: I cannot reproduce this on Linux using npm@8.6.0.

**Comment by fvictorio** [comment] 2022-05-17 22:52
Closing this for lack of more information. If someone has reproduction steps, please leave a comment and we'll re-open it.

**Closed by fvictorio** 2022-05-17 22:52 UTC

**Comment by Atheter** [comment] 2022-06-05 11:25
npm install --force solved it for me

**Comment by jemi2k** [comment] 2022-10-16 18:57
first delete the folder then create it again then use --force --legacy-peer-deps, it works!

**Comment by d0ra-1h3-3xpl0ra** [comment] 2022-12-23 21:39
`--force `worked for me on OSX and Ubuntu. Just make sure to delete package-lock.json and try again then.  👍 ⚡
