### ISSUE TITLE
[Error: EISDIR: illegal operation on a directory, read] when compiling with contracts/some_folder_name.sol

### ISSUE THREAD

**Issue by dasaveliev** [NomicFoundation/hardhat#1439] opened 2021-05-05 19:56 UTC
1. Put a folder with any name ending with .sol e.g. new_folder.sol into the contracts folder
2. Run hardhat compile
3. The error is thrown in the console:
`An unexpected error occurred:
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}`

**Comment by alcuadrado** [comment] 2021-05-05 22:28
Thanks for reporting this, @dasaveliev.

Would you mind telling us more about why you use the `.sol` extension in folders? Would you be ok if we forbid that we a clear error message?

**Comment by dasaveliev** [comment] 2021-05-06 00:09
It is convenient in my case to store a folder named after the contract with json inside containing both abi & bytecode.
I would personally prefer it to be handled correctly without trying to compile the folder )
But a clear error is the least acceptable option too

**Comment by alcuadrado** [comment] 2021-05-06 23:31
Do you store those inside `contracts/`?

**Comment by dasaveliev** [comment] 2021-05-06 23:44
> Do you store those inside `contracts/`?

Yes. They are contracts too, just not solidity files.
e.g. 
`contracts/ContractABIAndBytecode.sol/ContractABIAndBytecode.json`
with content 
{...
"abi": [...], 
"bytecode": ...
}

**Comment by fvictorio** [comment] 2021-05-18 17:29
@dasaveliev that looks very similar to what we generate in the `artifacts` directory. Is that the case and you are obtaining that from a compilation result, or is it just a coincidence?

**Comment by samgville** [comment] 2021-11-28 14:33
I'm experiencing the same error, has anyone found a workaround?

**Comment by fvictorio** [comment] 2021-11-29 11:34
> I'm experiencing the same error, has anyone found a workaround?

If it's the same error, the workaround for now is to rename your directory so that it doesn't end in `.sol`.

**Comment by Gilgames000** [comment] 2022-03-26 18:02
> If it's the same error, the workaround for now is to rename your directory so that it doesn't end in .sol.

I am facing the same problem and my directories in `contracts/` don't end with `.sol`

**Comment by si3mshady** [comment] 2022-04-04 20:51
Just started happening out of nowhere!

**Comment by fvictorio** [comment] 2022-04-12 17:45
@Gilgames000 @si3mshady do you have reproduction steps?

**Comment by avallois** [comment] 2022-05-06 00:44
I had the same problem, when I was importing a route that did not exist in my contract.

**Comment by fvictorio** [comment] 2022-05-06 17:00
@avallois can you help me reproduce the problem?

**Comment by avallois** [comment] 2022-05-07 01:14
Sure:

This is when importing `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";`

**Comment by fvictorio** [comment] 2022-05-18 14:09
Oh, I see, the problem was that you were importing a directory. Thanks, we should show a better error message in that case too.

**Comment by EdwardsVO** [comment] 2022-06-24 21:08
> Sure:
> 
> This is when importing `import "@openzeppelin/contracts/token/ERC721";` instead of `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";`

This work for me, thanks 😁

**Comment by Lasang3012** [comment] 2022-09-26 03:03
I have error like you! and i check import file of SMC 
![image](https://user-images.githubusercontent.com/96694773/192185687-1e3958fe-ea9d-454d-9305-4d9c038c101a.png)

resolve:
![image](https://user-images.githubusercontent.com/96694773/192185756-bccad09a-a9e2-4d2c-8345-5350a3e0092f.png)

**Comment by fvictorio** [comment] 2022-12-29 12:31
The original issue (compiling a project that has a directory ending in `.sol`) seems to be fixed in the latest version of Hardhat, so I'm going to close this.

I also opened https://github.com/NomicFoundation/hardhat/issues/3490 for the problem of accidentally trying to import a directory.

If someone has another kind of problem **and can provide minimal reproduction steps**, please open a new issue.

**Closed by fvictorio** 2022-12-29 12:31 UTC
Labels: type:bug, priority:low
