### ISSUE TITLE
HardHat network experiences unexplained reversions during iterations of pure/view functions

### ISSUE THREAD

**Issue by CodeForcer** [NomicFoundation/hardhat#1241] opened 2021-02-12 10:17 UTC
I've created a test repo to demonstrate the issue:
https://github.com/CodeForcer/curve-error-example-2

To run the test case just create `.env` file with a archive url variable `ARCHIVE_NODE_API=https://eth-mainnet.alchemyapi.io/etc...`, then run `yarn install` followed by `npx hardhat test`.

The test takes a while to run, but demonstrates the error by attempting to execute a pure/view function 200 times.

Given the function is pure/view, there should be no difference between each iteration, yet the iteration fails after 25 runs with a reversion on another contract.

**Comment by CodeForcer** [comment] 2021-02-12 11:23
Some further investigation which might help diagnose. I changed the code to make the call in a lower-level manner:
```
function test() public {
  console.log("Running stateless Curve function multiple times");

  for (uint256 i = 0; i < 200; i++) {
    curvePool.call(abi.encodeWithSignature(
      "get_dy_underlying(int128,int128,uint256)",
      int128(1),
      int128(2),
      1
    ));
    console.log("Successful iteration", i);
  }
}
```

Now the HardHat error is:
```
<...>
Successful iteration 22
Successful iteration 23
Successful iteration 24
Successful iteration 25
Successful iteration 26
    1) Replicates a confusing problem with Curve


  0 passing (7s)
  1 failing

  1) Test Curve Bug
       Replicates a confusing problem with Curve:
     Error: Transaction run out of gas
      at new TransactionExecutionError (node_modules/hardhat/src/internal/hardhat-network/provider/errors.ts:97:16)
      at HardhatNode._manageErrors (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:935:14)
      at HardhatNode.runTransactionInNewBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:312:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Failed to generate 1 stack trace. Run Hardhat with --verbose to learn more

**Comment by CodeForcer** [comment] 2021-02-15 14:31
Ok, I've discovered the cause here. The actual error is "out of gas", but is being suppressed in the first example. Raising block gas limit fixes the error.

**Comment by cameel** [comment] 2021-11-27 23:44
This seems to work as expected. Calling view and pure functions on chain (i.e. from a contract) is not free. You do not pay any gas only if a node simulates its execution for you without actually publishing that fact to the rest of the network. Depending on what the function does, executing it 25 times could very well use up all gas.

**Comment by fvictorio** [comment] 2022-12-29 19:21
Hmm, I'm going to close this because this is expected behavior. I am interested in the fact that the original reproduction didn't result in an OOG error, but the repo doesn't exist anymore.

@CodeForcer if you happen to still have that repo, I will open a new issue about this. But I would understand if you don't, it's been almost 2 years :sweat:

**Closed by fvictorio** 2022-12-29 19:21 UTC
