### ISSUE TITLE
Inconsistency between Hardhat EVM and Geth EVM.

### ISSUE THREAD

**Issue by hickscorp** [NomicFoundation/hardhat#2946] opened 2022-07-14 12:25 UTC
Consider the following code, as part of a smart contract method:

```solidity
...
uint256 balance = address(this).balance;
...
```

The code compiles, and runs fine within Hardhat node environments.
However it crashes in a Geth based chain with error such as:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0xE875158298ac8e112e7180707E3a9CF3F06f2F3f","data":"0x565974d3","accessList":null}, error={"name":"ProviderError","code":-32000,"_isProviderError":true}, code=CALL_EXCEPTION, version=providers/5.6.8)
```

The problem here is that code runs locally, passes tests, and would get deployed without the developer knowing that it would in fact crash in production.

We fixed the problem using `payable(address(this)).balance`.

I would suggest that Hardhat makes it so the crash also occurs locally on Hardhat-based EVMs.

**Comment by fvictorio** [comment] 2022-07-14 13:10
Tagging some folks from the ethereumjs team, since this looks like it could be an issue in the VM: @holgerd77 @jochem-brouwer

**Comment by jochem-brouwer** [comment] 2022-07-14 13:26
We would need the entire environment and the transaction data to reproduce this test. Could @hickscorp provide a minimal setup in hardhat and in Geth so that we can reproduce this divergence?

Why would this `payable` solve this problem? I am no solidity expert but AFAIK this solves static analysis compiler errors. It also makes no sense to me why you cannot load an account balance if a non-payable account.

**Comment by alcuadrado** [comment] 2022-07-14 14:19
Hey there 👋


My suspicion is that this is not a bug in Hardhat nor in ethereumjs, but rather a really hard-to-spot misconfiguration.

I believe you are using another chain that's running a pretty old hardfork, older than Istanbul. The reason I suspect this is that Istanbul introduced the `SELFBALANCE` opcode, and solidity >= 0.5.13 compiles `address(this).balance` to that opcode. 

By default, Hardhat Network runs using the same hardfork as mainnet, so `SELFBALANCE` exists and works correctly. But the same code on your chain, which doesn't have that opcode, reverts.

The `payable` keyword must be forcing it to use `BALANCE` instead.

Can you please tell us which chain are you using and your versions of Hardhat and Solidity? That'd be enough to confirm this theory.

If I'm correct, these are the things you need to do to fix this issue:

1. Set Hardhat network's hardfork to the one your chain is running.
2. Set the [evmVersion of solidity](https://docs.soliditylang.org/en/v0.8.15/using-the-compiler.html#setting-the-evm-version-to-target) to the same one.

If I'm not correct you'd be better following those steps anyway. @fvictorio should we create an "Using Hardhat with other chains" advanced guide explaining these things?

**Comment by fvictorio** [comment] 2022-07-15 08:15
> @fvictorio should we create an "Using Hardhat with other chains" advanced guide explaining these things?

Agree. I created a Linear issue for that.

I'm going to tentatively close this issue, but @hickscorp please let us know if you still think there's a problem in Hardhat.

**Closed by fvictorio** 2022-07-15 08:15 UTC

**Comment by hickscorp** [comment] 2022-07-15 09:33
Good morning and thanks a lot for your help @fvictorio @jochem-brouwer @alcuadrado .

It's going to be difficult for me to provide a reproducible example this week, but I could try next week.

FWIW, we operate on two private chains, but we are able to replicate locally using a POA Geth chain.
The settings for it are:

```> geth version
Geth
Version: 1.10.19-stable
Git Commit: 23bee16208718975f9b9e012949b8d4ee1223108
Architecture: amd64
Go Version: go1.18.1
Operating System: linux
GOPATH=
GOROOT=go
```

Our genesis looks like:

```json
{
  "config": {
    "chainId": 18021980,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "clique": {
      "period": 1,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5d1e25b1",
  "extraData": "...",
  "gasLimit": "0x59a5380",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {...},
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

In terms of Solidity compiler versions, most (if not all) of our contracts fence with `pragma solidity ^0.8.4;`

**Comment by hickscorp** [comment] 2022-07-15 12:50
@alcuadrado Same problem.

**Comment by hickscorp** [comment] 2022-07-15 12:55
In case you want to try - this is how I start the local geth chain to try and replicate what happens on our private chains:

```bash
#!/bin/bash -e
trap cleanup EXIT
DATADIR="./geth-local-poa-chain"

function cleanup {
  # Delete any previous data dir.
  echo "Cleaning up..."
  rm -rf "$DATADIR/geth/"
}

# Clean up, in case something wasn't deleted from last run.
cleanup

# Initialize data dir from Genesis.
geth init \
  --datadir "$DATADIR" \
  "${DATADIR}/genesis.json"

# Run geth in dev mode (poa, sealing enabled).
geth --dev \
  --ipcdisable \
  --datadir "$DATADIR" \
  --miner.etherbase "..........." \
  --http \
  --http.addr "0.0.0.0" \
  --http.port 8546 \
  --http.api "eth,web3,net" \
  --http.corsdomain "*"
```

Note that the `etherbase` is set to an address that is in the `keystore/` folder, so that the extradata specifying which sealer can append on the canonical chain is unlocked and runs.

**Comment by hickscorp** [comment] 2022-07-19 10:04
@alcuadrado I'm not sure I understand. We run a private chain - we can't touch our genesis - can we?

**Comment by fvictorio** [comment] 2022-07-20 09:33
Either that or configure Hardhat to match the hardfork that is being used by your chain. That might not be possible in some scenarios if, for example, you are doing something like "using hardfork X but without the EIP Y that is included in that fork".
