### ISSUE TITLE
build-info improvements for verifying on sourcify

### ISSUE THREAD

**Issue by sirpy** [NomicFoundation/hardhat#2696] opened 2022-05-12 05:38 UTC
I have a large project and when compiling it , it creates several json files in build-info one of them is very large 7MB.
This file size is not supported by sourcify.
Another issue is that it should also be possible to verify on sourcify just using the metadata, where the sources are specified as ipfs links, but it seems that they are not actually uploaded to ipfs.

The suggested solutions are
1. have the build-info split into several smaller files
2. a way to upload sources to ipfs

**Comment by fvictorio** [comment] 2022-06-07 19:57
Hi @sirpy. I think the problem is that the build info files also include things like the `ast`, which contribute a lot to their size. The problem is that configuring hardhat to _not_ include the ast in the output is not straightforward (to be honest, I don't even know how to do it); I opened #2803 to investigate and document this. For the time being, removing all the `ast` entries programmatically might work for you, but I realize it's far from ideal.

> have the build-info split into several smaller files

Sadly, this would be hard to do without significant changes to our compilation pipeline.

> a way to upload sources to ipfs

That seems like a feature for the deployment solution, so it's unlikely we'll add it to the core of hardhat.

I'm going to close this issue now since I don't think there's much we can do (except for the documentation part I mentioned) but please let me know if you disagree.

**Closed by fvictorio** 2022-06-07 19:57 UTC
