### ISSUE TITLE
cmd/flatten: should only emit one "SPDX-License-Identifier"

### ISSUE THREAD

**Issue by Dentrax** [NomicFoundation/hardhat#2408] opened 2022-02-22 07:50 UTC
If you try to _flatten_ your contract by issuing the following command:
```bash
$ npx hardhat flatten contract.sol > output.sol
```

`flatten` command emits multiple `SPDX-License-Identifier` header and you eventually ended-up on error if you try to verify your contract on _etherscan_:

Most of them comes from `@openzeppelin` imports.

```
ParserError: Multiple SPDX license identifiers found in source file. Use "AND" or "OR" to combine multiple licenses. Please see https://spdx.org for more information.
--> myc
```

**Comment by fvictorio** [comment] 2022-02-22 14:50
Duplicate of #1499.

**Closed by fvictorio** 2022-02-22 14:50 UTC
