### ISSUE TITLE
Forking goerli-optimism after Bedrock fails

### ISSUE THREAD

**Issue by leomassazza** [NomicFoundation/hardhat#3590] opened 2023-01-17 23:02 UTC
### Version of Hardhat

2.12.6

### What happened?

When attempting to fork goerli optimism after Optimism bedrock upgrade fails. 

### Minimal reproduction steps

- Create a new hardhat project
- Attempt to fork optimism-hardhat 
`npx hardhat node --fork https://opt-goerli.g.alchemy.com/v2/<ALCHEMY KEY>`
  or 
`npx hardhat node --fork https://optimism-goerli.infura.io/v3/<INFURA KEY>`
It will fail with `Invalid value null supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/0: RpcTransaction/gasPrice: QUANTITY`

Note: I used the same providers with `ganache-cli` and the fork works

### Search terms

bedrock fork

**Comment by fvictorio** [comment] 2023-01-19 09:20
Thank you @leomassazza, I can confirm this is happening.

The underlying reason seems to be that the transaction objects returned by the node don't include some fields (`gasPrice`, `r`, `s`, `v`). I think this has to do with optimism's [deposited transaction types](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md#the-deposited-transaction-type).

Possible fixes here:
- Just accept transactions without those values
- Fetch the forking block _without_ expanding the transactions. This is something we should do anyway, because expanding them is unnecessarily wasteful.

The second option is less risky and maybe easier, but there will still be issues if you fetch a deposit transaction, or if you fetch a block with expanded transactions.

**Comment by sashaaldrick** [comment] 2023-01-26 15:33
I can confirm this is happening as well for me, when it worked fine in December before bedrock upgrade.

**Comment by panukettu** [comment] 2023-02-19 15:03
looking forward to get this fixed. ganache works btw

**Comment by sebastianst** [comment] 2023-03-07 14:23
This got fixed in `op-geth` two weeks ago with https://github.com/ethereum-optimism/op-geth/pull/48 so recent Optimism geth nodes will provide `0` values for the sig fields and gas price.

But correct, for Deposited transactions (`"type": "0x7e"`) you can also just ignore these fields.

**Comment by 0xmichalis** [comment] 2024-11-26 15:02
We have started seeing this occur on Base Sepolia, is it worth to open a separate ticket?

**Comment by schaable** [comment] 2024-12-03 16:49
This issue is resolved and no longer occurring. Closing.

**Closed by schaable** 2024-12-03 16:49 UTC
Labels: type:bug, status:ready
