### ISSUE TITLE
Hardhat instance from a config file and be able to have multiple instances

### ISSUE THREAD

**Issue by seromenho** [NomicFoundation/hardhat#3281] opened 2022-10-18 11:01 UTC
Is there already some way to have multiple hardhat instances with different configurations?
If there is please 🙏 let me know and you can ignore what's next...

I think it could be beneficial if we could create a hardhat instance from a specific config file.
Some advantages I can see:
1. There are some plugins that are incompatible with each other, so you could have an instance with some plugins loaded and another one with some other plugins
2. You can have different settings for different chains you use hardhat for
3. Maybe we can also remove the `You are not inside a Hardhat project` error and don't limit the usage of hardhat to a folder where you will find a config file. This could open door to one for example creating a package from hardhat to be used in a project. You would import that package into the project.

Sample code:
```ts
import hardhat from 'hardhat'

export const ethHre = hardhat({ configPath: './eth/hardhat.config.ts' })
export const hederaHre = hardhat({ configPath: './hedera/hardhat.config.ts' })
```

Does this make sense to you?

**Comment by fvictorio** [comment] 2022-10-20 08:21
I'm going to close this one as a duplicate of #3042. If someone feels strongly that this is a different issue, please let me know.

**Closed by fvictorio** 2022-10-20 08:21 UTC

**Comment by seromenho** [comment] 2022-10-20 08:48
Hi @fvictorio thank you. It seems to me that #3042 addresses this.
