### ISSUE TITLE
ChainId assembly code not deterministic with hardhat forking feature

### ISSUE THREAD

**Issue by josojo** [NomicFoundation/hardhat#2325] opened 2022-02-02 21:00 UTC
I found that the chainId return from the following solidity assembly code:
```
assembly {
            id := chainid()
        }
```
is not deterministic, if the "forking" mode is used in hardhat. 
See the following  [Minimal Reproducible Example](https://github.com/josojo/hardhat-issue-example).
Please see the README of the linked repo for a detailed report. I hope that I can contribute to hardhat with this bug report, because hardhat is great.

**Comment by alcuadrado** [comment] 2022-02-03 13:54
Hey @josojo, 

Thanks for opening this issue and creating a reproduction repo. It was really helpful!

I can confirm that this is a bug in Hardhat Network. We are running `eth_call`s using the remote network's `chainId`, independently of the block number, which is incorrect.

The error is in these lines of code:

https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L2232-L2233

The expected behavior is:

* Use the config's `chainId` for every tx
* Use the remote `chainId` for `eth_call`s with block numbers equal or less than the block you forked from.
* Use the config's `chainId` for `eth_call`s with block numbers greater than the block you forked from.

**Comment by josojo** [comment] 2022-05-14 11:25
I think its still relevant. We would love to build simulations for the gnosis safe and there it is relevant

**Comment by kasperpawlowski** [comment] 2022-05-24 20:24
It seems that this issue has been resolved in the latest release - 2.9.6

**Comment by alcuadrado** [comment] 2022-05-24 21:21
That's right, @kasperpawlowski. Can you try with 2.9.6, @josojo?

**Comment by kasperpawlowski** [comment] 2022-05-24 21:35
As I have your attention here @alcuadrado, could you look at issue # that I just created? It's related to this one.

**Comment by alcuadrado** [comment] 2022-05-24 21:45
Yes, it is related to this one. I'll take a look at it tomorrow. I believe we have different expectations of what should happen in that case. If you could explain yours, or better yet, create a reproduction repository/script, that would be extremely useuful.

**Comment by kasperpawlowski** [comment] 2022-05-24 23:05
Yes, I created reproduction repository and proposed a bug fix. I believe that this time it's pure oversight. The logic was written in a way that when `_forkBlockNumber` is undefined, `_forkNetworkId` is returned as `chainId` which shouln't be the case I guess.

**Comment by rodrigoherrerai** [comment] 2022-05-28 16:20
Hello. Related to this issue, I have a very annoying problem. 

When running normal tests (no mainnet-forking), the result of "block.chainid" is 0.

I have been trying to debug this for a while, but I have no clue what the issue is.

**Comment by rodrigoherrerai** [comment] 2022-05-28 16:31
Here is simple reproduction of the error: https://github.com/rodrigoherrerai/hardhat-chainid/tree/master

**Comment by kasperpawlowski** [comment] 2022-05-28 16:32
@rodrigoherrerai check that out and let me know if your observations are the same. You can also try the solution I proposed
#2753

**Comment by rodrigoherrerai** [comment] 2022-05-28 16:40
@kasperpawlowski Hi ! By the solution, do you mean the pr to Hardhat directly ? Or you had a workaround this issue  for your tests ?

**Comment by rodrigoherrerai** [comment] 2022-05-28 16:51
So I tried an older version and it worked. I don't know the exact version that broke this, but the latest version def doesn't work. It is broken for mainnet-forking and for hardhat-network testing.

**Comment by rodrigoherrerai** [comment] 2022-05-28 16:54
It was actually the latest version  the one that caused this error. Version 2.9.5 works fine.

**Comment by kasperpawlowski** [comment] 2022-05-28 17:12
@rodrigoherrerai I haven't created a PR yet as I wanted to discuss it under the issue I created. Check out this:
https://github.com/NomicFoundation/hardhat/compare/master...kasperpawlowski:fix-chainId?expand=1

is seems that it's enough to update the `packages/hardhat-core/src/internal/hardhat-network/provider/node.ts` as showed in the commit above

**Comment by fvictorio** [comment] 2022-12-28 11:49
I confirm this is still happening in the latest version of Hardhat.

Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3481 for bookkeeping reasons.

**Closed by fvictorio** 2022-12-28 11:49 UTC
