### ISSUE TITLE
TransactionExecutionError: Headers Timeout Error

### ISSUE THREAD

**Issue by Pzixel** [NomicFoundation/hardhat#2672] opened 2022-05-06 06:03 UTC
## Bug Description

When running long tests on harhat network all transactions start failing and then it stalls. 

## Reproducible By

This snippet should do the trick:

```ts
for (let j = 0; j < 1000000; j++) {
    const amountIn = '1000';
    const [signer1] = await ethers.getSigners();
    const swapRouter = ISwapRouter__factory.connect('0xE592427A0AEce92De3Edee1F18E0157C05861564', signer1);
    const recipient = signer1.address;
    await waitEthersTx(swapRouter.exactInput({
        // WETH -> USDC 3000 fee
        path: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2000bb8A0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        amountIn: amountIn,
        deadline: constants.MaxUint256,
        recipient,
        amountOutMinimum: 1,
    }, {
        value: amountIn,
    }));
}
```

## Expected Behavior

It should be working without issues

## Logs & Screenshots

Transaction fails with

```ts
TransactionExecutionError: Headers Timeout Error
    at HardhatNode.mineBlock (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:478:15)
    at async EthModule._sendTransactionAndReturnHash (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)
    at async HardhatNetworkProvider.request (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at async EthersProviderWrapper.send (/Users/pzixel/Documents/Repos/test/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

    Caused by: HeadersTimeoutError: Headers Timeout Error
        at Timeout.onParserTimeout [as _onTimeout] (/Users/pzixel/Documents/Repos/test/node_modules/undici/lib/client.js:1005:28)
        at listOnTimeout (node:internal/timers:561:11)
        at processTimers (node:internal/timers:502:7)
```

## Environment

Node 16.5.0, Macos 12.3.1 M1 Pro (but I'm pretty sure it's doesn't matter)

Hardhat config if relevant:

```ts
const networks: NetworksUserConfig = {
    hardhat: {
        forking: {
            url: myurl,
        },
        chainId: 1,
    },
};
```

**Comment by feuGeneA** [comment] 2022-05-13 19:16
Thank you for using Hardhat. Can you provide a more complete reproduction scenario? Perhaps in a separate repo or in an attachment? Something I can easily just run. Thanks.

**Comment by therawk** [comment] 2022-05-21 10:36
I'm struggling with this, too. I call a function on a smart contract which takes a while to finish and get this error:

```
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/dev/collab/node_modules/undici/lib/client.js:1005:28)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```
What exactly is causing this Timeout Error? I'm using mainnet fork via Alchemy. Is this timeout caused by Alchemy, Hardhat or the undici lib?

**Comment by Pzixel** [comment] 2022-05-21 11:20
I've got it no two different endpoints (non-alchemy ones) so this must be a hardhat issue

**Comment by inspiraluna** [comment] 2022-05-23 07:41
I only got it on a hardhat local node when I was forking from a Polygon mainnet via a public node. There might be a timeout when getting the data from the live node. If I repeat the command a couple of times it disappears. Obviously when all data are downloaded the the local node eventually.

**Comment by feuGeneA** [comment] 2022-05-23 19:53
I'm closing this because it sounds like Hardhat is behaving as expected.

This error message is simply the result of a network timeout, and the mere presence of this message does not indicate a problem with Hardhat, and GitHub Issues are intended to be used exclusively for problems in Hardhat itself.

There are many reasons why such a timeout may occur, including a problem on the endpoint (eg public node). It could also be the case that the computation you're requesting the node to execute may simply be a longer-running computation than the timeout values that have been configured at various points in the networking stack (both on the client and on the server).

If anyone suspects a problem that actually lies within Hardhat, please feel free to re-open this Issue, and, ideally, provide a minimal, reproducible example.

**Comment by 3commascapital** [comment] 2022-05-25 02:26
i am also seeing this when forking an ethereum node

**Comment by bretep** [comment] 2022-05-25 19:27
I'm also seeing it forking an ethereum archive node of mainnet. :/

**Comment by bretep** [comment] 2022-05-25 19:31
I've taken a pcap, 100% of the RPC calls were responded to. There was one call that looks like it took 1 second to respond.

Here is each request and latency of the request.
![hardhat-network-for-test-run](https://user-images.githubusercontent.com/787344/170352524-f24b1284-f641-4bf3-99e9-14deba68fcf8.png)

**Comment by bretep** [comment] 2022-05-25 19:34
I'm not seeing any timeouts on the wire, or from the server.

**Comment by therawk** [comment] 2022-05-25 20:21
Would you be interested in a repo I'm having this issue with?

**Comment by feuGeneA** [comment] 2022-05-25 20:28
@bretep thank you for this. I've re-opened the issue. Clearly this isn't necessarily an issue connecting to the remote node. In particular, the presence of `HardhatNode.mineBlock()` in the call stack, which I hadn't noticed before your confirmation here.

Are you able to configure Wireshark to also capture loopback traffic? (I know that is easier on some systems than others.) That would capture this activity, if I'm understanding the scenario correctly.

Also, can you confirm that you have the same symptoms as in the original Issue description? In particular, I'm interested in hearing whether `HardhatNode.mineBlock()` appears in your call stack.

Finally, would you happen to have a reproducible scenario for this? Even with all these wonderful clues, without a reproduction it will be difficult to even diagnose this, much less get it fixed.

Thanks again!

**Comment by bretep** [comment] 2022-05-25 21:13
> @bretep thank you for this. I've re-opened the issue. Clearly this isn't necessarily an issue connecting to the remote node. In particular, the presence of `HardhatNode.mineBlock()` in the call stack, which I hadn't noticed before your confirmation here, points a finger at Hardhat.
> 
> 
> 
> Are you able to configure Wireshark to also capture loopback traffic? (I know that is easier on some systems than others.) That would capture this activity, if I'm understanding the scenario correctly.
> 
> 
> 
> Also, can you confirm that you have the same symptoms as in the original Issue description? In particular, I'm interested in hearing whether `HardhatNode.mineBlock()` appears in your call stack.
> 
> 
> 
> Finally, would you happen to have a reproducible scenario for this? Even with all these wonderful clues, without a reproduction it will be difficult to even diagnose this, much less get it fixed.
> 
> 
> 
> Thanks again!

Yes, I can. I'll do that once I get back to my computer. It's going to be a few hours.

**Comment by bretep** [comment] 2022-05-26 03:18
Hi, I've captured the loopback device. I didn't see anything that took more than 0.5ms. 

I'll see what I can do about a reproducible scenario.

![hardhat-network-for-test-run-lo](https://user-images.githubusercontent.com/787344/170408673-c340d9ae-14dc-4ef7-be20-75b0a0827d85.png)

<img width="912" alt="Screen Shot 2022-05-25 at 20 14 24" src="https://user-images.githubusercontent.com/787344/170408698-55b05049-253f-4eeb-b4b5-598758de7e31.png">

**Comment by bretep** [comment] 2022-05-26 03:25
hardhat v2.9.6
Specifically getting the following error:

```
     HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as _onTimeout] (node_modules/undici/lib/client.js:1005:28)
      at listOnTimeout (node:internal/timers:561:11)
      at processTimers (node:internal/timers:502:7)

```

**Comment by 3commascapital** [comment] 2022-05-26 05:56
to lend some credence to the mined block thread while i work on a minimum viable, these are some of the errors that i see when i do not see the same error, but it seems very similar: takes a long time to do anything
```
Mined block #14361014
  Block: 0xd6005a46c9070513722990be5765c6f465178475e91be0e69c2b7c2ecbd50886
    Base fee: 0
    Transaction:           0xf5ba928fb13b3a7f0e5472d16497fd45914832e51d439f4701c006586dcd987e
      Contract call:       Swap#uniswapV3ExactInputSingle
      From:                0xf42b8cf17ad3bbc0a203b2d2b5e7be373650f456
      To:                  0x9d634360c39aa1b9a75b013a66a137bb390924d5
      Value:               0 ETH
      Gas used:            9692216 of 10000000

      Error: Transaction reverted without a reason string
          at <UnrecognizedContract>.<unknown> (0xc2e9f25be6257c210d7adf0d4cd6e3e881ba25f8)
          at <UnrecognizedContract>.<unknown> (0xe592427a0aece92de3edee1f18e0157c05861564)
          at Swap.uniswapV3ExactInputSingle (contracts/Swap.sol:208)
          at async HardhatNode._mineBlockWithPendingTxs (.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
          at async HardhatNode.mineBlock (.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
          at async HardhatModule._intervalMineAction (.../node_modules/hardhat/src/internal/hardhat-network/provider/modules/hardhat.ts:175:20)
          at async HardhatNetworkProvider._sendWithLogging (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
          at async HardhatNetworkProvider.request (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
          at async MiningTimer._mineFunction (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:325:9)
          at async MiningTimer._loop (.../node_modules/hardhat/src/internal/hardhat-network/provider/MiningTimer.ts:98:5)
```
this is a simple uniswapv3 swap, which should only cost <50k gas, but for whatever reason, it ends up costing near the hard coded gas limit provided by the client. this gas usage varies wildly but is almost always > 1m

when i try to inspect the transaction using hardhat-tracer, i get this error
https://github.com/zemse/hardhat-tracer/issues/16

**Comment by feuGeneA** [comment] 2022-05-27 16:53
This Issue has been added to the team's backlog. Thanks @3commascapital for your help on this repro!

**Comment by 3commascapital** [comment] 2022-05-30 13:56
also, just some extra information, it looks like, both the hardhat fork as well as the polling side get "stuck", as in when one is polling for a transaction hash, the requests return just fine the first couple of rounds, but often on the 3rd check (on a ~1s poll interval and a 3s block time) the response for `eth_getTransactionReceipt` freezes as well - is there an internal db that is locking transaction receipts there which could offer a clue?

**Comment by 3commascapital** [comment] 2022-06-22 19:03
not sure if it's the same issue, but i also got this error recently
```
hardhat_intervalMine

Unexpected error calling hardhat_intervalMine: TransactionExecutionError: the tx doesn't have the correct nonce. account has nonce of: 31 tx has nonce of: 27 (vm hf=arrowGlacier -> block number=14361621 hash=0x5f9b8d32f78e2086dacb20d46304b4454311de11312a92a108a977bdcf0df80a hf=arrowGlacier baseFeePerGas=0 txs=0 uncles=0 -> tx type=0 hash=0x8c9b94664842afe482f39bff752c65bcbfc8faf3ad75572d36bd2238af5ab374 nonce=27 value=0 signed=true hf=arrowGlacier gasPrice=1000000000)
```
found it kind of odd that the nonce was having difficulties given that the system that is testing this / where this is happening is fairly solid

**Comment by samlaf** [comment] 2022-06-27 14:14
I would really like to see this issue resolved.
So far it seems like it's a stochastic error to me... sometimes it happens, sometimes it doesn't (with the same exact code).
Not sure if it depends on network latency, or some other random parameters... been trying things out for 3 hours and can't put my finger on it.

**Comment by aquib20034** [comment] 2022-07-07 13:10
I also managed this issue using the following configuration.

module.exports = {
   solidity: "0.8.4",
   defaultNetwork: "kovan",
   networks: {
      hardhat: {},
      kovan: {
         url: API_URL,
         accounts: [`0x${PRIVATE_KEY}`]
      }
   },
   **mocha: {
    timeout: 400000000
  },**
   etherscan: {
    apiKey: ETHERSCAN_API_KEY
  }
}

**Comment by 3commascapital** [comment] 2022-08-06 13:38
Still relevant

**Comment by sunwrobert** [comment] 2022-08-16 07:03
+1, still would like to get this solved

**Comment by feuGeneA** [comment] 2022-08-16 23:12
On our internal backlog, I've bumped this up to the highest priority, so that if nothing else it will be discussed by the team. I can't make any promises about whether it'll stay at that priority, much less about when we might add it to our schedule, but once we've discussed it and made such some decision then I'll report back here.

**Comment by lut1k** [comment] 2022-08-19 15:55
+1, still would like to get this solved

**Comment by alcuadrado** [comment] 2022-09-05 17:22
If anyone wants to tackle this, take a look at https://github.com/NomicFoundation/hardhat/issues/3136

**Comment by ivanvolov** [comment] 2022-09-16 18:45
+1 same here

**Comment by SeungWookHan** [comment] 2022-10-15 11:16
I'm struggling with this, too.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/22572874/195983615-279c2b41-1ff9-417a-a90c-0e7a77939a91.png">

**Comment by GoofyMoose** [comment] 2022-11-03 12:22
I had the same issue (Headers Timeout Error) and it disappeared after I turned off my firewall.

**Comment by fvictorio** [comment] 2022-12-28 09:31
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3136.

**Closed by fvictorio** 2022-12-28 09:31 UTC
