### ISSUE TITLE
Missing class properties transform.

### ISSUE THREAD

**Issue by tony123S** [NomicFoundation/hardhat#3598] opened 2023-01-20 07:31 UTC
### Version of Hardhat

2.12.4

### What happened?

```
C:/Users/nick_/VSCodeProjects/nft-school-examples/end-to-end/node_modules/hardhat/node_modules/undici/lib/fetch/headers.js
SyntaxError: C:\Users\nick_\VSCodeProjects\nft-school-examples\end-to-end\node_modules\hardhat\node_modules\undici\lib\fetch\headers.js: Missing class properties transform.
  67 | class HeadersList {
  68 |   /** @type {[string, string][]|null} */
> 69 |   cookies = null
     |   ^^^^^^^^^^^^^^
  70 |
  71 |   constructor (init) {
  72 |     if (init instanceof HeadersList) {
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
```

Keep getting this annoying error after I run `C:\Users\nick_\VSCodeProjects\nft-school-examples\end-to-end> yarn add -D hardhat -W` and add this line in my `LazyMinter.js` file.

`import { ethers } from "hardhat";`

### Minimal reproduction steps

1.Clone this project from here https://github.com/tony123S/nft-school-examples
2. cd to end-to-end
3. in command, run `yarn start`

**Comment by fvictorio** [comment] 2023-01-20 09:38
Which version of node are you using? You can run `node --version` to get it.

**Comment by tony123S** [comment] 2023-01-20 10:08
> Which version of node are you using? You can run `node --version` to get it.

v18.13.0

**Comment by fvictorio** [comment] 2023-01-20 13:55
In that case I'll need reproduction steps, I can't investigate this just with this information.

**Comment by tony123S** [comment] 2023-01-20 18:21
@fvictorio I have edit my post..please have a look. Thanks a lot.

**Comment by tony123S** [comment] 2023-01-21 10:10
What could be the issue?

**Comment by fvictorio** [comment] 2023-01-24 22:59
Hey @tony123S, some comments about this.

First a clarification: Hardhat is not meant to be used in the browser. It relies on a lot of node.js specific things that simply won't work, even if you bundle it.

That being said, in your particular example the import from hardhat seems to be unnecessary. If you remove [this line](https://github.com/tony123S/nft-school-examples/blob/4a1b9b2f55d20f4c1f70e5cc9d792537c112f1a0/end-to-end/packages/react-app/src/helpers/LazyMinter.js#L1), then `yarn start` works fine.

I'm going to close this now because there isn't much to do on our side.

**Closed by fvictorio** 2023-01-24 22:59 UTC
Labels: status:needs-more-info
