### ISSUE TITLE
hardhat-verify found one or more errors during the verification process:  Etherscan: ReadableStream is not defined

### ISSUE THREAD

**Issue by cykk** [NomicFoundation/hardhat#5194] opened 2024-05-10 06:08 UTC
When executing the following command：
`npx hardhat verify --network Sepolia 0x64f632b88513918915a95f96fb2a83dd259a8e60`

The following error message appears：

hardhat-verify found one or more errors during the verification process:
Etherscan:
ReadableStream is not defined`

What is the reason for this？

**Comment by schaable** [comment] 2024-05-13 13:53
Hi @cykk, thanks for submitting the issue. Can you provide more information? A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be really useful here.

**Comment by schaable** [comment] 2024-05-27 14:39
Hi @cykk, I'm closing this for bookkeeping reasons, but I'll be happy to reopen it if this issue persists and you can provide more information. Thanks!

**Closed by schaable** 2024-05-27 14:39 UTC
Labels: status:needs-more-info

**Comment by njelich** [comment] 2024-08-07 09:06
For reference, this seems to be due to an outdated Node version. I tested this by changing node versions and running hardhat verify and noticed it fails on e.g. Node 16 but passes on Node 20.
