### ISSUE TITLE
InvalidInputError: sender doesnt have enough funds to send tx on  hardhat network

### ISSUE THREAD

**Issue by viraj124** [NomicFoundation/hardhat#2593] opened 2022-04-11 15:27 UTC
Hi,

I am on Mac OS with node version `v12.6.0`, I have tried hardhat versions `2.9.3, 2.9.2, 2.9.1` with all versions I get this error,  I have 4 unit test files, out of 4 one of my unit test files when executed gives this error after running a few tests, my hardhat config is 
`
    hardhat: {
      accounts: {
        mnemonic,
      },
      forking: {
        enabled: process.env.FORKING === "true",
        url: process.env.RPC
      },
      chainId: chainIds.hardhat,
      gas: 2100000
    }
    `
    What is the right workaround? , I tried setting a low gas limit but still, the issue persists.

**Comment by alcuadrado** [comment] 2022-04-18 13:13
This is a duplicate of https://github.com/NomicFoundation/hardhat/issues/2159.

The workaround is to use `gas: "auto"`

**Closed by alcuadrado** 2022-04-18 13:13 UTC
