### ISSUE TITLE
Tests for the `parallel` option in `hardhat-core` do not pass without `yarn build`

### ISSUE THREAD

**Issue by cameel** [NomicFoundation/hardhat#2486] opened 2022-03-14 14:26 UTC
In #1969 I was told that the tests in `hardhat-core` are supposed to work even without running `yarn build`. This is no longer the case now that extra tests for the `parallel` option were added.

I noticed this when our tests in solc-js started failing ([4387](https://app.circleci.com/pipelines/github/ethereum/solc-js/1085/workflows/f11eccff-0bb3-4057-98dd-90df8163ae88/jobs/4387)). The test forcibly injects the latest solc-js into dependencies but I managed to reproduce it also with Hardhat's own dependency.

### How to reproduce
Run these commands in the shell:
```bash
git clone --depth 1 https://github.com/nomiclabs/hardhat.git
cd hardhat
yarn

cd packages/hardhat-core/
npx mocha --recursive test/builtin-tasks/test.ts
```
Test output:
```
  test task
    default config project
      ✔ should run tests (2188ms)
    failing tests
      ✔ should have a return code equal to the number of failing tests (66ms)
    parallel tests
      with the default config
        ✔ should fail in serial mode (58ms)
        1) should pass in parallel mode
      when the config has parallel: true
        2) use parallel by default
      when the config has parallel: false
        ✔ use serial by default (56ms)
        3) should be overridable
    bail
      with the default config
        ✔ should have two failures if all tests are run (60ms)
        ✔ should stop at the first failure if --bail is used (58ms)
      when the config has bail: true
        ✔ use bail by default (55ms)
      when the config has bail: false
        ✔ don't bail by default (63ms)
        ✔ should be overridable (57ms)


  9 passing (11s)
  3 failing

  1) test task
       parallel tests
         with the default config
           should pass in parallel mode:

      AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0

      at Context.<anonymous> (test/builtin-tasks/test.ts:56:16)

  2) test task
       parallel tests
         when the config has parallel: true
           use parallel by default:

      AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0

      at Context.<anonymous> (test/builtin-tasks/test.ts:69:16)

  3) test task
       parallel tests
         when the config has parallel: false
           should be overridable:

      AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0

      at Context.<anonymous> (test/builtin-tasks/test.ts:92:16)
```
Adding `yarn build` after `yarn` makes tests pass.

**Comment by feuGeneA** [comment] 2022-03-14 16:10
I've reproduced this problem locally. @fvictorio I see you wrote those tests; would you mind taking a look?

**Comment by fvictorio** [comment] 2022-03-14 16:54
Will do. Thanks for reporting this, @cameel.

**Comment by cameel** [comment] 2022-04-28 09:31
Still relevant.

**Comment by fvictorio** [comment] 2022-04-28 12:58
Sorry for not working on this yet @cameel, we'll try to prioritize this.

**Comment by cameel** [comment] 2022-04-28 13:11
No worries. In the grand scheme of things this is not affecting us that much. I just added `yarn build` and it works, just adding a bit more build time in CI. I think it must actually be bothering you more :)

**Comment by cameel** [comment] 2022-05-28 14:31
> If you think it's still relevant, please leave a comment indicating so.

Not urgent at all but still relevant I guess :)

**Comment by fvictorio** [comment] 2022-12-28 10:33
I looked a bit into this but I don't think there's an easy way to fix it. And since we already have a pre-requisite of building Hardhat to run the plugins tests, I don't think it's that bad to have the same requirement for the core tests too.

I think I'm going to close this now. Hope you don't mind, @cameel! Let me know if this turns out to be a big issue for you and I'll give it another try.

**Closed by fvictorio** 2022-12-28 10:33 UTC
