### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by aliveli186** [NomicFoundation/hardhat#2491] opened 2022-03-14 22:58 UTC
Using hardhat v2.9.1 still receiving "JavaScript heap out of memory" after local fork node being active for few hours.
Why is memory leaking, something stays in memory forever?

Related issue: https://github.com/NomicFoundation/hardhat/issues/2380

```
Mined empty block range #14397128 to #14397130
eth_feeHistory (24)
Mined empty block range #14397131 to #14397133
eth_feeHistory (24)
eth_blockNumber
eth_gasPrice
Mined empty block range #14397134 to #14397136
eth_blockNumber
eth_getBlockByNumber
eth_feeHistory (6)
eth_getBalance
eth_getBlockByNumber

<--- Last few GCs --->

[15296:000001CD5B11CC10] 40879168 ms: Mark-sweep (reduce) 2045.1 (2083.3) -> 2044.2 (2083.6) MB, 1409.7 / 0.1 ms  (average mu = 0.183, current mu = 0.124) allocation failure scavenge might not succeed
[15296:000001CD5B11CC10] 40880894 ms: Mark-sweep (reduce) 2045.3 (2083.6) -> 2043.0 (2083.4) MB, 1386.7 / 0.1 ms  (average mu = 0.190, current mu = 0.196) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6AF277B7F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF6AF204546 DSA_meth_get_flags+65542
 3: 00007FF6AF2053FD node::OnFatalError+301
 4: 00007FF6AFB3B29E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6AFB2587D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6AF9C8C4C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF6AF9D58F9 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF6AF9D28CA v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF6AF9C5529 v8::internal::Heap::CollectGarbage+2137
10: 00007FF6AF9C36E0 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF6AF9E8266 v8::internal::Factory::NewFillerObject+214
12: 00007FF6AF71A735 v8::internal::DateCache::Weekday+1797
13: 00007FF6AFBC8F91 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 000001CD5CFF2E83
```

**Comment by alcuadrado** [comment] 2022-03-14 23:26
Hey, thanks for reporting this issue. Can you provide steps to reproduce it?

**Comment by aliveli186** [comment] 2022-03-15 18:58
> Hey, thanks for reporting this issue. Can you provide steps to reproduce it?

Start a forked node, create an app which will make periodical requests to some contracts in that node and eventually you'll receive this error.

**Comment by alcuadrado** [comment] 2022-03-15 21:59
Are you using Metamask?

**Comment by aliveli186** [comment] 2022-03-16 10:03
> Are you using Metamask?

Yes.

**Comment by alcuadrado** [comment] 2022-03-16 15:47
Yes, I'm just asking for info to be able to reproduce it.

**Comment by aliveli186** [comment] 2022-03-17 10:17
My app is calling some contract methods periodically and when the node stays few hours up it breaks eventually. 
Maybe there is some memory DB like structure which grows indefinitely and crashes. You know better.

**Comment by aliveli186** [comment] 2022-04-30 12:38
No progress?
Could it be related with web server part?
Is there any limit on how many requests a node can handle?

**Comment by sunwrobert** [comment] 2022-05-24 06:47
Also experiencing flakiness running hardhat nodes specifically during e2e tests that tack on load on Hardhat

**Comment by julianmrodri** [comment] 2022-06-16 10:52
Experiencing this exact issue when calling `hardhat_reset` on my  mainnet fork tests in Github Actions (CI). Completely brings down the node with every reset.

**Comment by alcuadrado** [comment] 2022-06-16 11:13
I'm closing this issue, as its description indicates that this was due to `eth_feeHistory`. Please open a new issue for different OOM erros.

**Closed by alcuadrado** 2022-06-16 11:13 UTC
