### ISSUE TITLE
Solidity 0.8.10 breaks the "Transaction reverted: function call to a non-contract account"-heuristic

### ISSUE THREAD

**Issue by chriseth** [NomicFoundation/hardhat#2051] opened 2021-11-09 18:06 UTC
Solidity 0.8.10 skips the `extcodesize` check for external calls whenever it can be sure that the ABI decoding after the call to a potentially non-existing contract will always revert if that call returns data of length zero.

We added this because we expect it to be a gigantic gas-saver. This unfortunately breaks hardhat's heuristic to detect such a call to a non-existing contract. Sorry, we only discovered it after the release.

Two quick proposals to fix this:
 - use `--revert-strings debug` compiler option for debug builds - this will keep the excodesize check because it results in a different revert data. Upside: Also provides revert strings for other situations like ABI decoding failures. Downside: The deployed code gets larger and might hit the code size limit
 - detect calls to non-existing contracts on the EVM level - this can be done now since the call is actually made in that case. Upside: backwards-compatible, Downside: probably none? Maybe the traces need to be extended?

**Comment by chriseth** [comment] 2021-11-09 19:12
Yes, if the function is not expected to return anything (based on its type), the extcodesize check will still be there. Without looking at the code of the called contract, you will not be able to distinguish the case of "called non-existing contract" from "abi type confusion on the called function".

**Comment by nikola-matic** [comment] 2022-12-16 09:05
Heya @fvictorio, should this also be closed in favour of #3365?

**Comment by cameel** [comment] 2022-12-16 13:18
@nikola-matic IIRC this was broken with legacy codegen as well.

**Comment by nikola-matic** [comment] 2022-12-16 13:34
> @nikola-matic IIRC this was broken with legacy codegen as well.

I guess that's a no then :)

**Comment by fvictorio** [comment] 2022-12-21 19:45
I can't reproduce this, the heuristic seems to work fine when using 0.8.10, even with the optimizer enabled :confused:

**Comment by fvictorio** [comment] 2022-12-22 23:31
Tentatively closing this. Will re-open if we can reproduce it.

**Closed** 2022-12-22 23:33 UTC

**Comment by cameel** [comment] 2023-01-17 14:59
I just checked and this is still reproducible in our CI with latest solc: [1249604](https://app.circleci.com/pipelines/github/ethereum/solidity/28161/workflows/1537f3cb-2e7b-4461-9792-03474dcbe9d6/jobs/1249604)

```
254 passing (17s)
  20 pending
  2 failing

  1) CompatibilityFallbackHandler
       isValidSignature(bytes,bytes)
         should revert if called directly:
     AssertionError: Expected transaction to be reverted with function call to a non-contract account, but other exception was thrown: Error: Transaction reverted without a reason string
  

  2) CompatibilityFallbackHandler
       isValidSignature(bytes32,bytes)
         should revert if called directly:
     AssertionError: Expected transaction to be reverted with function call to a non-contract account, but other exception was thrown: Error: Transaction reverted without a reason string
```

Same locally, on 0.8.10 and without all the overrides we do in CI:
```bash
git clone https://github.com/safe-global/safe-contracts.git
cd safe-contracts/
SOLIDITY_VERSION=0.8.10 npm install
SOLIDITY_VERSION=0.8.10 npm test test/handlers/CompatibilityFallbackHandler.spec.ts
```

**Comment by fvictorio** [comment] 2023-01-20 13:52
Thanks @cameel. I think the underlying issue is https://github.com/NomicFoundation/hardhat/issues/2451, so I'll leave this closed in favor of that one.
