### ISSUE TITLE
Accounts Array Truncation to 20 Signers

### ISSUE THREAD

**Issue by mshakeg** [NomicFoundation/hardhat#5003] opened 2024-03-15 12:18 UTC
### Version of Hardhat

2.19.1

### What happened?

When specifying an array of private keys (1000 in total) for the `accounts` field within a network configuration in Hardhat, it appears that Hardhat truncates the list of signers to only the first 20, despite the array containing more than 20 private keys. This is also the case when specifying a mnemonic with a count of >20. I expected Hardhat to use all provided accounts, allowing me to interact with more than just the first 20 accounts during my tests and deployments.

### Minimal reproduction steps

1. Create a Hardhat project and configure the `hardhat.config.js` file with a custom network that uses an array of 1000 private keys for the `accounts` field or specify a mnemonic with a count of greater than 20.
2. Write a simple script that uses `ethers.getSigners()` to retrieve the signers/accounts.
3. Run the script and observe that only the first 20 signers are available, even though 1000 were provided in the configuration.

**`hardhat.config.js` example snippet:**
```javascript
module.exports = {
  networks: {
    customNetwork: {
      url: "http://localhost:8545",
      accounts: [/* array of 1000 private keys */],
    },
  },
  solidity: "0.8.4",
};
```

**Script to list signers:**
```javascript
async function main() {
  const signers = await ethers.getSigners();
  console.log(`Total signers available: ${signers.length}`);
}

main().then(() => process.exit(0)).catch(error => {
  console.error(error);
  process.exit(1);
});
```

### Expected Behavior:
I expected the script to output "Total signers available: 1000", indicating that all 1000 accounts provided in the `accounts` array are available for use.

### Actual Behavior:
The script outputs "Total signers available: 20", showing that only the first 20 accounts are available, despite the configuration specifying 1000.

### Search terms

signers accounts array limit

**Comment by mshakeg** [comment] 2024-03-15 16:16
@ChristopherDedominici thanks for investigating, all private keys are unique and as mentioned it's also an issue when a mnemonic is used with a count > 20. Also I'm using hardhat but on a forked network.

**Comment by ChristopherDedominici** [comment] 2024-03-15 17:59
Hi @mshakeg, did the 2 points I mentioned before not solve your issue? If this is the case, could you please create a simple Hardhat project where you can reproduce the error and share it with me so I can further investigate? Thanks

**Comment by ChristopherDedominici** [comment] 2024-03-26 10:17
Closing due to no answer in the last 2 weeks

**Closed by ChristopherDedominici** 2024-03-26 10:17 UTC
Labels: status:needs-more-info
