### ISSUE TITLE
Failed to generate 5 stack traces. Run Hardhat 

### ISSUE THREAD

**Issue by adil-techcode** [NomicFoundation/hardhat#5181] opened 2024-05-06 09:41 UTC
I m facing this Error while testing , How to solve this Issue?

**Comment by schaable** [comment] 2024-05-06 12:29
Hi @adil-techcode. Can you explain when you're getting this error? A list of reproduction steps or a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be useful. Thanks!

**Comment by adil-techcode** [comment] 2024-05-06 16:19
hi @schaable  ,
When attempting to execute a test file, I encounter either partially solved test cases , but some accompanied by the error message "UnsuccessfulExecution()." Additionally, I receive a notification indicating "Failed to generate 8 stack traces." How can I resolve these conflicts?

![image](https://github.com/NomicFoundation/hardhat/assets/111005699/3ad8c24c-f2c9-4cdb-8344-f79d6d5b99a3)

**Comment by schaable** [comment] 2024-05-06 17:46
From the test output, I can see that there was some kind of issue with your transaction, and it's reverting. This could be due to the way the contract is called, or there might be some faulty code in the contract itself. It’s difficult to pinpoint the problem without looking at the code. Could you point us to your repo to further debug?

**Comment by schaable** [comment] 2024-05-27 14:37
Hi @adil-techcode, I'm closing this for bookkeeping reasons, but I'll be happy to reopen it if this issue persists and you can provide more information. Thanks!

**Closed by schaable** 2024-05-27 14:37 UTC
Labels: status:needs-more-info
