### ISSUE TITLE
Hedera Hashgraph 

### ISSUE THREAD

**Issue by stefan-stefanooov** [NomicFoundation/hardhat#4429] opened 2023-09-29 08:09 UTC
### Version of Hardhat

^2.17.3

### What happened?

Hello everyone,

I am working on the [Hedera Hashgraph](https://hedera.com/) project.
We are trying to integrate with your wonderful project for obvious reasons :)

In **Hedera** we have a thing called system contracts that allow the network to expose native service implementations on top of the EVM through smart contracts.

They are called from a predefined address. ("0x167" for example)
If we create a smart contract, that uses this address and write a test for it with your tool, we get the following **error**:
<img width="1095" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/10372129/af08f7cb-0930-47d9-9ac7-64e246b7a935">

A little something from the **"--show-stack-traces"** flag ... 
<img width="1117" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/10372129/860438fb-122d-446a-9027-68769f7cce6f">

Can you please have a look?
We would really like for you to support our project.

Please let me know if I can do anything else to help US solve this. 

Best of wishes,
Stefan

### Minimal reproduction steps

- Create a normal out of the box **hardhat** project. 
`npm install --save-dev hardhat`
`npx hardhat init` --- use TypeScript 
- add the 4 contracts and test file in the [GitHub gist](https://gist.github.com/stefan-stefanooov/08191e704db60aacda6e6c7d0332969c) 
- run the tests
- we also use this [tool](https://www.npmjs.com/package/solidity-coverage) for our code-caverage 

### Search terms

hedera hashgraph hardhat precompile address code-coverage

**Comment by ChristopherDedominici** [comment] 2023-10-10 16:21
Hi @stefan-stefanooov, I'm checking the issue and I have a question: is the GitHub gist that you shared correct? I see a lot of code  that I cannot understand:
<img width="793" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/18092467/20039f0b-15ec-4a5f-8f1d-994127076c05">

**Comment by stefan-stefanooov** [comment] 2023-10-10 16:48
Apologies Sir @ChristopherDedominici , 
I just edited my link ...hopefully to the correct gist.
Please confirm that you can open it. And that it's something meaningful. 

I'll also add it here.
https://gist.github.com/stefan-stefanooov/08191e704db60aacda6e6c7d0332969c

Thank you for checking this out :) 
I am here for you if you need me for more clarifications.

**Comment by fvictorio** [comment] 2023-10-20 13:32
Hey @stefan-stefanooov, I can confirm that your transaction is reverting, but that doesn't necessarily mean there's a bug in Hardhat.

If you think this is happening because the code assumes that some precompile exist, then the problem is that the Hardhat network only has Ethereum's standard precompiles. If you want to simulate those, then you need to have some bytecode in those addresses with the same functionality (you can use `hardhat_setCode` for that).

I'm tentatively closing this, but I can re-open it if there's indeed a problem on our side.

**Closed by fvictorio** 2023-10-20 13:32 UTC
Labels: status:triaging
