### ISSUE TITLE
[hardhat-chai-matchers] Expecting "reverted" doesn't work when tested with sendTransaction

### ISSUE THREAD

**Issue by superical** [NomicFoundation/hardhat#3802] opened 2023-03-29 15:29 UTC
### Version of Hardhat

2.13.x

### What happened?

Very strangely, when testing for a call to revert using ethers' `sendTransaction`, the error thrown escapes from the expected `revertedWith`, `reverted`, basically, `reverted*`.

I couldn't quite understand how this is happening. My workaround to this problem is by using a `try/catch` but it's not pretty.

### Minimal reproduction steps

Here's an example to illustrate the problem:

```
const signer = (await ethers.getSigners())[0]

// Here's an intentionally malfunctioned data that will trigger the contract's call to revert with some reason
const malfunctionedData = '0x....';

const tx = signer.sendTransaction({
  to: contractAddress,
  data: malfunctionedData
})

// Now, here's the issue. The following test fails because the error escapes the expect and it wasn't caught within the test.  
await expect(tx).to.be.revertedWith('Invalid token ID')
```
The call made via `sendTransaction` did revert but the error is thrown instead of being caught by the `expect`. The error is printed in the console instead:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"VM Exception while processing transaction: reverted with reason string 'Invalid token ID'","code":"UNPREDICTABLE_GAS_LIMIT"........
```

If I had made the call by using a typical function call like so, it would have worked:
```
const tx = contract.transferFrom('0xAlice', '0xBob', 123)

// Passes the test because revert was caught by expect
await expect(tx).to.be.revertedWith('Invalid token ID')
```
In this example, the test passed because it reverted as expected; the error didn't escape and get thrown to the console like it did with `sendTransaction`.

### Search terms

ethers, expect, revert

**Comment by fvictorio** [comment] 2023-04-04 09:28
Hi @superical, I couldn't reproduce this. Here's the contract I used:

```solidity
contract Foo {
  function f() public {
    require(false, "boom");
  }
}
```

and here's the test:

```js
it("test", async function () {
  const [s] = await ethers.getSigners();
  const foo = await ethers.deployContract("Foo");


  // normal call
  const tx1 = foo.f();
  await expect(tx1).to.be.revertedWith("boom");

  // sent from signer
  const tx2 = s.sendTransaction({
    to: foo.address,
    data: "0x26121ff0", // selector of f()
  });

  await expect(tx2).to.be.revertedWith("boom");
});
```

And it worked fine.

I'm going to tentatively close this, but I'm happy to re-open it if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Closed by fvictorio** 2023-04-04 09:28 UTC
