### ISSUE TITLE
HardhatError: HH110: Invalid JSON-RPC response received: no healthy upstream

### ISSUE THREAD

**Issue by eulerbeat** [NomicFoundation/hardhat#2762] opened 2022-05-26 18:02 UTC
In a hardhat local fork environment with a Moralis speed archive node, the call (read-only) fails after some time. For a while after forking, the calls are going through successfully but after some time, it fails with the error:
```
"code":"SERVER_ERROR"
"message":"HardhatError: HH110: Invalid JSON-RPC response received: no healthy upstream"
```

**Comment by fvictorio** [comment] 2022-05-27 22:51
This seems like a problem with the Moralis server. Have you tried contacting them about this?

I'm going to close this issue because, if it's indeed a problem in the server, there's not much we can do. But please let us know if you think the problem is in hardhat.

**Closed by fvictorio** 2022-05-27 22:51 UTC
