### ISSUE TITLE
Support for yarn berry (v2)

### ISSUE THREAD

**Issue by paulrberg** [NomicFoundation/hardhat#586] opened 2020-05-18 20:53 UTC
[Berry](https://github.com/yarnpkg/berry) is yarn's v2 release and is disruptive in many regards. They replaced "node_modules" with a new [plug-n-play](https://classic.yarnpkg.com/en/docs/pnp/) system that caches dependencies more efficiently.

In the docs for [Typescript support](https://buidler.dev/guides/typescript.html#plugin-type-extensions), you specify that we should add this to our `tsconfig.json` config:

```json
"files": [
  "./buidler.config.ts",
  "./node_modules/@nomiclabs/buidler-ethers/src/type-extensions.d.ts",
  "./node_modules/@nomiclabs/buidler-waffle/src/type-extensions.d.ts"
]
```

But this is sadly not possible in yarn v2. I suppose that this is not a priority, but I wanted to open an issue about it anyways, in case more people stumble upon it and want to signal their support.

**Comment by PaulRBerg** [comment] 2020-05-18 21:12
It's actually worse than just not being able to use the ethers and waffle plugins. The way Buidler is architected seems to not be compatible \*at all\* with yarn v2 + typescript.

If I run `yarn buidler compile` in a yarn v2 project, I am given the default response:

```sh
? What do you want to do? … 
❯ Create a sample project
  Create an empty buidler.config.js
  Quit
```

But if I copy-and-paste the same source code into a yarn v1, `yarn builder compile` successfully compiles the contract:

```sh
Compiling...
Downloading compiler version 0.6.8
Compiled 1 contract successfully
✨  Done in 4.12s.
```

For the record, this is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": ["es5"],
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true,
    "target": "es5",

    "noImplicitAny": true,
    "strict": true,

    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,

    "forceConsistentCasingInFileNames": true
  },
  "files": [
    "./buidler.config.ts",
    "./node_modules/@nomiclabs/buidler-ethers/src/type-extensions.d.ts",
    "./node_modules/@nomiclabs/buidler-waffle/src/type-extensions.d.ts"
  ],
  "include": ["./scripts", "./test"]
}
```

**Comment by alcuadrado** [comment] 2020-05-18 21:22
Thanks for opening this issue, @PaulRBerg!

As you mentioned, yarn 2 is very disruptive, and controversial. It's unclear if/when it will be successful enough to justify adapting Buidler. I think it may never be released as `yarn@latest`. Now that npm is owned by GitHub, and yarn is no longer maintained by Facebook, its future is even more unclear imo.

I've been following pnp for some time and had already identified a [module of Buidler](https://github.com/nomiclabs/buidler/blob/development/packages/buidler-core/src/internal/core/execution-mode.ts#L10) that needs to be adapted. I haven't thought about the type extensions though. Have you found any other thing that needs to be changed?

If someone else does feel that Yarn v2 should be supported, please let us know in this issue.

**Comment by PaulRBerg** [comment] 2020-05-18 22:18
Well, with over [38.5k](https://github.com/yarnpkg/yarn) stars, an active and responsive community on Discord and killer features like [workspaces](https://classic.yarnpkg.com/en/docs/workspaces/), it's hard for Yarn to fade away any time soon. Not impossible, but hard.

As v2 is concerned, it is super promising. The "node_modules" folder is a sunk cost we all got used to, yet I suspect that everyone would incline to say that life would better without it. Supporting yarn v2 is a small step towards a better developer experience in the big, vivid world of open-source, not just JavaScript or Ethereum.

What incompatibilities I found in Buidler, specifically:

1. The "buidler.config.ts" file is not recognised when yarn v2 finds and executes buidler from pnp
2. The ethers and waffle plugins cannot be used because their type extensions cannot be added to "tsconfig.json"

I'll keep reporting things here as I discover them.

**Comment by alcuadrado** [comment] 2020-05-18 22:43
> it's hard for Yarn to fade away any time soon

I completely agree. I just think it's possible that Yarn 2 gets released under another name, or keeps tagged as `@next` for a very long time.

**Comment by PaulRBerg** [comment] 2020-05-20 01:18
Yeah it's probably going to take a while before a fully-fledged release.

FWIW, I discovered in the meantime that you can use yarn v2 with node_modules instead of plug-n-play, with this magic [node_modules linker](https://yarnpkg.com/advanced/migration#if-required-enable-the-node-modules-plugin). If you do this, you inadvertently discard the zero-install approach, so you also have to modify your `.gitignore` file, as per the [instructions](https://stackoverflow.com/questions/60184159/yarn-v2-gitignore) here.

**Comment by lepidotteri** [comment] 2020-10-12 17:28
so, can we support Berry?

**Comment by chapati23** [comment] 2020-10-29 16:01
I ran into this today as well with yarn v2 (which by the way is now the "official" yarn, e.g. https://yarnpkg.com is all about v2 now), although my issue is more related to type definitions.

i don't have a custom `tsconfig.json` (as per the docs) so I'm wondering whether I need to set any additional config for vscode to recognize the hardhat types correctly

<img width="889" alt="image" src="https://user-images.githubusercontent.com/117495/97599431-484d0600-1a08-11eb-8fd6-2925bc14e31a.png">

**Comment by alcuadrado** [comment] 2020-10-29 16:55
Have you tried resetting vscode? I know how this question looks like 😅 but vscode's typescript support is buggy and restarting it fixes it.

**Comment by chapati23** [comment] 2020-11-04 18:34
i actually don't know anymore what fixed it in the end. but without adding a `tsconfig.json` even a vscode restart didn't fix this

**Comment by chapati23** [comment] 2020-11-04 18:35
FWIW I've abandoned my yarn v2 efforts for the moment, I love the speed, but I'm losing time in other places now when running into compatibility issues with other packages :-/

**Comment by platocrat** [comment] 2021-01-08 21:26
> Have you tried resetting vscode? I know how this question looks like 😅 but vscode's typescript support is buggy and restarting it fixes it.

I no longer experience that issue thanks to the resolve I found in https://github.com/nomiclabs/hardhat/issues/1137#issue-775167379.

Also, @chapati23 idk how you're using yarn2, but using `hardhat` with yarn2 works perfectly fine for me.

**Comment by platocrat** [comment] 2021-01-08 21:38
@chapati23  I can also confirm that @alcuadrado is correct that vscode's TS support is quite buggy. Just ran a TypeScript test file with hardhat and experienced no issues.

View my snapshot of my VSCode env to confirm and close.

<img width="1021" alt="Screen Shot 2021-01-08 at 3 38 22 PM" src="https://user-images.githubusercontent.com/37757724/104066753-8bc1ae80-51c7-11eb-9dce-01c2e95bd4a9.png">

**Comment by platocrat** [comment] 2021-01-08 21:40
I'll run `yarn --version` again because resizing my terminal window created a bug in how the line in the previous pic was displayed.

<img width="1021" alt="Screen Shot 2021-01-08 at 3 39 25 PM" src="https://user-images.githubusercontent.com/37757724/104066841-b1e74e80-51c7-11eb-9e1e-b1672aeb81ce.png">

**Comment by kevinji** [comment] 2022-05-29 23:19
Another issue I've run into: the combination of yarn pnp, yarn workspaces, and TypeScript is a broken experience with Hardhat. I get errors like
```
Error HH13: Your Hardhat project uses typescript, but ts-node is not installed.

Please run: npm install --save-dev ts-node
```
despite having installed `ts-node` in the workspace. I think there's some issue with Hardhat resolving paths to its dependencies when yarn pnp and workspaces are both used.

**Comment by ShravanSunder** [comment] 2022-10-26 11:12
@alcuadrado any plans for plug n play compatibility for hardhat?

**Comment by fvictorio** [comment] 2022-12-30 12:25
I'm not sure if this is still relevant? I think yarn v2 works with Hardhat, at least in the sample project I tried it.

I'm going to close this now. If someone has a specific problem about Hardhat + Yarn v2, please open a new issue.

**Closed by fvictorio** 2022-12-30 12:25 UTC
Labels: priority:low

**Comment by ShravanSunder** [comment] 2023-01-04 21:08
It doesn't working with yarn plug n play.  it works with node_modules @fvictorio

**Comment by fvictorio** [comment] 2023-01-06 09:35
@ShravanSunder I was able to initialize and compile projects in javascript and typescript with yarn v3 and PnP enabled. If something related to this is not working for you and you can provide minimal reproduction steps, please open a new issue.
