### ISSUE TITLE
Nested calls to loadFixture() do not always work

### ISSUE THREAD

**Issue by m1cm1c** [NomicFoundation/hardhat#2980] opened 2022-07-21 20:55 UTC
When passing a function to `loadFixture()` that itself calls `loadFixture()`, this sometimes fails with an error message saying that loaded fixtures are not supported. This happens especially often if nesting more than once.

```
     FixtureSnapshotError: There was an error reverting the snapshot of the fixture.

This might be caused by using nested loadFixture calls in a test, for example by using multiple beforeEach calls. This is not supported yet.
      at loadFixture (node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:47:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async recoverViaDistributor (test/Wallet2.ts:111:9)
```

**Comment by m1cm1c** [comment] 2022-07-21 20:56
I propose a simple way of circumventing this issue in #2981.

**Comment by faces-of-eth** [comment] 2022-08-07 04:37
Running into this as well. Even if all "describe" blocks are removed the error still happens; so the error message isn't the clearest.

**Comment by fvictorio** [comment] 2022-08-08 18:15
Hey @m1cm1c, thanks for opening this. I'm a bit confused though. The way I would think about composing fixtures is that you would have something like:

```js
function deployTokenFixture() {
  // deploy a token
}

function deployWrappedTokenFixture() {
  const { token } = await deployTokenFixture();

  const wrappedToken = ...;

  return { token, wrappedToken }
}
```

And then in some tests you do `loadFixture(deployTokenFixture)` and in others you do `loadFixture(deployWrappedTokenFixture)`, but you don't use `loadFixture` inside a fixture function. Does that make sense? And if this doesn't work for your use case, can you explain why?

**Comment by m1cm1c** [comment] 2022-08-09 07:46
@fvictorio This is exactly what my proposed fix boils down to, except it has the advantage that if true nested fixture support were to ever be implemented (i.e. not executing `deployTokenFixture()` again when `deployWrappedTokenFixture()` gets executed), tests would already be implemented in the way that can take advantage of that future performance improvement.

However, documenting how to do it would be almost equivalent to the fix. When first encountered fixtures, I thought you could use them in any way to skip duplicate chain mutations, including of course inside another sequence of chain mutations. If the way to avoid the problem were documented, there'd be no need for the fix.

**Comment by fvictorio** [comment] 2022-08-10 13:44
> When first encountered fixtures, I thought you could use them in any way to skip duplicate chain mutations, including of course inside another sequence of chain mutations. If the way to avoid the problem were documented, there'd be no need for the fix.

This is very useful feedback, thank you

**Comment by fvictorio** [comment] 2022-08-11 08:39
I've already captured this in our documentation backlog, so I'm going to close this issue now. Thanks again.

**Closed by fvictorio** 2022-08-11 08:39 UTC

**Comment by sebastianst** [comment] 2022-08-20 14:51
I am a bit confused @fvictorio - is calling `loadFixture` inside another fixture function to apply chain mutations on top of the first fixture's snapshot now supported or ever will be? This could definitely lead to some potentially large performance improvements.

**Comment by fvictorio** [comment] 2022-08-20 22:54
It's not supported yet. Maybe it could be supported in the future, but it feels like an anti-pattern to me. IMO each fixture should be about deploying contracts and sending transactions. Executing a fixture with `loadFixture` should be orthogonal to that (in my mind at least, I'm open to being wrong here).

I'm not sure if supporting this would lead to *large* performance improvements. Take my example from before:

```js
function deployTokenFixture() {
  // deploy a token
}

function deployWrappedTokenFixture() {
  const { token } = await deployTokenFixture();

  const wrappedToken = ...;

  return { token, wrappedToken }
}
```

If you use the first fixture in 10 tests and the second fixture in other 10 tests, the first fixture would be executed twice (when it's called with `loadFixture` for the first time, and when it's called through the other fixture also for the first time) and the second fixture once.

If it was possible to call `loadFixture` inside the second fixture, then both fixtures would be executed only once. While this is (kind of) a 33% improvement, it's a small change compared to the speedup you get when you go from deploying in each test (where the fixtures are executed 20 and 10 times, respectively) to deploying only once via the `loadFixture` helper.

Does that make sense?

That being said, we do want to support nested calls to `loadFixture` for other reasons (nested `describe`s with `beforeEach`s that deploy things) and when that is done, then I think what you are asking for will also be possible.

**Comment by sebastianst** [comment] 2022-08-22 09:12
Yes that makes sense and in the scenario you described (10 tests for each fixture) the performance improvements are indeed marginal.

I just encountered a different scenario where the first fixture is large and the additional steps in the second fixture are small but still worthwhile putting into a fixture. Also, the second fixture would only be called 2-3 times. In this scenario, the cost of running the first=main fixture is not so easily amortized.

But happy to hear that it will soon be properly supported!

**Comment by krzysztof-cywinski** [comment] 2022-09-09 12:36
Hi. I'm having a similar issue despite using the proposed solution from https://github.com/NomicFoundation/hardhat/issues/2980#issuecomment-1208451537

Minimal steps to reproduce:
1. npm init
2. npm install hardhat
3. create sample project and install its dependencies
4. in test/Lock.ts add:

```
  async function testFixture() {
    const { lock, unlockTime, lockedAmount, owner, otherAccount } = await deployOneYearLockFixture();
    // do anything or nothing here. doesn't matter.
    return { lock, unlockTime, lockedAmount, owner, otherAccount };
  }
```

add two sets of test cases:

```
    describe("B", function () {
      it("B", async function () {
        const { lock, unlockTime, lockedAmount, owner } = await loadFixture(
          testFixture
        );
      });
    });

    describe("A-B", function () {
      it("A", async function () {
        const { lock, unlockTime, lockedAmount, owner } = await loadFixture(
          deployOneYearLockFixture
        );
      });

      it("B", async function () {
        const { lock, unlockTime, lockedAmount, owner } = await loadFixture(
          testFixture
        );
      });
    });
```

the second B fails with:
```
FixtureSnapshotError: There was an error reverting the snapshot of the fixture.

This might be caused by using nested loadFixture calls in a test, for example by using multiple beforeEach calls. This is not supported yet.
      at loadFixture (/private/tmp/test-hardhat/node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:47:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (/private/tmp/test-hardhat/test/Lock.ts:147:59)
  
      Caused by: InvalidSnapshotError: Trying to restore an invalid snapshot.
          at Object.restore (/private/tmp/test-hardhat/node_modules/@nomicfoundation/hardhat-network-helpers/src/helpers/takeSnapshot.ts:33:15)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async loadFixture (/private/tmp/test-hardhat/node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:44:7)
          at async Context.<anonymous> (/private/tmp/test-hardhat/test/Lock.ts:147:59)
```

The pattern seems to be that when you have a fixture A and a fixture B that calls A internally:
```
function A() {
  // deploy
}

function B() {
  const { token } = await A();

  // make a TX

  return { ... }
}
```

Then when you make a test with fixture B, then with fixture A, and then with B again, the second B always fails.
If you remove the A test from between the two B tests it works and both B tests pass.
It's as if the call to fixture A after the call to fixture B broke fixture B somehow.
