### ISSUE TITLE
hardhat-completions doesn't work on macOS zsh

### ISSUE THREAD

**Issue by tjcloa** [NomicFoundation/hardhat#4282] opened 2023-08-11 06:44 UTC
### Version of Hardhat

2.13.0

### What happened?

I followed the instruction https://hardhat.org/hardhat-runner/docs/guides/command-line-completion to setup `hardhat-completions` and `hh shorthand` . 
While `hh` shorthand works fine (`hh compile` and all other tasks run fine), `hardhat-completions` falls back to listing files and folders.  
This issue seems to be around for quite a while, but i couldn't find any solution. 
https://github.com/NomicFoundation/hardhat/issues/1878 - i tried all the suggestions from this issue - no use. 
OS: macOS Ventura 13.4.1 (22F82)

### Minimal reproduction steps

- Install `hardhat-shorthand` and `hardhat-completions`on zsh following manual https://hardhat.org/hardhat-runner/docs/guides/command-line-completion 
- Run `hh <TAB>` in terminal - falls back to files and folders listing instead of hardhat completions list. 

### Search terms

hardhat-completions does not work

**Comment by fvictorio** [comment] 2023-08-11 07:47
Hey @tjcloa, issues related to autocomplete are always hard to investigate, but here are some things you can run that would give us more information.

First, run `declare -f _hh_completion`. That should show the definition of the completion script installed by `hardhat-shorthand`. If this doesn't print anything, then the completion script wasn't installed correctly, or maybe it was installed but it isn't being loaded.

If that's the case, go to your `.zshrc` and check that you have something like this there:

```zsh
# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
```

That's the path for linux; in macOS it's probably a different place. But in any case, go to the directory where `__tabtab.zsh` is and check that there is a `hh.zsh` file too.

Please try all of that and let me know what you get.

**Comment by fvictorio** [comment] 2023-08-11 08:40
And does `~.config/tabtab/zsh/hh.zsh` exist?

**Comment by tjcloa** [comment] 2023-08-11 08:50
yes 
`~/.config/tabtab/zsh/hh.zsh`
```
###-begin-hh-completion-###
if type compdef &>/dev/null; then
  _hh_completion () {
    local reply
    local si=$IFS

    IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" hardhat-completion completion -- "${words[@]}"))
    IFS=$si

    if [ "$reply" = "__tabtab_complete_files__" ]; then
      _files
    else
      _describe 'values' reply
    fi
  }
  compdef _hh_completion hh
fi
###-end-hh-completion-###
```

**Comment by fvictorio** [comment] 2023-08-11 09:30
I'm a bit lost there. And you are sure that your Hardhat project doesn't have any issues, right? I mean, if you run `npx hardhat compile`, it works fine.

If that's the case, but `hh` still doesn't work... then I'm out of clues, I have no idea what could be the case.

**Comment by tjcloa** [comment] 2023-08-11 09:51
>I'm a bit lost here. And you are sure that your Hardhat project doesn't have any issues, right? I mean, if you run npx hardhat compile, it works fine.  

yes, that's right  
`hh` works per se, it is only `hardhat-completion` that doesn't work, it falls back to the default node completion i guess just listing files and folders at `hh<SPACE><TAB>` instead of hh tasks list/completion.

**Comment by tjcloa** [comment] 2023-08-11 09:53
it looks like this is pretty much the same issue that in https://github.com/NomicFoundation/hardhat/issues/1878 which was automatically closed without actual solution

**Comment by fvictorio** [comment] 2023-08-11 11:02
Ah, I think I know what's going on. Can you add this to the beginning of your `.zshrc` file and try again in a new terminal?

```
autoload -U compinit && compinit
```

**Comment by tjcloa** [comment] 2023-08-11 13:37
i already tried putting this in all possible options:
- having it in the beginning of the file leads to a weird behaviour when it seems to start loading hardhat instead of completion list logging by `hh <TAB>` - first logs appear similar to those of `hh <ENTER>` and then it just freezes 
- having it after `[[ -f ~/.config/tabtab/zsh/hh.zsh ]] && . ~/.config/tabtab/zsh/hh.zsh || true` or surroundig it like this:  
```
    autoload -U compinit 
    [[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
    compinit
``` 
 has no effect - falls back to listing files and folders

**Comment by fvictorio** [comment] 2023-08-11 15:28
In that case I think I will need some way to reproduce it, but I know that's super hard to do because it's very environment-dependent.

What I did to figure out the `compinit` thing was to try everything inside a docker container. If you are familiar with docker, you can use this Dockerfile as a starting point:

```
from node:18

run apt update && apt install -y zsh

run echo "autoload -U compinit && compinit" > ~/.zshrc

run npm i -g hardhat-shorthand

workdir /hardhat-project

run npm init -y

run npm install hardhat && echo 'module.exports = { solidity: "0.8.20" }' >> hardhat.config.js

cmd zsh
```

If you build that image and start a container with it (`docker build -t hh-zsh . && docker run -it --rm hh-zsh`), and then do:

```sh
hardhat-completion install
# select zsh and "yes"

zsh # open a new zsh instance to reload the .zshrc

hh <tab>
```

you'll see that it works. Then you can modify that `.zshrc`, making it gradually more similar to yours, until you get to a minimal `.zshrc` that reproduces the problem.

I know this is a lot to ask, but I'm out of ideas so without a reproducible example there isn't much I can do.

**Comment by fvictorio** [comment] 2023-08-23 10:28
Tentatively closing this. I will re-open it if someone can provide complete reproduction steps (see previous comment).

**Closed by fvictorio** 2023-08-23 10:28 UTC
Labels: status:needs-more-info
