### ISSUE TITLE
Forking Polygon PoS with hardhat + Alchemy Failing with Connection Timeout Error

### ISSUE THREAD

**Issue by aduttya** [NomicFoundation/hardhat#4069] opened 2023-06-26 06:06 UTC
I am trying to fork the Polygon PoS with Alchemy and it gives me the error of timeout while my internet connection is pretty good. I don't know why sometimes it runs successfully and sometimes it fails. Following is the error I am getting while trying to do the fork. I have followed this: https://hardhat.org/hardhat-network/docs/guides/forking-other-networks
![fork error](https://github.com/NomicFoundation/hardhat/assets/55932256/2bd1e856-36d3-4a64-81d0-cc1104d99eff)

**Comment by fvictorio** [comment] 2023-06-28 18:06
Sorry but I can't reproduce this. I forked polygon a couple of times (also using Alchemy) and didn't get the error.

I'm going to tentatively close this, but I'll re-open if you can provide minimal reproduction steps.

Also, for what it's worth: if this is indeed happening, then it might be fixed by https://github.com/NomicFoundation/hardhat/pull/3665

**Closed by fvictorio** 2023-06-28 18:06 UTC
Labels: status:triaging
