### ISSUE TITLE
[Bug] Set hardhat.config.ts[.js] 's config.networks.hardhat.mining.auto to false will lead test Error with revertedWith

### ISSUE THREAD

**Issue by Funarp** [NomicFoundation/hardhat#4242] opened 2023-08-04 16:58 UTC
### Version of Hardhat

2.17.1 (other version may have this bug)

### What happened?

At first, I am a new bee to hardhat for just a few days, so maybe this is not a bug.

I am writing a time-related contract, so I set  `hardhat.config.ts[.js]` 's `config.networks.hardhat.mining.auto` = false and `interval: [2500, 3500]`

when i run tests with `await expect(fn()).to.be.revertedWith('ERC20: insufficient allowance');` 

It should be reverted and the `hardhat node` reported reverted, but `hardhat test` console tells me:

```
AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.
```

I did a lot debug today, after many tries, I suddenly found out this optional, I set it back to true(enable automine), then It works!

### Minimal reproduction steps

I think you can just try hardhat starter project for test, just set hardhat.config.ts[.js] into this:
```ts
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";

const config: HardhatUserConfig = {
  solidity: "0.8.19",
  networks: {
    hardhat: {
      mining: {
        auto: false,
        interval: [2500, 3500]
      }
    }
  }
};

export default config;
```
and run the test, the bug will show up, and it seems only affect `revertedWith()` I thought maybe the logical of dealing with transaction receipt is wrong somewhere

**Comment by fvictorio** [comment] 2023-08-07 09:39
Hi @funarp, I think this is a duplicate of https://github.com/NomicFoundation/hardhat/issues/3203, can you confirm?

The reason the revert matchers don't work right now when automining is disabled is that obtaining the return data is a bit more involved than when automining is enabled. It's not impossible though.

If this is indeed a duplicate of that issue, please upvote that one. That helps us gauge how much interest there is in it.

**Comment by fvictorio** [comment] 2023-08-07 16:52
Yes, that makes sense. I opened https://github.com/NomicFoundation/hardhat/pull/4253 with a short clarification in the docs.

**Comment by fvictorio** [comment] 2023-08-09 07:12
Closing this in favor of #3203.

**Closed by fvictorio** 2023-08-09 07:12 UTC
Labels: status:needs-more-info
