### ISSUE TITLE
Inconsistent Hardhat Deployment Issues

### ISSUE THREAD

**Issue by codingwithmanny** [NomicFoundation/hardhat#4711] opened 2023-12-22 13:50 UTC
### Version of Hardhat

2.19.3

### What happened?

**Issues:**
When doing basic deployments on different networks, either transactions hang or don't get complete at all

**Tests Performed**
```
Ethereum
(Need more ETH)

Polygon
✅ Hardhat Viem - 0xe43f591ad474ca29deb4d0c89702539d66849b7f
❌ Hardhat Ethers6 - (Script Hangs - No Tx Hash)
✅ Foundry - 0xbC7D321D31e64733Db7a1e4C9dD33941D68fEbB7

Goerli
✅ Hardhat Viem - 0xE43F591AD474ca29deB4d0C89702539d66849b7F
✅ Hardhat Ethers6 - 0x338d3f6d02440e29c1E7D2362FBFC266930aB14b
✅ Foundry - 0xb81e538ed2394b2494608c283a557f0a9a4b9301

Mumbai
❌ Hardhat Viem - (Tx Hangs - 0x14394d044ce5f05f6f233b418b25506415690b7d78e1df0d366ed18c74b1c477 but not deployed)
❌ Hardhat Ethers6 - (Script Hangs - No Tx Hash)
✅ Foundry - 0xbC7D321D31e64733Db7a1e4C9dD33941D68fEbB7
```

### Minimal reproduction steps

1. npx hardhat init
2. Typescript or Typescript with viem
3. Configure hardhat.config.ts with proper networks (https://rpc.ankr.com/polygon, https://rpc.ankr.com/polygon_mumbai, https://rpc.ankr.com/eth_goerli)
4. Try deploying the contract and see isues

**Comment by codingwithmanny** [comment] 2023-12-22 13:50
Potential solution:
https://github.com/NomicFoundation/hardhat/pull/4710

**Comment by schaable** [comment] 2023-12-23 19:27
Hi @codingwithmanny, I just tested deploying on Mumbai using the same RPC url. It works for me:
Ethers: https://mumbai.polygonscan.com/address/0x9b90613832eB692e302B7a0e992C543ED7147804
Viem: https://mumbai.polygonscan.com/address/0xf35b9ed8c4b10492218367b2a7a824d5f9dfd7a0
We may need detailed steps or a sample repository where we can test it (if you do this, leave the accounts array in the config empty).

**Comment by codingwithmanny** [comment] 2023-12-24 13:29
Hi @schaable will get you the different scripts (hardhat ethers6, hardhat viem, just viem, just ethers6, and forge) that way it'll be easier to test.

I just need to move it over to a public repository.

**Comment by fvictorio** [comment] 2024-01-29 18:26
@codingwithmanny I'm tentatively closing this for book-keeping reasons, but I'm more than happy to re-open if you can provide those reproduction steps.

**Closed by fvictorio** 2024-01-29 18:26 UTC
Labels: status:needs-more-info
