### ISSUE TITLE
Some Signers generated with `ethers.getImpersonatedSigner` error out when sending transactions.

### ISSUE THREAD

**Issue by Majiick** [NomicFoundation/hardhat#3616] opened 2023-01-26 16:55 UTC
### Version of Hardhat

2.12.6

### What happened?

Some Signers generated with `ethers.getImpersonatedSigner` error out when sending transactions.

Error:
```
InvalidArgumentsError: Errors encountered in param 0: Invalid value undefined supplied to : HASH
      at validateParams (/root/node_modules/hardhat/src/internal/core/jsonrpc/types/input/validation.ts:64:13)
      at EthModule._getTransactionReceiptParams (/root/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:854:26)
      at EthModule.processRequest (/root/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:209:19)
      at HardhatNetworkProvider._send (/root/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:195:31)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at HardhatNetworkProvider.request (/root/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at TracerWrapper.request (/root/node_modules/hardhat-tracer/src/wrapper.ts:57:19)
      at EthersProviderWrapper.send (/root/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

### Minimal reproduction steps

For example 

```
// Working example
const owner = await ethers.getImpersonatedSigner("0x1234567890123456789012345678901234567890");
const transactionHash = await owner.sendTransaction({
        to: "0x1825FE1AEa79312FFBf44890Fc74DC28DC826386",
        value: ethers.utils.parseEther("1.0"), // Sends exactly 1.0 ether
});
```

```
// Non-working example, errors out.
const owner = await ethers.getImpersonatedSigner("0x4F1942eFEB53Ff047FfA47DEbE06B1Fd5f368d5C");
const transactionHash = await owner.sendTransaction({
        to: "0x1825FE1AEa79312FFBf44890Fc74DC28DC826386",
        value: ethers.utils.parseEther("1.0"), // Sends exactly 1.0 ether
});
```

The only difference is the addresses. Some existing addresses (non-newly generated) such as `0xee933609D7c3E9CfaE38b0B0E436f8663D850bfC` also error out.

### Search terms

getImpersonatedSigner

**Comment by Majiick** [comment] 2023-01-26 17:06
There is no difference in either Signers beside the address: https://www.diffchecker.com/kTuceVo1/

**Comment by fvictorio** [comment] 2023-03-01 10:37
Hey @Majiick, sorry for the late response.

I cannot reproduce this. If I run those snippets while forking mainnet, the second one (correctly) throws an error about not having enough funds. If I send some ETH to it before running the tx (so that it has funds), then both work.

I'm tentatively closing this, but I'll re-open if you can provide a minimal reproduction example that I can clone and run.

**Closed by fvictorio** 2023-03-01 10:37 UTC
Labels: status:triaging
