### ISSUE TITLE
Error HH5: HardhatContext is not created not being fixed

### ISSUE THREAD

**Issue by Priyanshu-Desai** [NomicFoundation/hardhat#5097] opened 2024-04-08 16:57 UTC
I am running the below code:
```javascript
const { ethers, run, network } = require("hardhat");

async function main() {
  const simpleStorageFactory = await ethers.getContractFactory("SimpleStorage");
  console.log("Deploying contract...");
  const simpleStorage = await simpleStorageFactory.deploy();
  await simpleStorage.waitForDeployment();
  simpleStorageAddress = simpleStorage.target;
  console.log(`Contract deployed to: ${simpleStorageAddress}`);
  if (network.config.chainId === 11155111 && process.env.ETHERSCAN_API_KEY) {
    await simpleStorage.deployTransaction.wait(5);
    await verify(simpleStorage.address, []);
  }
}

async function verify(contractAddress, args) {
  console.log("Verifying contract...");
  try {
    await run("verify:verify", {
      address: contractAddress,
      constructorArguments: args,
    });
  } catch (e) {
    if (e.message.toLowerCase().includes("already verified")) {
      console.log("Contract already verified");
    } else console.log(e);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.log(error);
    process.exit(1);
  });
```

but for some reason the below HH5 error is coming up:
```
HardhatError: HH5: HardhatContext is not created.
    at HardhatContext.getHardhatContext (D:\Priyanshu\blockchain\hardhat-simple-storage\node_modules\hardhat\internal\context.js:38:19)
    at extendEnvironment (D:\Priyanshu\blockchain\hardhat-simple-storage\node_modules\hardhat\internal\core\config\config-env.js:72:42)
    at Object.<anonymous> (D:\Priyanshu\blockchain\hardhat-simple-storage\node_modules\@nomicfoundation\hardhat-ethers\internal\index.js:7:32)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Priyanshu\blockchain\hardhat-simple-storage\node_modules\@nomicfoundation\hardhat-chai-matchers\index.js:3:1) {
  parent: undefined,
  _stack: 'HardhatError: HH5: HardhatContext is not created.\n' +
    '    at HardhatContext.getHardhatContext (D:\\Priyanshu\\blockchain\\hardhat-simple-storage\\node_modules\\hardhat\\internal\\context.js:38:19)\n' +
    '    at extendEnvironment (D:\\Priyanshu\\blockchain\\hardhat-simple-storage\\node_modules\\hardhat\\internal\\core\\config\\config-env.js:72:42)\n' +
    '    at Object.<anonymous> (D:\\Priyanshu\\blockchain\\hardhat-simple-storage\\node_modules\\@nomicfoundation\\hardhat-ethers\\internal\\index.js:7:32)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1112:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:988:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:834:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1012:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
    '    at Object.<anonymous> (D:\\Priyanshu\\blockchain\\hardhat-simple-storage\\node_modules\\@nomicfoundation\\hardhat-chai-matchers\\index.js:3:1)',
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}
```

 have correctly installed hardhat, and all of its dependencies that i need, so why am i getting this error?

Please help.

**Comment by schaable** [comment] 2024-04-08 21:09
Hey @Priyanshu-Desai, your code looks good, I tried to reproduce it by running that script in a fresh hardhat install and it seems to work correctly. Could you share your repository so I can try to reproduce the issue? Make sure to remove any sensitive information such as private keys or API tokens before sharing.

**Comment by schaable** [comment] 2024-04-09 12:32
Hi @Priyanshu-Desai! I've cloned your repo and noticed some dependency mismatches with hardhat and the toolbox's peer dependencies during installation. After a clean install and commenting out the redundant import of `hardhat-verify` in the config (as it's included in the toolbox), the code works. This issue seems to be in your setup. I recommend a fresh hardhat install as per [this guide](https://hardhat.org/hardhat-runner/docs/guides/project-setup) and then copying your files over. I'll close this issue since it appears to be a local setup problem.

**Closed by schaable** 2024-04-09 12:32 UTC
Labels: status:needs-more-info

**Comment by Priyanshu-Desai** [comment] 2024-04-09 12:33
Ok Thanks a lot for the help
