### ISSUE TITLE
Console.log executes twice on reverts

### ISSUE THREAD

**Issue by Pzixel** [NomicFoundation/hardhat#2197] opened 2021-12-28 03:00 UTC
Consider following contract:
```solidity
contract Foo {
    function test() external {
        console.log("Hello from solidity");
        revert("I reverted");
    }
}
```

Now let's call it from test suite:

```js
it('Console log test', async () => {
    console.log("Hello from JS");
    const Foo = artifacts.require('Foo');
    const foo = await Foo.new();
    await foo.test();
});
```

Expected output:

```
      Console log test
Hello from JS
Hello from solidity
     Error: VM Exception while processing transaction: reverted with reason string 'I reverted'
      at Foo.test (contracts/ConsoleTest.sol:16)
      at TruffleContract.test (node_modules\@nomiclabs\truffle-contract\lib\execute.js:169:26)
      at Context.<anonymous> (test\ConsoleTest.js:205:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Actual output:

```
      Console log test
Hello from JS
Hello from solidity
Hello from solidity
     Error: VM Exception while processing transaction: reverted with reason string 'I reverted'
      at Foo.test (contracts/ConsoleTest.sol:16)
      at TruffleContract.test (node_modules\@nomiclabs\truffle-contract\lib\execute.js:169:26)
      at Context.<anonymous> (test\ConsoleTest.js:205:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Note that `Hello from solidity` string was printed twice.

I suspect that hardhat revert processing may be causing printing this twice but this means that either this implementation or console.log itself should consider only actually printing to console once. 

This becomes exceptionally cumbersome when you have dozens of log lines printed interspersed with JS logs that only get printed once - it's hard to tell when happens what. This is a very desirable behavior change. Hope you'll see it this way and have time to fix.

**Comment by alcuadrado** [comment] 2022-01-06 21:30
Thanks for opening this issue, @Pzixel. I agree that this can be extremely annoying.

Can you please create a complete reproduction? That would be very helpful!

**Comment by Pzixel** [comment] 2022-01-06 22:21
```
git clone https://github.com/Pzixel/test-double-error.git
cd test-double-error
yarn install
export MAINNET_RPC_URL=https://api.mycryptoapi.com/eth
yarn run test
```

**Comment by Pzixel** [comment] 2022-06-04 07:50
Hello, ping?

**Comment by alcuadrado** [comment] 2022-06-05 21:53
Sorry I missed this, @Pzixel. Will get back to it this week.

**Comment by fvictorio** [comment] 2022-12-27 19:35
Hi @Pzixel, sorry for the very late response.

What's happening here is that Truffle's contract abstraction, for some reason, makes an `eth_call` after a transaction reverts. Since `eth_call`s also produce `console.sol` outputs, you are seeing the output twice.

I don't think there's much we can do. Maybe we could do some change in the `hardhat-truffle` plugin after #3224 is available. But for the time being I'm going to close this issue.

**Closed by fvictorio** 2022-12-27 19:35 UTC
