### ISSUE TITLE
Signers not available / documentation wrong

### ISSUE THREAD

**Issue by m1cm1c** [NomicFoundation/hardhat#4113] opened 2023-07-05 07:36 UTC
### Version of Hardhat

2.16.1

### What happened?

[The documentation says](https://hardhat.org/hardhat-runner/docs/other-guides/waffle-testing#testing-from-a-different-account) that `ethers.getSigners()` is a function, where `ethers` is an element of package `hardhat`. This was correct in hardhat version 2.14.1. However, in version 2.16.1, this function does not exist.

### Minimal reproduction steps

Check this code for compiler errors:

```
import {ethers} from 'hardhat';
ethers.getSigners();
```

### Search terms

getSigners

**Comment by fvictorio** [comment] 2023-07-06 17:01
You probably have a configuration issue around typescript. Try using this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  }
}
```

Tentatively closing, will re-open if this is a problem on our side.

**Closed by fvictorio** 2023-07-06 17:01 UTC
Labels: status:triaging

**Comment by m1cm1c** [comment] 2023-07-06 19:49
> You probably have a configuration issue around typescript. Try using this `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "es2020",
>     "module": "commonjs",
>     "esModuleInterop": true,
>     "forceConsistentCasingInFileNames": true,
>     "strict": true,
>     "skipLibCheck": true,
>     "resolveJsonModule": true
>   }
> }
> ```

I already used pretty much the same config. Using the config you posted did not solve the issue.

However, I still made a mistake when filing this bug report. The issue did not arise due to an upgrade from hardhat 2.14.1 to 2.16.1. Instead, it arose from an upgrade of @nomicfoundation/hardhat-toolbox@2.0.1 to @nomicfoundation/hardhat-toolbox@3.0.0. The latter depends on @nomicfoundation/hardhat-ethers@3.0.3, which installed ethers@6.6.2 because the package.json of @nomicfoundation/hardhat-ethers@3.0.3 lists `"ethers": "^6.1.0"` as a dependency. I.e. it enforces that ethers 6 is used. Before that, I used ethers 5 which works as described in hardhat's documentation.

> Tentatively closing, will re-open if this is a problem on our side.

The only problem on your side is that your documentation assumes that ethers 5 is used, whereas your product just changed as to require ethers 6, to which the code in your documentation is not applicable.

**Comment by alcuadrado** [comment] 2023-07-06 21:39
I think you somehow ended up with a node_modules with some incompatibilities that lead to the plugins working incorrectly. This could happen if, for example, you have multiple versions of the same component installed. If you can share your lockfile we'll be able to verify this. 

You can try killing your node_modules and lockfile and reinstalling from scratch. If that doesn't fix it the incompatibility must be in your package.json.

**Comment by m1cm1c** [comment] 2023-07-07 10:03
@alcuadrado Thank you very much for this offer. However, by now I have downgraded @nomicfoundation/hardhat-toolbox via `npm i @nomicfoundation/hardhat-toolbox@2.0.1`, which resolved my issue. So I don't think this is necessary.

However, in case anyone else who has this problem finds it useful, I will share my package files (`package.json` and `package-lock.json`) here regardless.

- original package files: https://gist.github.com/m1cm1c/23b0593c31cd1ca4958923e69c365441
- package files after dependabot performed updates: https://gist.github.com/m1cm1c/edac16431b63b8237daa6fb57927022b
- package files after i solved the issue using the above-mentioned command: https://gist.github.com/m1cm1c/1f05da74f31eb0e131d7fdc699d2681c

**Comment by alcuadrado** [comment] 2023-07-09 17:11
After inspecting the package-locks i'm convinced the problem is that you accidentally ended up with multiple versions of ethers. You can fix this by removing your lockfile and node_modules and reinstalling.

**Comment by m1cm1c** [comment] 2023-08-02 14:27
i'm finally getting around to migrating to ethers 6. i ran into the same issue again but this time i inspected types more carefully and discovered where things went wrong. posting it here in case other people find it useful

the problem was that `getSigners()` was read from a declaration in `typechain-types`. my typechain types had last been built for ethers v5, causing the types not to match up. after i ran `npx hardhat compile` to create the typechain types for ethers v6 (and restarting ts-server), `ethers.getSigners()` was found again
