### ISSUE TITLE
hardhat_reset does not reset forked chain

### ISSUE THREAD

**Issue by 3commascapital** [NomicFoundation/hardhat#2354] opened 2022-02-08 16:09 UTC
`hardhat_reset` command does not appear to do anything
```
import * as hardhat from 'hardhat'
main()

async function main() {
  const config = hardhat.config?.networks?.hardhat
  console.log('resetting chain')
  await hardhat.network.provider.request({
    method: "hardhat_reset",
    params: [{
      forking: {
        jsonRpcUrl: config.forking?.url,
        blockNumber: config.forking?.blockNumber,
      },
    }],
  })
...
```
this seems like a silent failure, i can see the hardhat terminal, operating with the same config, does not update it's empty blocks counter: `Mined empty block range #13505257 to #13505318`

**Comment by b-pmcg** [comment] 2022-02-11 20:54
How are you calling it? I've been trying to call `hardhat_reset` from inside a test and was successful by calling it from a script `npx hardhat run scripts/forkNetwork.js --network localhost`

**Comment by 3commascapital** [comment] 2022-02-11 20:59
yeah, this is exactly how i am calling it. here's some relevant info
1) the script in my previous comment is what is being called to try the reset
2) package.json script
```
"reset": "ts-node ./src/reset.ts",
```
3) `hardhat.config.ts`
```
...
  networks: {
    hardhat: {
      forking: {
        url: config.forkTarget.jsonRpcUrl,
        blockNumber: config.forkTarget.blockNumber,
      },
      accounts: config.wallet.privateKey ?
        privateKeyAccounts.map(privateKey => ({ privateKey, balance: hardhatBalance })) :
        { mnemonic: config.wallet.mnemonic, accountsBalance: hardhatBalance, count: 1 },
      blockGasLimit: 40_000_000,
      hardfork: "london",
      initialBaseFeePerGas: 0,
      mining: {
        auto: false,
        interval: [3000, 4000],
      },
    },
...
```

**Comment by 3commascapital** [comment] 2022-02-11 21:23
to be clear, i am starting up the forked node in one terminal, and resetting the fork to a particular block height in the other using this reset script. i am presuming that this how this is supposed to be done

**Comment by b-pmcg** [comment] 2022-02-11 22:05
One issue I had run into was not passing the correct network to my script, but it looks like you're using the default `hardhat` network. 
I changed my implementation a little bit. I have set up my call to `hardhat_reset` in a hardhat task called `fork` and I call it with an npm command that executes this: `npx hardhat fork --network localhost`.

I'm not affiliated with hardhat, I just happen to be working on a simlar problem right now.

**Comment by 3commascapital** [comment] 2022-02-11 22:17
for sure. no expectations, etc

yeah, i added a script just like you outlined in your previous response but to no avail.

**Comment by alcuadrado** [comment] 2022-02-12 19:00
@3commascapital can you elaborate on what you are expecting to happen?

@b-pmcg thanks for helping out!

**Comment by 3commascapital** [comment] 2022-02-13 21:36
hey @alcuadrado, yeah, so i am assuming that the fork i am running would be able to reset to the block height that is provided to it, but i don't see any new logs in the terminal where the fork is running and it seems like the transactions that i run in my scripts are skipped over (because they are already complete)

**Comment by alcuadrado** [comment] 2022-02-13 22:03
Do you have a repo to reproduce this? I think you are doing something slightly incorrect and this is not a bug. Something that could be happening is that you are running the script in a temporal hardhat network instance.

**Comment by iangregsondev** [comment] 2022-02-17 17:58
This also threw me a bit. I was running a forked version in one terminal window. Setup a few tasks to disable/enable logging and resetting the fork to a specific block number.

In the second terminal, just running the task actually uses a new forked version (i am assuming as my default is "hardhat", so it's important to pass in 

```
--network localhost
```

To get it to use these existing fork that is running on localhost.

Without passing in the --network then of course nothing works, the chain is not reset.

I wish I had found this post before lol :-)

I am considering whether things like this really belong in a task where I originally placed them.

I think a better alternative would be a script. Same functionality of course. So anything that calls the existing provider can be in a task but anything that requires a network change i.e. "localhost" then a task seems a better option. That's just in my mind, the functionality should be the same.

Cheers

**Comment by alcuadrado** [comment] 2022-02-17 18:08
@iangregsondev you can validate the network that your task is using. `hre.network.name` has that info.

**Comment by iangregsondev** [comment] 2022-02-17 18:10
Ah ok great, thank you.

**Comment by alcuadrado** [comment] 2022-02-18 13:10
You can also use `--network hardhat`, but that's the default network.

**Comment by alcuadrado** [comment] 2022-02-18 13:10
I'm closing this as it's not really a bug.

**Closed by alcuadrado** 2022-02-18 13:10 UTC
