### ISSUE TITLE
Describe.only does nothing...

### ISSUE THREAD

**Issue by JimLynchCodes** [NomicFoundation/hardhat#3012] opened 2022-08-04 18:07 UTC
Hi! I have a few test files in my project, and I would like to run only a single file.

I have seen others recommend to write "describe.only" in a test file to run only that describe block.

However, all my test files are run when I add this.

This is a bug because it should run ONLY the describe block marked with the .only but it incorrectly runs all describe blocks in all files.

**Comment by fvictorio** [comment] 2022-08-08 08:50
@JimLynchCodes can you provide reproduction steps? This works for me.

**Comment by fvictorio** [comment] 2022-08-20 22:32
Closing for lack of reproduction steps.

**Closed by fvictorio** 2022-08-20 22:32 UTC
