### ISSUE TITLE
`console.sol` not working on the tutorial

### ISSUE THREAD

**Issue by 0xapp123** [NomicFoundation/hardhat#5603] opened 2024-08-14 14:42 UTC
### Version of Hardhat

2.22.8

### What happened?

I followed your tutorial for my testing.

But I got 

`Error HH412: Invalid import hardhat/console.sol from contracts/Token.sol. Trying to import file using the own package's name.`

### Minimal reproduction steps

I followed the tutorial step by step and run with
`npx hardhat compile`
I got this error:
`Error HH412: Invalid import hardhat/console.sol from contracts/Token.sol. Trying to import file using the own package's name.`

### Search terms

hardhat, console, console.log, solidity

**Comment by kanej** [comment] 2024-08-15 09:12
I am closing this as a duplicate of https://github.com/NomicFoundation/hardhat/issues/3625

**Closed by kanej** 2024-08-15 09:12 UTC
Labels: status:triaging
