### ISSUE TITLE
`estimateGas` issue with hardhat network when autoMine is off

### ISSUE THREAD

**Issue by joyious** [NomicFoundation/hardhat#1836] opened 2021-08-30 04:02 UTC
We are having some issue with `estimateGas` when autoMine is off.

Hardhat version: version "2.6.1"

hardhat.config.js
```
    localhost: {
      hardfork: "istanbul",
    },
    hardhat: {
      hardfork: "istanbul",
    },
```

The `gasLimit` of the `hardhat` network is greatly larger than the `localhost` one, causing the transaction being dropped by the next block due to the block gasLimit constraint. The next block being mined can only hold 2 transactions.

The transaction data when sending to a `localhost` network:
```
{
  hash: '0x72d6362e91291c311012d9cef61b9c9f3ddcaa52b8706e2f0286550cc3a51aa6',
  type: null,
  accessList: null,
  blockHash: null,
  blockNumber: null,
  transactionIndex: null,
  confirmations: 0,
  from: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  gasPrice: BigNumber { _hex: '0x01dcd65000', _isBigNumber: true },
  gasLimit: BigNumber { _hex: '0x0ea7fd', _isBigNumber: true },
  to: '0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  nonce: 12,
  data: '0x42e77284000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000003c44cdddb6a900fa2b585dd299e03d12fa4293bc',
  r: '0xf24fb81b34cffd9463e22786632605125630dae1d9042d6b6def669353c9ea15',
  s: '0x0c77da00a7191abe556898036b6fb1c849107e39be70e2244943e5239f19730f',
  v: 62710,
  creates: null,
  chainId: 31337,
  wait: [Function (anonymous)]
}
```

The transaction data when sending to the default `hardhat` network:
```
{
  hash: '0x5dce93e43d33274b720399bb9e659b042990b4556980db79c0686affd5607bb8',
  type: null,
  accessList: null,
  blockHash: null,
  blockNumber: null,
  transactionIndex: null,
  confirmations: 0,
  from: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  gasPrice: BigNumber { _hex: '0x01dcd65000', _isBigNumber: true },
  gasLimit: BigNumber { _hex: '0x01badb18', _isBigNumber: true },
  to: '0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  nonce: 12,
  data: '0x42e77284000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000003c44cdddb6a900fa2b585dd299e03d12fa4293bc',
  r: '0xeb2a0c24521571805b031ef169984919de500112daee1a5008f05192580c7286',
  s: '0x7d3f542d5ca41c628f4e807fa1bc3b148db62a32b8e9933ead16a9a00f340034',
  v: 62710,
  creates: null,
  chainId: 31337,
  wait: [Function (anonymous)]
}
```

**Comment by fvictorio** [comment] 2021-08-30 19:25
@joyious `localhost` is the network running in `localhost:8545`, so the behavior depends on whatever you are running in that port. Do you mean that you are starting a `npx hardhat node`, connecting via localhost, and getting a different result?

**Comment by joyious** [comment] 2021-08-31 05:40
> @joyious `localhost` is the network running in `localhost:8545`, so the behavior depends on whatever you are running in that port. Do you mean that you are starting a `npx hardhat node`, connecting via localhost, and getting a different result?

**Comment by joyious** [comment] 2021-08-31 05:49
@fvictorio Yes. The `localhost` is running by `npx hardhat node`.

As you can see in the `hardhat.config.js`, at first I thought it may be related the the `London` hardfork, as we are adding many transactions into one block, the gasPrice may not be sufficient. But the `localhost` works fine with the `istanbul`  hardfork. As we dive deeper, it turned out that the gasLimit  seemed to be the reason why such transactions are dropped.

**Comment by fvictorio** [comment] 2021-08-31 12:53
@joyious I will need more precise reproduction steps. What transaction are you running? If you can create a minimal repo that I can just clone and run some commands to see the issue, that would be great.

**Comment by joyious** [comment] 2021-08-31 15:02
Sure. Here you go: https://github.com/joyious/hardhat-issue

**Comment by fvictorio** [comment] 2021-09-10 11:24
Hey @joyious, thanks for the reproduction repo and sorry for not getting back to you sooner.

I can confirm this happens. This is what I've seen so far:

- If you use `storage.estimateGas.store(1)`, the returned value is the same for the in-process hardhat network and for localhost.
- But when a tx is sent, the gas limit used is different in both cases
- Automining doesn't seem to matter, the same thing happens if I disable it

@alcuadrado maybe you have a quick guess about what could be happening here? Perhaps something related to the automatic gas provider?

**Comment by fvictorio** [comment] 2022-12-29 07:55
I believe this is caused by https://github.com/NomicFoundation/hardhat/issues/2159, so I'm going to close this one in favor of that.

**Closed by fvictorio** 2022-12-29 07:55 UTC
Labels: type:bug, priority:high
