### ISSUE TITLE
Error happened when i run 'npx hardhat'

### ISSUE THREAD

**Issue by GrumpyOnes** [NomicFoundation/hardhat#2769] opened 2022-05-28 10:12 UTC
```
xxxx/node_modules/@ethersproject/abi/lib/interface.js:22
var hash_1 = require("@ethersproject/hash");

Error [ERR_REQUIRE_ESM]: require() of ES Module /xxxx/node_modules/@ethersproject/hash/lib/index.js from /xxxx/node_modules/@ethersproject/abi/lib/interface.js not supported.
Instead change the require of index.js in /xxxx/node_modules/@ethersproject/abi/lib/interface.js to a dynamic import() which is available in all CommonJS modules.
```
- node 16.15.0

Maybe @ethersproject/hash @5.6.1 lead to this error ?, just conjecture.

**Comment by fvictorio** [comment] 2022-06-07 20:09
Hi @GrumpyOnes, this seems to be related to [ES modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), but it's hard to know the cause without more details.

I think ethers does publish ESM builds, maybe it's something related to that?

In any case, I don't think this is related to Hardhat itself, so I'm going to close the issue, but I don't mind helping you if you have specific questions, or if you can create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that shows that this is a problem in Hardhat itself.

**Closed by fvictorio** 2022-06-07 20:09 UTC
