### ISSUE TITLE
Gas estimation can cause "Insufficient fund" in the in-process network

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#2104] opened 2021-11-26 23:15 UTC
Reproduction:

1) Create the sample project and add this to the sample script:
    ```js
      const tx = await greeter.setGreeting("hi");

      console.log({tx});
    ```
2) Run the script and check the gas limit of the tx
3) It's something like `0x01bad6d8`, which doesn't make sense for this tx

This doesn't happen if you start a node and run the script with `--network localhost`

**Comment by fvictorio** [comment] 2021-11-29 19:11
Update: this is expected behavior for the in-process network, because it means not using an `eth_estimateGas` and therefore the execution is faster.

This isn't done when the `node` task is used because we don't have a reliable way to know that a given JSON-RPC endpoint corresponds to a Hardhat node.

Anyway, this is still an issue for people that are using an account that is not one of the default ones and doesn't have 1000 ETH. For example, you might create a new, random account that is funded with 0.1 ETH and then txs sent from that account will get an "insufficient funds" error.

One solution here is to cap the gas limit so that the cost of the tx won't be greater than the balance of the sender.

**Comment by fvictorio** [comment] 2021-11-29 19:16
Also: we should offer some way to opt-out of this behavior. For people using mainnet forking, the performance that is obtained from not calling `eth_estimateGas` is negligible in comparison with the actual execution times.

**Comment by feuGeneA** [comment] 2022-03-25 16:15
Duplicate of #2278

**Closed by feuGeneA** 2022-03-25 16:15 UTC
Labels: type:bug, priority:high, package:hardhat-core
