### ISSUE TITLE
buidler-evm issue with retrieving events

### ISSUE THREAD

**Issue by mrice32** [NomicFoundation/hardhat#785] opened 2020-09-11 19:59 UTC
We're trying to run tests that we previously ran with truffle in buidler and we're running into a strange issue when doing event queries. It's not reproducible on _every_ query, but it seems to happen deterministically within certain tests.

```
     TypeError: Cannot read property 'length' of undefined
      at topicMatched (/Users/matt/git/protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/filter.ts:120:45)
      at Object.filterLogs (/Users/matt/git/protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/filter.ts:95:10)
      at BuidlerNode.getLogs (/Users/matt/git/protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/node.ts:969:14)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at BuidlerEVMProvider.send (/Users/matt/git/protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:80:14)
      at Web3HTTPProviderAdapter._sendJsonRpcRequest (/Users/matt/git/protocol/packages/common/node_modules/@nomiclabs/buidler-web3/src/web3-provider-adapter.ts:80:22)
```

We've narrowed it to [this line](https://github.com/UMAprotocol/protocol/blob/9f91239647d36bfcd354026cced52274016f48cb/packages/liquidator/test/Liquidator.js#L222) in the test and [this query](https://github.com/UMAprotocol/protocol/blob/9f91239647d36bfcd354026cced52274016f48cb/packages/financial-templates-lib/src/clients/ExpiringMultiPartyClient.js#L121). It fails in many other test cases and scenarios, but we wanted to give a very particular case. If you'd like to investigate further, I'm happy to share a branch from our repo where you can reproduce!

**Comment by mrice32** [comment] 2020-09-11 20:16
Here's the branch where this can be repro'd: https://github.com/mrice32/protocol/tree/buidler.

If you pull down that branch (`git clone https://github.com/mrice32/protocol.git && git checkout buidler`), run:
```sh
yarn
yarn qbuild
cd packages/liquidator
yarn buidler test
```

This will run all the tests in that package and will show the above error for many of them.

**Comment by fvictorio** [comment] 2020-09-11 20:39
I actually get an error before that, when running `yarn qbuild`:

```
➜ yarn qbuild
yarn run v1.22.5
$ yarn lerna run build --stream --ignore '*/*dapp*'
$ /home/fvictorio/repos/protocol/node_modules/.bin/lerna run build --stream --ignore '*/*dapp*'
lerna notice cli v3.22.1
lerna info versioning independent
lerna notice filter excluding "*/*dapp*"
lerna info filter [ '!*/*dapp*' ]
lerna info Executing command in 1 package: "yarn run build"
@umaprotocol/core: $ yarn truffle compile && yarn load-addresses
@umaprotocol/core: $ /home/fvictorio/repos/protocol/node_modules/.bin/truffle compile
@umaprotocol/core: BuidlerError: BDLR5: BuidlerContext is not created.
@umaprotocol/core:     at Function.getBuidlerContext (/home/fvictorio/repos/protocol/packages/common/node_modules/@nomiclabs/buidler/src/internal/context.ts:32:13)
@umaprotocol/core:     at usePlugin (/home/fvictorio/repos/protocol/packages/common/node_modules/@nomiclabs/buidler/src/internal/core/config/config-env.ts:97:30)
...
```

The problem seems to be that you are requiring a buidler config outside a buidler context. Does that error not happen to you?

**Comment by mrice32** [comment] 2020-09-11 20:57
Sorry, this is an experimental branch, where we're trying to share the config. The qbuild step isn't necessary. You should be able to just run:
```
yarn
cd packages/liquidator
yarn buidler test
```

**Comment by mrice32** [comment] 2020-09-11 21:00
I think that's unrelated. Let me see if I can fix it. The reason I didn't see that error was that I had run the qbuild step before making some of the buidler-related changes.

**Comment by mrice32** [comment] 2020-09-11 21:12
@fvictorio sorry for the confusion. I've made a small update to the branch. The build issue should be fixed, and you should be able to see the test failures using that initial string of commands.

**Comment by fvictorio** [comment] 2020-09-21 12:29
Hey @mrice32, sorry for the late response.

I can confirm this is happening, but I'm not quite sure yet. We seem to be assuming that the `logs` entry of all transaction receipts have the same structure, but that doesn't seem to be the case? More specifically, we assume that each log has a `topics` property that is a `string[]`, but sometimes that property doesn't exist. That's why the `cannot read property length of undefined` shows up.

From what I can see, when the log doesn't have a `topics`, it does have a `signature` property.

This will need further investigation, but it definitely looks like a bug. I'm curious about why this hasn't happened before. Do you have a guess of something in your setup that might be different from a "normal" setup?

**Comment by mrice32** [comment] 2020-09-21 12:45
> Hey @mrice32, sorry for the late response.
> 
> I can confirm this is happening, but I'm not quite sure yet. We seem to be assuming that the `logs` entry of all transaction receipts have the same structure, but that doesn't seem to be the case? More specifically, we assume that each log has a `topics` property that is a `string[]`, but sometimes that property doesn't exist. That's why the `cannot read property length of undefined` shows up.
> 
> From what I can see, when the log doesn't have a `topics`, it does have a `signature` property.
> 
> This will need further investigation, but it definitely looks like a bug. I'm curious about why this hasn't happened before. Do you have a guess of something in your setup that might be different from a "normal" setup?

Thanks for looking into it!

Our setup is weird in a few ways:
- Our buidler config is shared across different packages in the monorepo, so we export a function to run the buidler setup and call that function on execution of the individual configs in the different packages. We are also customizing the file paths for the directories.
- We use a combination of web3 and truffle contract instantiations to query events and call functions. I know buidler modifies the truffle contract instantiations, but not sure if using both may cause issues. I believe that the calls in question are coming from web3 contract instantiations rather than truffle ones.

There certainly may be other types of strangeness in our setup, but those are the only two I can think of off the top of my head!

**Comment by alcuadrado** [comment] 2022-11-04 18:58
Hi,

I'm closing this issue as it has been a long time without activity, and it's unlikely it's still relevant/present.

Thanks for reporting it anyway, and please open a new one if you think it's needed.

**Closed by alcuadrado** 2022-11-04 18:58 UTC
Labels: type:bug
