### ISSUE TITLE
hardhat-solhint dependency is outdated

### ISSUE THREAD

**Issue by ItsNickBarry** [NomicFoundation/hardhat#1362] opened 2021-03-31 05:08 UTC
Required `solhint` version is `^2.0.0`, but `3.x.x` has been released.

**Comment by fluidsonic** [comment] 2021-07-03 18:57
Yes, please update :)

Might explain the following issues with more recent Node.js versions:

```text
 % hh check

(node:54631) [DEP0128] DeprecationWarning: Invalid 'main' field in '(…)/node_modules/antlr4/package.json' of 'src/antlr4/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:54631) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(node:54631) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```

**Comment by fvictorio** [comment] 2021-07-16 16:10
We need to do this, but release it as a new major version of the plugin.

**Comment by aspiers** [comment] 2021-10-03 03:21
Duplicate of #654?

**Closed** 2022-12-14 09:26 UTC
Labels: type:chore, package:hardhat-solhint, priority:medium
