### ISSUE TITLE
Feature request: Hardhat-etherscan support for Celo network

### ISSUE THREAD

**Issue by lazaralex98** [NomicFoundation/hardhat#3450] opened 2022-12-22 17:23 UTC
I intended to use `hardhat-etherscan` to verify some contracts I deployed on Celo. I was going to use [Celoscan](https://celoscan.io/), which is the Celo version of Etherscan (same team).

When listing the supported networks with `hardhat verify --list-networks` Celo is not there and I am using `"@nomiclabs/hardhat-etherscan": "^3.1.3"`.

I understand that I can add custom chains, so this feature is not urgent for me. But I am wondering if other people would like it too.

**Comment by fvictorio** [comment] 2022-12-22 18:32
Hi @lazaralex98, I think this is a duplicate of #2932.

**Closed by fvictorio** 2022-12-22 18:32 UTC
