### ISSUE TITLE
hardhat gas behaviour differs from geth

### ISSUE THREAD

**Issue by wighawag** [NomicFoundation/hardhat#3145] opened 2022-09-07 09:15 UTC
I was testing out a bug in solidity and found out that hardhat has a different gas behaviour that prevent me from testing the behaviour with hardhat

Reproduction repo has more details
https://github.com/bug-reproduction/solidity-assembly-variable-reset

but basically with that code 

```solidity
// SPDX-License-Identifier: AGPL-1.0
pragma solidity 0.8.16;

contract Test {
	event Debug(address deployedContract);

	function deployData(bytes calldata) external {
		address newContract;
		assembly {
			let len := calldataload(36)
			let p := mload(0x40)
			mstore(p, 0x61FFFF600E60003961FFFF6000F3000000000000000000000000000000000000)
			let lenByte1 := shr(8, len)
			let lenByte2 := and(len, 0xFF)
			mstore8(add(p, 1), lenByte1)
			mstore8(add(p, 2), lenByte2)
			mstore8(add(p, 9), lenByte1)
			mstore8(add(p, 10), lenByte2)
			calldatacopy(add(p, 14), 68, len)

			newContract := create(0, p, add(len, 14))
			log1(p, add(len, 14), newContract) // need this line, no idea why, looks like some memory management issues
		}
		emit Debug(newContract);
	}

}

```

If I execute deployData with an input of 24000 bytes, hardhat always fails while geth works

**Comment by fvictorio** [comment] 2022-09-07 16:42
Thank you Ronan, I'll take a look asap.

**Comment by fvictorio** [comment] 2022-09-09 09:35
Ok, I found what's going on here.

When you use the in-process hardhat network, we automatically use the block gas limit as the gas limit for all transactions. This makes execution faster, because no `estimateGas` is needed (which is slow).

To accomplish that behavior in ethers, we add a `gas` property to all the fragments in the `ContractFactory`. The problem is that ethers then [adds](https://github.com/ethers-io/ethers.js/blob/ec1b9583039a14a0e0fa15d0a2a6082a2f41cf5b/packages/contracts/src.ts/index.ts#L249-L262) the intrinsic cost of the tx to that gas value. So we subtract [one million](https://github.com/NomicFoundation/hardhat/blob/dbf7c0b33001ebca01ac3737e8599ef251cf0de7/packages/hardhat-ethers/src/internal/helpers.ts#L382-L387) to the block gas limit, asssuming no tx will have a intrinsic cost greater than that.

But guess what? Your transaction in that test has an intrinsic cost that is bigger than one million :sweat_smile:

The easiest workaround here is to disable that behavior in the hardhat network:

```
networks: {
  hardhat: {
    gas: "auto"
```

That will use `estimateGas` for all transactions, and you should get the same behavior as in geth.

Alternatively, you can add an explicit gas limit to the transactions that have a huge call data.

Obviously that's just a workaround, we need to figure out a proper solution somehow. But in the meantime, I hope that helps you as a temporary solution.

**Comment by wighawag** [comment] 2022-09-09 10:16
Thanks @fvictorio ! it works

**Comment by fvictorio** [comment] 2022-12-27 18:22
Closing this in favor of #3469.

**Closed by fvictorio** 2022-12-27 18:22 UTC
