### ISSUE TITLE
deploy error (version: 2.15.0 ): ProviderError: too many arguments, want at most 1

### ISSUE THREAD

**Issue by anbang** [NomicFoundation/hardhat#4010] opened 2023-06-09 10:23 UTC
### Version of Hardhat

2.15.0

### What happened?

deploy error when on other network

### Minimal reproduction steps

This is the example:  https://github.com/anbang/hardhat-deploy-example

- install :
  - `npm i`
- create `.env` file in project root path
  - mirror `.env.example`
- compile :
  - `npm run compile`
- deploy on blockchain network
  - ❌ run: `npm run d:o`  or  `npx hardhat run scripts/deploy.ts --network okchain`

Error info ：

**ProviderError: too many arguments, want at most 1**
    at HttpProvider.request (/Users/mac/Documents/xxxxxxxxxxxx/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersProvider.estimateGas (/Users/mac/Documents/xxxxxxxxxxxx/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:209:27)
    at async /Users/mac/Documents/xxxxxxxxxxxx/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 0)
    at async HardhatEthersSigner._sendUncheckedTransaction (/Users/mac/Documents/xxxxxxxxxxxx/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at async HardhatEthersSigner.sendTransaction (/Users/mac/Documents/xxxxxxxxxxxx/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async ContractFactory.deploy (/Users/mac/Documents/xxxxxxxxxxxx/node_modules/ethers/src.ts/contract/factory.ts:106:24)
    at async main (/Users/mac/Documents/xxxxxxxxxxxx/scripts/deploy.ts:9:16)

**Comment by fvictorio** [comment] 2023-06-09 11:25
I cannot reproduce this. I didn't do it in that okchain network, but the error you are getting shouldn't be affected by which network you are using.

Can you double check that those reproduction steps are accurate?

**Comment by validateITNikita** [comment] 2023-06-10 11:59
same issue with some other chain

**Comment by fvictorio** [comment] 2023-06-11 06:56
There isn't much we can do without reproduction steps.

**Comment by tnquanghuy0512** [comment] 2023-06-15 09:44
I have the same issue with okt chain

**Comment by Haripandey21** [comment] 2023-06-20 14:08
The OKChain network might have some issues because when I deployed the same contract on the Goerli network, it functioned perfectly. You can find the deployed address here: https://goerli.etherscan.io/address/0xfd472Ba195f2032fa8A59Ac97E031446aF434b37#code

**Comment by fvictorio** [comment] 2023-06-20 17:35
Thank you @Haripandey21. It seems like there's nothing we can do on our side, so I'm going to close this. I suggest reaching out to someone working on that chain's node implementation (or the node provider, idk) and letting them know about this.

**Closed by fvictorio** 2023-06-20 17:35 UTC
Labels: status:needs-more-info

**Comment by jveer634** [comment] 2023-06-29 10:40
@fvictorio We are facing similar issue on a different chain as well. Can you specify which part of the hardhat is bugging out. So that we can track down the error from our end as well.

**Comment by outSH** [comment] 2023-07-03 10:59
@anbang @jveer634 Try adding explicit `gasLimit` to the deployment transaction like this:

`const token = await ethers.deployContract("Token", { gasLimit: "0x1000000" });`

The problem is most probably caused by an outdated ethereum node (geth < 1.9.22 or similar) which doesn't support `eth_estimateGas` 2'nd argument (quantity / type, see https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_estimategas). `hardhat-ethers` seem to be compliant with the current API so I don't think there's an issue here.

**Comment by passabilities** [comment] 2023-07-27 00:58
I ran into this issue when deploying to Mantle network. I've confirmed with their dev team that this is an issue on their end with their RPC nodes. The solution for now is to hard code the `gasLimit` values when submitting the transaction. Specifically the issue was with the `eth_estimateGas` method before deploying a contract.

**Comment by 0xtrou** [comment] 2023-10-07 02:18
the old version works fine, since I upgraded hardhat and typechain it caused the error

**Comment by 0xtrou** [comment] 2023-10-07 02:41
@fvictorio can we do fallback to the old estimate gas version when the newer version causes error?

**Comment by fvictorio** [comment] 2023-10-10 18:49
@0xtrou unless I'm missing something, that behavior comes from ethers, not from our plugin, so you should try asking in their repo.
