### ISSUE TITLE
Forked hardhat node becomes unresponsive when connecting with Metamask

### ISSUE THREAD

**Issue by haydenyoung** [NomicFoundation/hardhat#2415] opened 2022-02-23 06:16 UTC
When running a local hardhat node from fork, the chain will become unresponsive when connecting with Metamask and no other interaction is possible, even from hardhat console.

To reproduce:

- Run hardhat node with a forked url. I've been using alchemy,

`npx hardhat node --verbose --no-deploy --fork http://alchemy-app-url`

where alchemy-app-url is some app configured on alchemy. Could be Infura or something else. Doesn't matter about the chain, can be testnet, can be polygon, the result is the same.

- Connect to hardhat node via console again:

`npx hardhat console`

Once connected, try executing something:

> const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545", ethers.provider.getNetwork(31337))
> await provider.send("evm_mine")

A block should be mined. hardhat node should also report this.

Exit out of console.

- Go to Metamask and connect to localhost:8545 using default hardhat chain id 31337.

- In Metamask, select a different network. I select Ethereum mainnet.

- Go back to localhost:8545 by selecting it again from Metamask's network dropdown.

Metamask will try and load localhost but will fail with a Try again message.

- Reconnect to hardhat node via console again:

`npx hardhat console`

Once connected, try executing something:

> const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545", ethers.provider.getNetwork(31337))
> await provider.send("evm_mine")

It will hang. No further communication will be able to be made with the local node.

I have also run node in verbose mode but there are no errors.

I have tried Metamask in Firefox, Brave and Chromium. Same results for each.

Running without --fork does not encounter this problem.

It seems to be the initial MM connection which causes the hardhat node to become unresponsive, hence any further communication, whether MM or console, seems to hang.

hardhat node throws no exceptions when it hangs.

**Comment by sennett** [comment] 2022-02-23 11:49
I am also seeing the same issue with forked hardhat.  After hanging it also increasing consumes more and more memory until it OOMs.

**Comment by haydenyoung** [comment] 2022-02-23 14:08
> I am also seeing the same issue with forking mainnet. After hanging it also consumes more and more memory until it OOMs. My colleagues' hardhats are fine - perhaps there is some dependency that has changed that causes this for people who have installed recently?

Could it be MM version specific? Running 10.9.3.

**Comment by alcuadrado** [comment] 2022-02-23 19:40
Thanks for reporting this issue and adding more info to help us debug it. 

This is a duplicate of #2380. I'm closing it to keep all the conversation there.

**Closed by alcuadrado** 2022-02-23 19:40 UTC
