### ISSUE TITLE
Unable to verify contracts with "import", and temporary solution

### ISSUE THREAD

**Issue by anh194** [NomicFoundation/hardhat#2236] opened 2022-01-10 04:29 UTC
I have problems deployed to testnet such as polygon mumbai. No problem if the contract does not import others libraries/contracts.

Version solidity: 0.8.9
Hardhat: 2.8.2
command:
`npx hardhat verify  --network polygonMumbai {contract address} --show-stack-traces`
Error:
```
Successfully submitted source code for contract
contracts/Match.sol:Match at 0x13Fc3017EFc2774f4B5f8F4e14cd00bCA4E2418d
for verification on the block explorer. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify
```

Solution:
I try to flatten the contract and verify it manually on polygonscan. 
`npx hardhat flatten {contract file location} > output.sol `

Polygonscan will return multiple SPDX. Manually remove extra SPDX in the flatten file (output.sol), and verify again will return successfully.

Maybe hardhat-etherscan does not remove extra SPDX after flattening the contracts?

**Comment by alcuadrado** [comment] 2022-01-10 13:13
Hey @anh194,

There's currently an issue with Mumbai contract deployments, and you may be affected by it. Can you tell us more info about your project? What does your setup look like?

Thanks

**Comment by anh194** [comment] 2022-01-10 14:23
Hi @alcuadrado 

I found the issue when testing the verify functionalities. You can easily reproduce the bug by deploy this simple contract and using hardhat-etherscan library to verify. I just import a random library, you can import anything to reproduce the bug.
```

// SPDX-License-Identifier: MIT
// pragma solidity >=0.4.22 <0.9.0;
pragma solidity ^0.8.0;

import "../node_modules/@chainlink/contracts/src/v0.8/VRFConsumerBase.sol";

contract Hello {
    int public tmp;

    function setTmp(int _tmp) public{
        tmp = _tmp;
    }

    function getTmp() view public returns(int){
        return tmp;
    }
}
```

`npx hardhat verify --contract "contracts/Hello.sol:Hello" --network polygonMumbai {address} --show-stack-traces`

Error log:
```
We tried verifying your contract Match without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/Match.sol:Match at 0x13Fc3017EFc2774f4B5f8F4e14cd00bCA4E2418d
for verification on the block explorer. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/anh/Documents/coin/flipcoin/js/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:332:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Environment._runTaskDefinition (/Users/anh/Documents/coin/flipcoin/js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/anh/Documents/coin/flipcoin/js/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at Environment._runTaskDefinition (/Users/anh/Documents/coin/flipcoin/js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/anh/Documents/coin/flipcoin/js/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at main (/Users/anh/Documents/coin/flipcoin/js/node_modules/hardhat/src/internal/cli/cli.ts:214:5
```

**Comment by snuffykl** [comment] 2022-02-20 13:38
I am having the same issue as @anh194 to verify contract in Fantom Testnet. Is there any updates on this issue ?

**Comment by magic990619** [comment] 2022-02-23 13:10
Same issue on polygonscan.

**Comment by alcuadrado** [comment] 2022-02-23 19:36
I'm closing this issue as I think there are multiple things being mixed here.

If you are having problems with Mumbai or Polygon, please look at #2312.

@anh194 sorry for the delay. I can't reproduce your problem.

**Closed by alcuadrado** 2022-02-23 19:36 UTC

**Comment by drinkius** [comment] 2022-04-20 22:34
Same issue with Fantom testnet - unable to verify contracts
