### ISSUE TITLE
verification of contract with hardhat-etherscan broken again

### ISSUE THREAD

**Issue by JEflyer** [NomicFoundation/hardhat#2465] opened 2022-03-08 07:27 UTC
When verifying my contract 5 days ago it worked, then it broke & started working again & now it has broke again.

Is there a ETA for this to be stable & working again?

I've updated to the latest version of hardhat-etherscan & tried previous versions with no working result.

**Comment by JEflyer** [comment] 2022-03-08 07:28
The error I'm receiving is the same as I got when it last broke. 

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify

**Comment by oishun1112** [comment] 2022-03-08 07:29
I'm having the same issue.

**Comment by JEflyer** [comment] 2022-03-08 07:32
Good to know I'm not the only one :')

**Comment by laygir** [comment] 2022-03-08 08:04
Same issues here 😔

**Comment by fvictorio** [comment] 2022-03-08 11:54
@JEflyer in which network are you trying to verify the contract?

**Comment by fvictorio** [comment] 2022-03-08 12:31
I was able to verify a contract on Rinkeby. We'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to investigate this. Please don't add "same issue" comments unless you can provide one.

**Comment by laygir** [comment] 2022-03-08 21:56
Hey @fvictorio 

Just created a new repo to test from scratch. Both rinkeby and ropsten seems to be working at the moment.

I had issues earlier for about 12 hours and stopped trying until now. If I remember correctly I was getting 403 with some html page throw as the error in the console.

If I encounter it again I'll post a screenshot and a reproduction case. Maybe it had to do with Etherscan api's. Perhaps error logging could be improved if Etherscan was the cause to make it clear that it has nothing to do with Hardhat but the underlying api is having issues.

**Comment by italosantana** [comment] 2022-03-08 23:08
@fvictorio  

$ '/home/italopc/workspace/web3-/node_modules/.bin/hardhat' verify --network ropsten 0x0f103a5a5ffcA469E9f9FE5097... param1 param2

Nothing to compile
No need to generate any newer typings.
Compiling 1 file with 0.8.4
Successfully submitted source code for contract
contracts/NFTCollection.sol:NFTCollection at 0x0f103a5a5ffcA469E9f9FE5097...
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract NFTCollection without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/NFTCollection.sol:NFTCollection at 0x0f103a5a5ffcA469E9f9FE5097...
for verification on the block explorer. Waiting for verification result...

**Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify**

using 
"@nomiclabs/hardhat-etherscan": "^2.1.8",
"@openzeppelin/contracts": "^4.5.0"

**Comment by oishun1112** [comment] 2022-03-09 05:42
@JEflyer @fvictorio  
Hi, now I can verify my code.

Yesterday, I failed verifying code that I could verify before, so I imagine that was something internal.
Anyway, it works now so I think we can close this issue

**Closed** 2022-03-09 06:32 UTC
