### ISSUE TITLE
Cannot run hardhat script in bun

### ISSUE THREAD

**Issue by mshakeg** [NomicFoundation/hardhat#4383] opened 2023-09-13 13:09 UTC
### Version of Hardhat

2.17.1

### What happened?

I created a `script.ts` file in `./scripts/ts` and I am trying to run it using [bun](https://github.com/oven-sh/bun), however it fails with the following error:
```
8 |     this._capacity = capacity
9 |     this._delimitedSuffix = delimitedSuffix
10 |     this._hashBitLength = hashBitLength
11 |     this._options = options
12 | 
13 |     this._state = new KeccakState()
                     ^
TypeError: Object is not a constructor (evaluating 'new KeccakState')
     at new Keccak (/Users/usr/hardhat-project/node_modules/.pnpm/keccak@3.0.3/node_modules/keccak/lib/api/keccak.js:13:18)
     at /Users/usr/hardhat-project/node_modules/.pnpm/keccak@3.0.3/node_modules/keccak/lib/api/index.js:12:31
     at keccak256 (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/util/keccak.js:9:4)
     at create (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/utils/random.js:10:26)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/utils/random.js:32:18
     at globalThis (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/utils/random.js:48:30)
     at require (:1:20)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/fork/ForkStateManager.js:10:6
     at globalThis (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/fork/ForkStateManager.js:299:27)
     at require (:1:20)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/node.js:65:6
     at globalThis (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/node.js:1800:22)
     at require (:1:20)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/provider.js:24:6
     at globalThis (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/hardhat-network/provider/provider.js:244:33)
     at require (:1:20)
     at importProvider (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/construction.js:19:16)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/construction.js:28:39
     at createProvider (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/construction.js:22:30)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/runtime-environment.js:92:97
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:30:44
     at init (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:27:17)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:121:34
     at _getOrInitProvider (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:114:31)
     at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:42:31
     at send (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.17.1_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/internal/core/providers/lazy-initialization.js:41:15)
     at /Users/usr/hardhat-project/scripts/ts/backtester.ts:9:18
     at processTicksAndRejections (:1:2602)
```

### Minimal reproduction steps

1. Create a simple `script.ts` file in `./scripts`

```typescript
import hre from "hardhat";
console.log(await hre.network.provider.send('eth_chainId'))
```

2. Try to run the file with bun: `bun run ./scripts/backtester.ts`, this should fail with the above error.

### Search terms

bun

**Comment by mshakeg** [comment] 2023-09-13 15:48
This issue seems a bit related to #2294

**Comment by schaable** [comment] 2023-09-19 19:58
Hi @mshakeg,

Thanks for reporting this issue. After investigating, it appears that the problem you've encountered is not directly related to Hardhat, but to the `keccak` package itself. 

You can verify this by creating a minimal project, installing the `keccak` package, and running the following test:

```javascript
import createKeccakHash from "keccak";

createKeccakHash("keccak256").update("Hello world!").digest("hex");
```

Executing the code above with bun will result in the same error. I recommend you to submit a bug report on [the keccak repo](https://github.com/cryptocoinjs/keccak/issues).

I'm closing this issue here since it appears unrelated to Hardhat.

**Closed by schaable** 2023-09-19 19:58 UTC
Labels: status:triaging

**Comment by mshakeg** [comment] 2023-09-19 21:36
Hi @schaable so this issue can be resolved in hardhat by using `keccak/js` as described [here](https://github.com/cryptocoinjs/keccak/issues/27#issuecomment-1726529255)

**Comment by junderw** [comment] 2023-09-20 08:00
This issue is already resolved and published in `3.0.4`.

Since hardhat uses `"keccak": "^3.0.2",` users of hardhat should have no issues with keccak and bun anymore.

**Comment by mshakeg** [comment] 2023-09-20 09:16
Thanks @junderw it's an improvement. Unfortunately, hardhat also has `undici` as a dependency and bun doesn't currently implement `undici.Pool.request` as described in oven-sh/bun/issues/1987

```
161 | class Pool extends Dispatcher {
162 |   constructor() {
163 |     super(...arguments);
164 |   }
165 | 
166 |   request() {

error: Not implemented in bun
      at request (undici:166:18)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/core/providers/http.js:103:35
      at _fetchJsonRpcResponse (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/core/providers/http.js:101:32)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/core/providers/http.js:52:38
      at request (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/core/providers/http.js:47:18)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/utils/makeForkClient.js:58:35
      at getNetworkId (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/utils/makeForkClient.js:57:28)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/utils/makeForkClient.js:21:28
      at makeForkClient (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/utils/makeForkClient.js:19:30)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/node.js:154:86
      at create (/Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/node.js:137:24)
      at /Users/usr/hardhat-project/node_modules/.pnpm/hardhat@2.12.2_ts-node@10.9.1_typescript@4.9.3/node_modules/hardhat/internal/hardhat-network/provider/provider.js:181:37
      at processTicksAndRejections (:1:2602)
```

**Comment by fvictorio** [comment] 2023-09-27 14:13
I want to point out that the problem is not that Hardhat doesn't work in bun: the problem is that bun doesn't support the things Hardhat is using. Bun's author [has been clear about this for other projects](https://twitter.com/jarredsumner/status/1700497869160268155). If you find a problem like this, please open an issue in Bun's repo.

**Comment by mshakeg** [comment] 2023-09-27 17:20
@fvictorio agreed, I don't really see an easy way to find issues that will cause hardhat to not run in bun(would probably have to go over each of hardhat's dependencies and each dependency's dependencies which is tedious), so I'm fine with going issue by issue.

oven-sh/bun/issues/1987 is the next one in line.
