### ISSUE TITLE
Executing `hardhat coverage` throws "typechain_1.glob is not a function"

### ISSUE THREAD

**Issue by barakman** [NomicFoundation/hardhat#1672] opened 2021-07-15 08:26 UTC
I haven't been able to figure out what's causing this, but it seems to be resolved when catching the exception thrown in [file runtime-environment.ts](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/core/runtime-environment.ts#L216-L221):
```
    try {
      return await taskDefinition.action(taskArguments, this, runSuper);
    } finally {
      uninjectFromGlobal();
      globalAsAny.runSuper = previousRunSuper;
    }
```
More precisely, when I add a `catch` between the `try` and the `finally`, the error (mentioned in the title) is not thrown, and the coverage begins.

Of course, this doesn't imply that the problem is in HardHat and not in my project's configuration of HardHat, but I would still be happy if you could look into it.

Thanks

**Comment by fvictorio** [comment] 2021-07-15 10:54
Hi @barakman, the `coverage` task is defined by [solidity-coverage](https://github.com/sc-forks/solidity-coverage), so you should open the issue there, unless you think the underlying issue is in hardhat's core.

**Comment by barakman** [comment] 2021-07-15 11:00
@fvictorio : I actually do think it's in hardhat's core, please see my description above (that file is even a part of hardhat's core).
An additional support to that claim is that this problem is not present when running  solidity-coverage, for example, via truffle.
Thanks you.

**Comment by barakman** [comment] 2021-07-15 12:17
After a bit more research, adding `taskArguments.noTypechain = true;` at the beginning of [function _runTaskDefinition](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/core/runtime-environment.ts#L179) seems to resolve the problem completely (i.e., without adding `catch` as previously mentioned.
So I tend to guess that this is a configuration parameter that I need to add in either my HH configuration or in my SC configuration.

**Comment by fvictorio** [comment] 2021-07-15 12:29
> I actually do think it's in hardhat's core, please see my description above (that file is even a part of hardhat's core).

The reason that `catch` fixes your issue is because that's the part of Hardhat that runs the task defined by the plugin, but that doesn't mean the problem is in Hardhat.

> After a bit more research, adding `taskArguments.noTypechain = true;` at the beginning of [function _runTaskDefinition](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/core/runtime-environment.ts#L179) seems to resolve the problem completely

That seems to suggest that there's an issue when using both solidity-coverage and typechain. If you have the time to create a minimal reproducible example, it would be very useful if you could submit it to the solidity-coverage repo.

**Comment by barakman** [comment] 2021-07-16 10:42
@fvictorio : This error also occurs (occasionally for some reason) on `hardhat compile`, so I think it is not directly related to solidity-coverage.

**Comment by fvictorio** [comment] 2021-07-16 11:25
If that's the case, we'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to look into it.

**Comment by sshmaxime** [comment] 2021-07-28 15:35
@fvictorio hey, i've made a minimal reproducible example here: https://github.com/sshmaxime/issue-replication/tree/glob_not_a_function. And here is attempt to resolve the issue - or at least spot the culprit: https://github.com/sshmaxime/issue-replication/tree/glob_not_a_function_fix. Hope you'll be able to look into that soon enough 🙏 🙏

**Comment by feuGeneA** [comment] 2021-08-06 20:17
I was trying to use `@typechain/hardhat` 2.3.0 and experiencing this error, and adding `typechain`@5.1.2 made it go away for me.

**Comment by nascimento-cesar** [comment] 2022-03-28 18:48
> Another common reason for this error is installing `@typechain/hardhat` and `@typechain/ethers-v5` in your project, importing typechain in your `hardhat-config.ts`, **but** _failing to install the `typechain` dependency in your package.json_

That solved my problem here! Thank you for your answer, @colinnielsen

**Comment by sridharreddyu** [comment] 2022-04-05 10:43
I face exact same issue during `npx hardhat compile`. After installing the typechain ` npm install --save-dev typechain` the problem is gone.

**Comment by danicunhac** [comment] 2022-04-09 18:35
I updated `typechain` version to the latest one and it worked fine.

**Comment by fvictorio** [comment] 2022-04-12 17:50
If I'm understanding this correctly, this doesn't happen if you have the latest version of `typechain` correctly installed.

I'm tentatively closing this again, because I guess there's nothing we can do. But, as always, feel free to comment if you think there's something we could do on our side.

**Closed by fvictorio** 2022-04-12 17:50 UTC
Labels: status:needs-research
