### ISSUE TITLE
eth_estimateGas - error , l can't connect my Dapp with my  

### ISSUE THREAD

**Issue by Programmer001-JS** [NomicFoundation/hardhat#3089] opened 2022-08-28 09:18 UTC
eth_estimateGas

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug

*** l can't connect and approve transactions with my wallet metamask.
l run - npx hardhat  test - in terminal , and l had 7 passing successfullytest, but in my npx hardhat node terminal i have this error.

**Comment by fvictorio** [comment] 2022-08-29 10:23
@Programmer001-JS can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by velateem** [comment] 2022-09-01 08:40
I have a same issue, we were trying to use metamask connect to hardhat node, and we could do the first transaction between the test wallets. However, when we try to do the second transaction , it would say 
"eth_estimateGas

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug"

and we need to restart the hardhat node and reset account on metamask.

**Comment by m1s5** [comment] 2022-09-11 10:18
same issue: 
• Bare node. No extra config
• Trying to connect with metamask

**Comment by vaxann** [comment] 2022-09-11 10:22
Problem the same as @m1s5, see screen
<img width="757" alt="Screenshot 2022-09-11 at 13 20 31" src="https://user-images.githubusercontent.com/582511/189522532-94f26cb6-6773-4b3c-b22b-e3a54169a0c1.png">

**Comment by lightrao** [comment] 2022-10-03 10:48
same problem

**Comment by victorshevtsov** [comment] 2022-10-16 15:32
Does anybody have a solution for that?
This issue has been reported already #1731 but not solved yet.

**Comment by victorshevtsov** [comment] 2022-10-16 16:34
It looks like the issue is in MetaMask browser extension.

It works just fine with MetaMask for Android.
All the transactions to `hardhat node` goes well when performed from mobile wallet but not from a browser extension.

I tried Chrome and FireFox extensions.

**Comment by victorshevtsov** [comment] 2022-10-16 19:23
Finally I got it!
It took almost whole day to figure out what is the cause.

The default `chainId` of Hardhat node is `31337` and this causes the issue.
I changed it to `1337` and everything works now.

```javascript
/// hardhat.config.js:

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.17",
  networks: {
    hardhat: {
      chainId: 1337, // default is 31337
    }
  }
};
```

I'm sure the root of the problem is out there.
I hope somebody will figure it out and get it fixed eventually.

**Comment by Programmer001-JS** [comment] 2022-11-03 18:59
Now l have this msg:

eth_sendRawTransaction

  Trying to send a raw transaction with an invalid chainId. The expected chainId is 31337

**Comment by nfts2me** [comment] 2022-11-16 18:18
Same error here using hardhat tests.
Using node I get this information

```
eth_accounts
eth_chainId
eth_estimateGas --> This in red

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/report-bug

.../contracts/node_modules/hardhat/internal/hardhat-network/stack-traces/solidity-errors.js:111
    return new SolidityCallSite(sourceReference.sourceName, sourceReference.contract, sourceReference.function !== undefined
                                                ^

TypeError: Cannot read properties of undefined (reading 'sourceName')
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by matilareo** [comment] 2022-11-22 04:27
Any workaround for this? iam facing the same issue

**Comment by RedHeadphone** [comment] 2022-11-28 05:54
> Any workaround for this? iam facing the same issue

@matilareo checkout this https://github.com/NomicFoundation/hardhat/issues/3089#issuecomment-1280036283

**Comment by benzsuankularb** [comment] 2022-12-06 07:04
I've tried other chain id than 31337 and hit the same issue.

Look like this is the issue of Metamask.
Where it assumed that 1337 is the only private test network chain id.
This is pretty unreasonable.

**Comment by fvictorio** [comment] 2022-12-28 07:23
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3474

For anyone landing here: a workaround is to set the initial base fee to 0:

```js
module.exports = {
  solidity: "0.8.17",
  networks: {
    hardhat: {
      initialBaseFeePerGas: 0
    },
  },
};
```

**Closed by fvictorio** 2022-12-28 07:23 UTC
